// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Controller struct {
	Cid      string
	Airport  pgtype.Text
	Position pgtype.Text
}

type Event struct {
	ID        string
	Type      pgtype.Text
	Timestamp pgtype.Text
	Cid       pgtype.Text
	Data      pgtype.Text
}

type Strip struct {
	ID                string
	Origin            pgtype.Text
	Destination       pgtype.Text
	Alternative       pgtype.Text
	Route             pgtype.Text
	Remarks           pgtype.Text
	AssignedSquawk    pgtype.Text
	Squawk            pgtype.Text
	Sid               pgtype.Text
	ClearedAltitude   pgtype.Text
	Heading           pgtype.Text
	AircraftType      pgtype.Text
	Runway            pgtype.Text
	RequestedAltitude pgtype.Text
	Capabilities      pgtype.Text
	CommunicationType pgtype.Text
	AircraftCategory  pgtype.Text
	Stand             pgtype.Text
	Sequence          pgtype.Text
	State             pgtype.Text
	Cleared           pgtype.Bool
	Positionfrequency pgtype.Text
	PositionLatitude  pgtype.Text
	PositionLongitude pgtype.Text
	PositionAltitude  pgtype.Text
	Tobt              pgtype.Text
	Tsat              pgtype.Text
	Ttot              pgtype.Text
	Ctot              pgtype.Text
	Aobt              pgtype.Text
	Asat              pgtype.Text
}
