// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
)

type Controller struct {
	Cid      string
	Airport  sql.NullString
	Position sql.NullString
}

type Event struct {
	ID        string
	Type      sql.NullString
	Timestamp sql.NullString
	Cid       sql.NullString
	Data      sql.NullString
}

type Strip struct {
	ID                string
	Origin            sql.NullString
	Destination       sql.NullString
	Alternative       sql.NullString
	Route             sql.NullString
	Remarks           sql.NullString
	AssignedSquawk    sql.NullString
	Squawk            sql.NullString
	Sid               sql.NullString
	ClearedAltitude   sql.NullString
	Heading           sql.NullString
	AircraftType      sql.NullString
	Runway            sql.NullString
	RequestedAltitude sql.NullString
	Capabilities      sql.NullString
	CommunicationType sql.NullString
	AircraftCategory  sql.NullString
	Stand             sql.NullString
	Sequence          sql.NullString
	State             sql.NullString
	Cleared           interface{}
	Positionfrequency sql.NullString
	PositionLatitude  sql.NullString
	PositionLongitude sql.NullString
	PositionAltitude  sql.NullString
	Tobt              sql.NullString
	Tsat              sql.NullString
	Ttot              sql.NullString
	Ctot              sql.NullString
	Aobt              sql.NullString
	Asat              sql.NullString
}
