// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package data

import (
	"context"
	"database/sql"
)

const insertController = `-- name: InsertController :exec
INSERT INTO controllers (
    cid, airport, position
) VALUES (
             ?, ?, ?
         )
`

type InsertControllerParams struct {
	Cid      string
	Airport  sql.NullString
	Position sql.NullString
}

func (q *Queries) InsertController(ctx context.Context, arg InsertControllerParams) error {
	_, err := q.db.ExecContext(ctx, insertController, arg.Cid, arg.Airport, arg.Position)
	return err
}

const insertStrip = `-- name: InsertStrip :exec
INSERT INTO strips (
    id, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, positionFrequency, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat
) VALUES (
             ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
         )
`

type InsertStripParams struct {
	ID                string
	Origin            sql.NullString
	Destination       sql.NullString
	Alternative       sql.NullString
	Route             sql.NullString
	Remarks           sql.NullString
	AssignedSquawk    sql.NullString
	Squawk            sql.NullString
	Sid               sql.NullString
	ClearedAltitude   sql.NullString
	Heading           sql.NullString
	AircraftType      sql.NullString
	Runway            sql.NullString
	RequestedAltitude sql.NullString
	Capabilities      sql.NullString
	CommunicationType sql.NullString
	AircraftCategory  sql.NullString
	Stand             sql.NullString
	Sequence          sql.NullString
	State             sql.NullString
	Cleared           interface{}
	Positionfrequency sql.NullString
	PositionLatitude  sql.NullString
	PositionLongitude sql.NullString
	PositionAltitude  sql.NullString
	Tobt              sql.NullString
	Tsat              sql.NullString
	Ttot              sql.NullString
	Ctot              sql.NullString
	Aobt              sql.NullString
	Asat              sql.NullString
}

func (q *Queries) InsertStrip(ctx context.Context, arg InsertStripParams) error {
	_, err := q.db.ExecContext(ctx, insertStrip,
		arg.ID,
		arg.Origin,
		arg.Destination,
		arg.Alternative,
		arg.Route,
		arg.Remarks,
		arg.AssignedSquawk,
		arg.Squawk,
		arg.Sid,
		arg.ClearedAltitude,
		arg.Heading,
		arg.AircraftType,
		arg.Runway,
		arg.RequestedAltitude,
		arg.Capabilities,
		arg.CommunicationType,
		arg.AircraftCategory,
		arg.Stand,
		arg.Sequence,
		arg.State,
		arg.Cleared,
		arg.Positionfrequency,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Tobt,
		arg.Tsat,
		arg.Ttot,
		arg.Ctot,
		arg.Aobt,
		arg.Asat,
	)
	return err
}

const listControllers = `-- name: ListControllers :many
SELECT cid, airport, position FROM controllers
`

func (q *Queries) ListControllers(ctx context.Context) ([]Controller, error) {
	rows, err := q.db.QueryContext(ctx, listControllers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Controller
	for rows.Next() {
		var i Controller
		if err := rows.Scan(&i.Cid, &i.Airport, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControllersByAirport = `-- name: ListControllersByAirport :many
SELECT cid, airport, position FROM controllers WHERE airport = ?
`

func (q *Queries) ListControllersByAirport(ctx context.Context, airport sql.NullString) ([]Controller, error) {
	rows, err := q.db.QueryContext(ctx, listControllersByAirport, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Controller
	for rows.Next() {
		var i Controller
		if err := rows.Scan(&i.Cid, &i.Airport, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStripsByOrigin = `-- name: ListStripsByOrigin :many
SELECT id, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, positionfrequency, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat FROM strips WHERE origin = ?
`

func (q *Queries) ListStripsByOrigin(ctx context.Context, origin sql.NullString) ([]Strip, error) {
	rows, err := q.db.QueryContext(ctx, listStripsByOrigin, origin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strip
	for rows.Next() {
		var i Strip
		if err := rows.Scan(
			&i.ID,
			&i.Origin,
			&i.Destination,
			&i.Alternative,
			&i.Route,
			&i.Remarks,
			&i.AssignedSquawk,
			&i.Squawk,
			&i.Sid,
			&i.ClearedAltitude,
			&i.Heading,
			&i.AircraftType,
			&i.Runway,
			&i.RequestedAltitude,
			&i.Capabilities,
			&i.CommunicationType,
			&i.AircraftCategory,
			&i.Stand,
			&i.Sequence,
			&i.State,
			&i.Cleared,
			&i.Positionfrequency,
			&i.PositionLatitude,
			&i.PositionLongitude,
			&i.PositionAltitude,
			&i.Tobt,
			&i.Tsat,
			&i.Ttot,
			&i.Ctot,
			&i.Aobt,
			&i.Asat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeController = `-- name: RemoveController :exec
DELETE FROM controllers WHERE cid = ?
`

func (q *Queries) RemoveController(ctx context.Context, cid string) error {
	_, err := q.db.ExecContext(ctx, removeController, cid)
	return err
}

const removeStripByID = `-- name: RemoveStripByID :exec
DELETE FROM strips WHERE id = ?
`

func (q *Queries) RemoveStripByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, removeStripByID, id)
	return err
}

const updateStripByID = `-- name: UpdateStripByID :exec
UPDATE strips SET (
        origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, positionFrequency, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat
) = (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
    ) WHERE id = ?
`

func (q *Queries) UpdateStripByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateStripByID, id)
	return err
}
