// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package data

import (
	"context"
	"database/sql"
)

const insertController = `-- name: InsertController :exec
INSERT INTO controllers (
    cid, airport, position
) VALUES (
             ?, ?, ?
         )
`

type InsertControllerParams struct {
	Cid      string
	Airport  sql.NullString
	Position sql.NullString
}

func (q *Queries) InsertController(ctx context.Context, arg InsertControllerParams) error {
	_, err := q.db.Exec(ctx, insertController, arg.Cid, arg.Airport, arg.Position)
	return err
}

const listControllers = `-- name: ListControllers :many
SELECT cid, airport, position FROM controllers
`

func (q *Queries) ListControllers(ctx context.Context) ([]Controller, error) {
	rows, err := q.db.Query(ctx, listControllers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Controller
	for rows.Next() {
		var i Controller
		if err := rows.Scan(&i.Cid, &i.Airport, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControllersByAirport = `-- name: ListControllersByAirport :many
SELECT cid, airport, position FROM controllers WHERE airport = ?
`

func (q *Queries) ListControllersByAirport(ctx context.Context, airport sql.NullString) ([]Controller, error) {
	rows, err := q.db.Query(ctx, listControllersByAirport, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Controller
	for rows.Next() {
		var i Controller
		if err := rows.Scan(&i.Cid, &i.Airport, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeController = `-- name: RemoveController :exec
DELETE FROM controllers WHERE cid = ?
`

func (q *Queries) RemoveController(ctx context.Context, cid string) error {
	_, err := q.db.Exec(ctx, removeController, cid)
	return err
}
