export var Capibilities;
(function (Capibilities) {
    Capibilities[Capibilities["?"] = 0] = "?";
    Capibilities[Capibilities["T"] = 1] = "T";
    Capibilities[Capibilities["X"] = 2] = "X";
    Capibilities[Capibilities["U"] = 3] = "U";
    Capibilities[Capibilities["D"] = 4] = "D";
    Capibilities[Capibilities["B"] = 5] = "B";
    Capibilities[Capibilities["A"] = 6] = "A";
    Capibilities[Capibilities["M"] = 7] = "M";
    Capibilities[Capibilities["N"] = 8] = "N";
    Capibilities[Capibilities["P"] = 9] = "P";
    Capibilities[Capibilities["Y"] = 10] = "Y";
    Capibilities[Capibilities["C"] = 11] = "C";
    Capibilities[Capibilities["I"] = 12] = "I";
    Capibilities[Capibilities["E"] = 13] = "E";
    Capibilities[Capibilities["F"] = 14] = "F";
    Capibilities[Capibilities["G"] = 15] = "G";
    Capibilities[Capibilities["R"] = 16] = "R";
    Capibilities[Capibilities["W"] = 17] = "W";
    Capibilities[Capibilities["Q"] = 18] = "Q";
})(Capibilities || (Capibilities = {}));
