// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airports.sql

package database

import (
	"context"
)

const insertAirport = `-- name: InsertAirport :exec
INSERT INTO airports (name)
VALUES ($1)
`

func (q *Queries) InsertAirport(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertAirport, name)
	return err
}
