// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: aman.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAMANAuditRecord = `-- name: CreateAMANAuditRecord :exec
INSERT INTO aman_audit_records (airport, revision, category, payload, recorded_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAMANAuditRecordParams struct {
	Airport    string
	Revision   int64
	Category   string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) CreateAMANAuditRecord(ctx context.Context, arg CreateAMANAuditRecordParams) error {
	_, err := q.db.Exec(ctx, createAMANAuditRecord,
		arg.Airport,
		arg.Revision,
		arg.Category,
		arg.Payload,
		arg.RecordedAt,
	)
	return err
}

const createAMANCommandOutcome = `-- name: CreateAMANCommandOutcome :exec
INSERT INTO aman_command_outcomes (command_id, airport, revision, payload, recorded_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAMANCommandOutcomeParams struct {
	CommandID  string
	Airport    string
	Revision   int64
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) CreateAMANCommandOutcome(ctx context.Context, arg CreateAMANCommandOutcomeParams) error {
	_, err := q.db.Exec(ctx, createAMANCommandOutcome,
		arg.CommandID,
		arg.Airport,
		arg.Revision,
		arg.Payload,
		arg.RecordedAt,
	)
	return err
}

const createAMANValidationEvidence = `-- name: CreateAMANValidationEvidence :exec
INSERT INTO aman_validation_evidence (evidence_id, airport, kind, payload, recorded_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAMANValidationEvidenceParams struct {
	EvidenceID string
	Airport    string
	Kind       string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) CreateAMANValidationEvidence(ctx context.Context, arg CreateAMANValidationEvidenceParams) error {
	_, err := q.db.Exec(ctx, createAMANValidationEvidence,
		arg.EvidenceID,
		arg.Airport,
		arg.Kind,
		arg.Payload,
		arg.RecordedAt,
	)
	return err
}

const deleteAMANFlightsForAirport = `-- name: DeleteAMANFlightsForAirport :exec
DELETE FROM aman_flights
WHERE airport = $1
`

func (q *Queries) DeleteAMANFlightsForAirport(ctx context.Context, airport string) error {
	_, err := q.db.Exec(ctx, deleteAMANFlightsForAirport, airport)
	return err
}

const getAMANAirportState = `-- name: GetAMANAirportState :one
SELECT airport, revision, generated_at, policy_version, mode, authoritative, runway_groups, updated_at
FROM aman_airport_states
WHERE airport = $1
`

func (q *Queries) GetAMANAirportState(ctx context.Context, airport string) (AmanAirportState, error) {
	row := q.db.QueryRow(ctx, getAMANAirportState, airport)
	var i AmanAirportState
	err := row.Scan(
		&i.Airport,
		&i.Revision,
		&i.GeneratedAt,
		&i.PolicyVersion,
		&i.Mode,
		&i.Authoritative,
		&i.RunwayGroups,
		&i.UpdatedAt,
	)
	return i, err
}

const getAMANCommandOutcome = `-- name: GetAMANCommandOutcome :one
SELECT command_id, airport, revision, payload, recorded_at
FROM aman_command_outcomes
WHERE command_id = $1
`

func (q *Queries) GetAMANCommandOutcome(ctx context.Context, commandID string) (AmanCommandOutcome, error) {
	row := q.db.QueryRow(ctx, getAMANCommandOutcome, commandID)
	var i AmanCommandOutcome
	err := row.Scan(
		&i.CommandID,
		&i.Airport,
		&i.Revision,
		&i.Payload,
		&i.RecordedAt,
	)
	return i, err
}

const listAMANAuditRecords = `-- name: ListAMANAuditRecords :many
SELECT id, airport, revision, category, payload, recorded_at
FROM aman_audit_records
WHERE airport = $1
ORDER BY revision, id
`

func (q *Queries) ListAMANAuditRecords(ctx context.Context, airport string) ([]AmanAuditRecord, error) {
	rows, err := q.db.Query(ctx, listAMANAuditRecords, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AmanAuditRecord
	for rows.Next() {
		var i AmanAuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.Airport,
			&i.Revision,
			&i.Category,
			&i.Payload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAMANFlights = `-- name: ListAMANFlights :many
SELECT airport, state, data_status, updated_at, payload, callsign
FROM aman_flights
WHERE airport = $1
ORDER BY callsign
`

func (q *Queries) ListAMANFlights(ctx context.Context, airport string) ([]AmanFlight, error) {
	rows, err := q.db.Query(ctx, listAMANFlights, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AmanFlight
	for rows.Next() {
		var i AmanFlight
		if err := rows.Scan(
			&i.Airport,
			&i.State,
			&i.DataStatus,
			&i.UpdatedAt,
			&i.Payload,
			&i.Callsign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAMANValidationEvidence = `-- name: ListAMANValidationEvidence :many
SELECT evidence_id, airport, kind, payload, recorded_at
FROM aman_validation_evidence
WHERE airport = $1
ORDER BY evidence_id
`

func (q *Queries) ListAMANValidationEvidence(ctx context.Context, airport string) ([]AmanValidationEvidence, error) {
	rows, err := q.db.Query(ctx, listAMANValidationEvidence, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AmanValidationEvidence
	for rows.Next() {
		var i AmanValidationEvidence
		if err := rows.Scan(
			&i.EvidenceID,
			&i.Airport,
			&i.Kind,
			&i.Payload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAMANAirportState = `-- name: LockAMANAirportState :one
SELECT revision
FROM aman_airport_states
WHERE airport = $1
FOR UPDATE
`

func (q *Queries) LockAMANAirportState(ctx context.Context, airport string) (int64, error) {
	row := q.db.QueryRow(ctx, lockAMANAirportState, airport)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const lockAMANCommand = `-- name: LockAMANCommand :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockAMANCommand(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockAMANCommand, hashtextextended)
	return err
}

const upsertAMANAirportState = `-- name: UpsertAMANAirportState :one
INSERT INTO aman_airport_states (
    airport, revision, generated_at, policy_version, mode, authoritative, runway_groups
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (airport) DO UPDATE
SET revision = EXCLUDED.revision,
    generated_at = EXCLUDED.generated_at,
    policy_version = EXCLUDED.policy_version,
    mode = EXCLUDED.mode,
    authoritative = EXCLUDED.authoritative,
    runway_groups = EXCLUDED.runway_groups,
    updated_at = NOW()
WHERE aman_airport_states.revision = $8
RETURNING airport, revision, generated_at, policy_version, mode, authoritative, runway_groups, updated_at
`

type UpsertAMANAirportStateParams struct {
	Airport       string
	Revision      int64
	GeneratedAt   pgtype.Timestamptz
	PolicyVersion string
	Mode          string
	Authoritative bool
	RunwayGroups  []byte
	Revision_2    int64
}

func (q *Queries) UpsertAMANAirportState(ctx context.Context, arg UpsertAMANAirportStateParams) (AmanAirportState, error) {
	row := q.db.QueryRow(ctx, upsertAMANAirportState,
		arg.Airport,
		arg.Revision,
		arg.GeneratedAt,
		arg.PolicyVersion,
		arg.Mode,
		arg.Authoritative,
		arg.RunwayGroups,
		arg.Revision_2,
	)
	var i AmanAirportState
	err := row.Scan(
		&i.Airport,
		&i.Revision,
		&i.GeneratedAt,
		&i.PolicyVersion,
		&i.Mode,
		&i.Authoritative,
		&i.RunwayGroups,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAMANFlight = `-- name: UpsertAMANFlight :exec
INSERT INTO aman_flights (
    airport, callsign, state, data_status, updated_at, payload
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (airport, callsign) DO UPDATE
SET
    state = EXCLUDED.state,
    data_status = EXCLUDED.data_status,
    updated_at = EXCLUDED.updated_at,
    payload = EXCLUDED.payload
`

type UpsertAMANFlightParams struct {
	Airport    string
	Callsign   string
	State      string
	DataStatus string
	UpdatedAt  pgtype.Timestamptz
	Payload    []byte
}

func (q *Queries) UpsertAMANFlight(ctx context.Context, arg UpsertAMANFlightParams) error {
	_, err := q.db.Exec(ctx, upsertAMANFlight,
		arg.Airport,
		arg.Callsign,
		arg.State,
		arg.DataStatus,
		arg.UpdatedAt,
		arg.Payload,
	)
	return err
}

const upsertAMANFlights = `-- name: UpsertAMANFlights :exec
INSERT INTO aman_flights (
    airport, callsign, state, data_status, updated_at, payload
)
SELECT $1::text, unnest($2::text[]),
    unnest($3::text[]), unnest($4::text[]),
    unnest($5::timestamptz[]), unnest($6::text[])::jsonb
ON CONFLICT (airport, callsign) DO UPDATE
SET
    state = EXCLUDED.state,
    data_status = EXCLUDED.data_status,
    updated_at = EXCLUDED.updated_at,
    payload = EXCLUDED.payload
`

type UpsertAMANFlightsParams struct {
	Airport      string
	Callsigns    []string
	States       []string
	DataStatuses []string
	UpdatedAts   []pgtype.Timestamptz
	Payloads     []string
}

func (q *Queries) UpsertAMANFlights(ctx context.Context, arg UpsertAMANFlightsParams) error {
	_, err := q.db.Exec(ctx, upsertAMANFlights,
		arg.Airport,
		arg.Callsigns,
		arg.States,
		arg.DataStatuses,
		arg.UpdatedAts,
		arg.Payloads,
	)
	return err
}
