// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: aman.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAMANAuditRecord = `-- name: CreateAMANAuditRecord :exec
INSERT INTO aman_audit_records (airport, revision, category, payload, recorded_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAMANAuditRecordParams struct {
	Airport    string
	Revision   int64
	Category   string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) CreateAMANAuditRecord(ctx context.Context, arg CreateAMANAuditRecordParams) error {
	_, err := q.db.Exec(ctx, createAMANAuditRecord,
		arg.Airport,
		arg.Revision,
		arg.Category,
		arg.Payload,
		arg.RecordedAt,
	)
	return err
}

const createAMANCommandOutcome = `-- name: CreateAMANCommandOutcome :exec
INSERT INTO aman_command_outcomes (command_id, airport, revision, payload, recorded_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAMANCommandOutcomeParams struct {
	CommandID  string
	Airport    string
	Revision   int64
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) CreateAMANCommandOutcome(ctx context.Context, arg CreateAMANCommandOutcomeParams) error {
	_, err := q.db.Exec(ctx, createAMANCommandOutcome,
		arg.CommandID,
		arg.Airport,
		arg.Revision,
		arg.Payload,
		arg.RecordedAt,
	)
	return err
}

const createAMANVATSIMObservationIdentity = `-- name: CreateAMANVATSIMObservationIdentity :one
INSERT INTO aman_vatsim_observation_identities (
    flight_id, vatsim_cid, current_callsign
)
VALUES ($1, $2, $3)
RETURNING flight_id, vatsim_cid, current_callsign, retired_at, created_at, updated_at
`

type CreateAMANVATSIMObservationIdentityParams struct {
	FlightID        string
	VatsimCid       string
	CurrentCallsign string
}

func (q *Queries) CreateAMANVATSIMObservationIdentity(ctx context.Context, arg CreateAMANVATSIMObservationIdentityParams) (AmanVatsimObservationIdentity, error) {
	row := q.db.QueryRow(ctx, createAMANVATSIMObservationIdentity, arg.FlightID, arg.VatsimCid, arg.CurrentCallsign)
	var i AmanVatsimObservationIdentity
	err := row.Scan(
		&i.FlightID,
		&i.VatsimCid,
		&i.CurrentCallsign,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAMANValidationEvidence = `-- name: CreateAMANValidationEvidence :exec
INSERT INTO aman_validation_evidence (evidence_id, airport, kind, payload, recorded_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAMANValidationEvidenceParams struct {
	EvidenceID string
	Airport    string
	Kind       string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) CreateAMANValidationEvidence(ctx context.Context, arg CreateAMANValidationEvidenceParams) error {
	_, err := q.db.Exec(ctx, createAMANValidationEvidence,
		arg.EvidenceID,
		arg.Airport,
		arg.Kind,
		arg.Payload,
		arg.RecordedAt,
	)
	return err
}

const deleteAMANFlightsForAirport = `-- name: DeleteAMANFlightsForAirport :exec
DELETE FROM aman_flights
WHERE airport = $1
`

func (q *Queries) DeleteAMANFlightsForAirport(ctx context.Context, airport string) error {
	_, err := q.db.Exec(ctx, deleteAMANFlightsForAirport, airport)
	return err
}

const getAMANAirportState = `-- name: GetAMANAirportState :one
SELECT airport, revision, generated_at, policy_version, mode, authoritative, runway_groups, updated_at
FROM aman_airport_states
WHERE airport = $1
`

func (q *Queries) GetAMANAirportState(ctx context.Context, airport string) (AmanAirportState, error) {
	row := q.db.QueryRow(ctx, getAMANAirportState, airport)
	var i AmanAirportState
	err := row.Scan(
		&i.Airport,
		&i.Revision,
		&i.GeneratedAt,
		&i.PolicyVersion,
		&i.Mode,
		&i.Authoritative,
		&i.RunwayGroups,
		&i.UpdatedAt,
	)
	return i, err
}

const getAMANCommandOutcome = `-- name: GetAMANCommandOutcome :one
SELECT command_id, airport, revision, payload, recorded_at
FROM aman_command_outcomes
WHERE command_id = $1
`

func (q *Queries) GetAMANCommandOutcome(ctx context.Context, commandID string) (AmanCommandOutcome, error) {
	row := q.db.QueryRow(ctx, getAMANCommandOutcome, commandID)
	var i AmanCommandOutcome
	err := row.Scan(
		&i.CommandID,
		&i.Airport,
		&i.Revision,
		&i.Payload,
		&i.RecordedAt,
	)
	return i, err
}

const getActiveAMANVATSIMObservationIdentity = `-- name: GetActiveAMANVATSIMObservationIdentity :one
SELECT flight_id, vatsim_cid, current_callsign, retired_at, created_at, updated_at
FROM aman_vatsim_observation_identities
WHERE vatsim_cid = $1
  AND retired_at IS NULL
`

func (q *Queries) GetActiveAMANVATSIMObservationIdentity(ctx context.Context, vatsimCid string) (AmanVatsimObservationIdentity, error) {
	row := q.db.QueryRow(ctx, getActiveAMANVATSIMObservationIdentity, vatsimCid)
	var i AmanVatsimObservationIdentity
	err := row.Scan(
		&i.FlightID,
		&i.VatsimCid,
		&i.CurrentCallsign,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAMANAuditRecords = `-- name: ListAMANAuditRecords :many
SELECT id, airport, revision, category, payload, recorded_at
FROM aman_audit_records
WHERE airport = $1
ORDER BY revision, id
`

func (q *Queries) ListAMANAuditRecords(ctx context.Context, airport string) ([]AmanAuditRecord, error) {
	rows, err := q.db.Query(ctx, listAMANAuditRecords, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AmanAuditRecord
	for rows.Next() {
		var i AmanAuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.Airport,
			&i.Revision,
			&i.Category,
			&i.Payload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAMANFlights = `-- name: ListAMANFlights :many
SELECT flight_id, airport, vatsim_cid, current_callsign, state, data_status, updated_at, payload
FROM aman_flights
WHERE airport = $1
ORDER BY flight_id
`

func (q *Queries) ListAMANFlights(ctx context.Context, airport string) ([]AmanFlight, error) {
	rows, err := q.db.Query(ctx, listAMANFlights, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AmanFlight
	for rows.Next() {
		var i AmanFlight
		if err := rows.Scan(
			&i.FlightID,
			&i.Airport,
			&i.VatsimCid,
			&i.CurrentCallsign,
			&i.State,
			&i.DataStatus,
			&i.UpdatedAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAMANValidationEvidence = `-- name: ListAMANValidationEvidence :many
SELECT evidence_id, airport, kind, payload, recorded_at
FROM aman_validation_evidence
WHERE airport = $1
ORDER BY evidence_id
`

func (q *Queries) ListAMANValidationEvidence(ctx context.Context, airport string) ([]AmanValidationEvidence, error) {
	rows, err := q.db.Query(ctx, listAMANValidationEvidence, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AmanValidationEvidence
	for rows.Next() {
		var i AmanValidationEvidence
		if err := rows.Scan(
			&i.EvidenceID,
			&i.Airport,
			&i.Kind,
			&i.Payload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAMANAirportState = `-- name: LockAMANAirportState :one
SELECT revision
FROM aman_airport_states
WHERE airport = $1
FOR UPDATE
`

func (q *Queries) LockAMANAirportState(ctx context.Context, airport string) (int64, error) {
	row := q.db.QueryRow(ctx, lockAMANAirportState, airport)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const lockAMANCommand = `-- name: LockAMANCommand :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockAMANCommand(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockAMANCommand, hashtextextended)
	return err
}

const lockAMANVATSIMObservationIdentity = `-- name: LockAMANVATSIMObservationIdentity :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockAMANVATSIMObservationIdentity(ctx context.Context, hashtextextended string) error {
	_, err := q.db.Exec(ctx, lockAMANVATSIMObservationIdentity, hashtextextended)
	return err
}

const retireAMANVATSIMObservationIdentity = `-- name: RetireAMANVATSIMObservationIdentity :execrows
UPDATE aman_vatsim_observation_identities
SET retired_at = NOW(),
    updated_at = NOW()
WHERE flight_id = $1
  AND retired_at IS NULL
`

func (q *Queries) RetireAMANVATSIMObservationIdentity(ctx context.Context, flightID string) (int64, error) {
	result, err := q.db.Exec(ctx, retireAMANVATSIMObservationIdentity, flightID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAMANVATSIMObservationIdentityCallsign = `-- name: UpdateAMANVATSIMObservationIdentityCallsign :one
UPDATE aman_vatsim_observation_identities
SET current_callsign = $2,
    updated_at = NOW()
WHERE flight_id = $1
  AND retired_at IS NULL
RETURNING flight_id, vatsim_cid, current_callsign, retired_at, created_at, updated_at
`

type UpdateAMANVATSIMObservationIdentityCallsignParams struct {
	FlightID        string
	CurrentCallsign string
}

func (q *Queries) UpdateAMANVATSIMObservationIdentityCallsign(ctx context.Context, arg UpdateAMANVATSIMObservationIdentityCallsignParams) (AmanVatsimObservationIdentity, error) {
	row := q.db.QueryRow(ctx, updateAMANVATSIMObservationIdentityCallsign, arg.FlightID, arg.CurrentCallsign)
	var i AmanVatsimObservationIdentity
	err := row.Scan(
		&i.FlightID,
		&i.VatsimCid,
		&i.CurrentCallsign,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAMANAirportState = `-- name: UpsertAMANAirportState :one
INSERT INTO aman_airport_states (
    airport, revision, generated_at, policy_version, mode, authoritative, runway_groups
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (airport) DO UPDATE
SET revision = EXCLUDED.revision,
    generated_at = EXCLUDED.generated_at,
    policy_version = EXCLUDED.policy_version,
    mode = EXCLUDED.mode,
    authoritative = EXCLUDED.authoritative,
    runway_groups = EXCLUDED.runway_groups,
    updated_at = NOW()
WHERE aman_airport_states.revision = $8
RETURNING airport, revision, generated_at, policy_version, mode, authoritative, runway_groups, updated_at
`

type UpsertAMANAirportStateParams struct {
	Airport       string
	Revision      int64
	GeneratedAt   pgtype.Timestamptz
	PolicyVersion string
	Mode          string
	Authoritative bool
	RunwayGroups  []byte
	Revision_2    int64
}

func (q *Queries) UpsertAMANAirportState(ctx context.Context, arg UpsertAMANAirportStateParams) (AmanAirportState, error) {
	row := q.db.QueryRow(ctx, upsertAMANAirportState,
		arg.Airport,
		arg.Revision,
		arg.GeneratedAt,
		arg.PolicyVersion,
		arg.Mode,
		arg.Authoritative,
		arg.RunwayGroups,
		arg.Revision_2,
	)
	var i AmanAirportState
	err := row.Scan(
		&i.Airport,
		&i.Revision,
		&i.GeneratedAt,
		&i.PolicyVersion,
		&i.Mode,
		&i.Authoritative,
		&i.RunwayGroups,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAMANFlight = `-- name: UpsertAMANFlight :exec
INSERT INTO aman_flights (
    flight_id, airport, vatsim_cid, current_callsign, state, data_status, updated_at, payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (flight_id) DO UPDATE
SET airport = EXCLUDED.airport,
    vatsim_cid = EXCLUDED.vatsim_cid,
    current_callsign = EXCLUDED.current_callsign,
    state = EXCLUDED.state,
    data_status = EXCLUDED.data_status,
    updated_at = EXCLUDED.updated_at,
    payload = EXCLUDED.payload
`

type UpsertAMANFlightParams struct {
	FlightID        string
	Airport         string
	VatsimCid       string
	CurrentCallsign string
	State           string
	DataStatus      string
	UpdatedAt       pgtype.Timestamptz
	Payload         []byte
}

func (q *Queries) UpsertAMANFlight(ctx context.Context, arg UpsertAMANFlightParams) error {
	_, err := q.db.Exec(ctx, upsertAMANFlight,
		arg.FlightID,
		arg.Airport,
		arg.VatsimCid,
		arg.CurrentCallsign,
		arg.State,
		arg.DataStatus,
		arg.UpdatedAt,
		arg.Payload,
	)
	return err
}
