// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"FlightStrips/pkg/models"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiracnetHttpCheckpoint struct {
	RequestKey   string
	Etag         string
	LastModified string
	NextPage     int32
	ResponseBody []byte
	UpdatedAt    pgtype.Timestamptz
}

type Airport struct {
	Name string
}

type AirportMasterOrder struct {
	ID       int32
	Airport  string
	Position string
	Priority int32
}

type AmanAirportState struct {
	Airport       string
	Revision      int64
	GeneratedAt   pgtype.Timestamptz
	PolicyVersion string
	Mode          string
	Authoritative bool
	RunwayGroups  []byte
	UpdatedAt     pgtype.Timestamptz
}

type AmanAuditRecord struct {
	ID         int64
	Airport    string
	Revision   int64
	Category   string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

type AmanCommandOutcome struct {
	CommandID  string
	Airport    string
	Revision   int64
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

type AmanFlight struct {
	FlightID        string
	Airport         string
	VatsimCid       string
	CurrentCallsign string
	State           string
	DataStatus      string
	UpdatedAt       pgtype.Timestamptz
	Payload         []byte
}

type AmanNavActiveManifest struct {
	Airport    string
	ManifestID int64
	Revision   int64
}

type AmanNavAirportFragment struct {
	Digest          string
	SchemaVersion   string
	Cycle           string
	SourceRevision  string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveUntil  pgtype.Timestamptz
	Airport         string
	Provenance      []byte
	ValidationState string
	ImportedAt      pgtype.Timestamptz
	ValidatedAt     pgtype.Timestamptz
	Payload         []byte
}

type AmanNavFixFragment struct {
	Digest          string
	SchemaVersion   string
	Cycle           string
	SourceRevision  string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveUntil  pgtype.Timestamptz
	Provenance      []byte
	ValidationState string
	ImportedAt      pgtype.Timestamptz
	ValidatedAt     pgtype.Timestamptz
	Payload         []byte
}

type AmanNavManifest struct {
	ManifestID       int64
	Airport          string
	Revision         int64
	Cycle            string
	SourceRevision   string
	EffectiveFrom    pgtype.Timestamptz
	EffectiveUntil   pgtype.Timestamptz
	AirportDigest    string
	ProcedureDigests []byte
	FixDigest        string
	TerminalDigest   *string
	CreatedAt        pgtype.Timestamptz
}

type AmanNavProcedureFragment struct {
	Digest          string
	SchemaVersion   string
	Cycle           string
	SourceRevision  string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveUntil  pgtype.Timestamptz
	Airport         string
	ProcedureKind   string
	Provenance      []byte
	ValidationState string
	ImportedAt      pgtype.Timestamptz
	ValidatedAt     pgtype.Timestamptz
	Payload         []byte
}

type AmanNavRouteCache struct {
	CacheKey        string
	SemanticKey     string
	ResolverVersion string
	SchemaVersion   string
	RouteDigest     string
	Provenance      []byte
	CreatedAt       pgtype.Timestamptz
	Query           []byte
	Payload         []byte
}

type AmanNavTerminalFragment struct {
	Digest          string
	SchemaVersion   string
	Cycle           string
	SourceRevision  string
	EffectiveFrom   pgtype.Timestamptz
	EffectiveUntil  pgtype.Timestamptz
	Airport         string
	ConfigVersion   string
	Provenance      []byte
	ValidationState string
	ImportedAt      pgtype.Timestamptz
	ValidatedAt     pgtype.Timestamptz
	Payload         []byte
}

type AmanValidationEvidence struct {
	EvidenceID string
	Airport    string
	Kind       string
	Payload    []byte
	RecordedAt pgtype.Timestamptz
}

type AmanVatsimObservationIdentity struct {
	FlightID        string
	VatsimCid       string
	CurrentCallsign string
	RetiredAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Controller struct {
	ID                int32
	Session           int32
	Callsign          string
	Position          string
	Cid               *string
	LastSeenEuroscope pgtype.Timestamp
	LastSeenFrontend  pgtype.Timestamp
	Layout            *string
	Observer          bool
}

type Coordination struct {
	ID            int32
	Session       int32
	StripID       int32
	FromPosition  string
	ToPosition    string
	CoordinatedAt pgtype.Timestamp
	FromEs        bool
	EsHandoverCid *string
	IsTagRequest  bool
}

type SectorOwner struct {
	ID         int32
	Session    int32
	Sector     []string
	Position   string
	Identifier string
}

type Session struct {
	ID                 int32
	Name               string
	Airport            string
	ActiveRunways      models.ActiveRunways
	PdcSequence        int32
	PdcMessageSequence int32
	AvailableSids      models.AvailableSids
	CdmMaster          bool
}

type StandAssignment struct {
	ID             int64
	SessionID      int32
	Callsign       string
	Stand          string
	Direction      string
	Stage          string
	Source         string
	RuleID         *string
	Tier           *int32
	MatchedVariant *string
	Eta            pgtype.Timestamptz
	EtaSource      *string
	AssignedAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	Manual         bool
	Acknowledged   bool
	AcknowledgedAt pgtype.Timestamptz
	AcknowledgedBy *string
	VatsimCid      *int64
	VatsimRevision *int64
	Version        int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ConflictReason *string
}

type StandBlock struct {
	ID        int64
	SessionID int32
	Stand     string
	BlockType string
	Source    string
	Reason    *string
	Callsign  *string
	CreatedBy *string
	ExpiresAt pgtype.Timestamptz
	Manual    bool
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Strip struct {
	ID                       int32
	Version                  int32
	Callsign                 string
	Session                  int32
	Origin                   string
	Destination              string
	Alternative              *string
	Route                    *string
	Remarks                  *string
	AssignedSquawk           *string
	Squawk                   *string
	Sid                      *string
	ClearedAltitude          *int32
	Heading                  *int32
	AircraftType             *string
	Runway                   *string
	RequestedAltitude        *int32
	Capabilities             *string
	CommunicationType        *string
	AircraftCategory         *string
	Stand                    *string
	Sequence                 *int32
	State                    *string
	Cleared                  bool
	Owner                    *string
	Bay                      string
	PositionLatitude         *float64
	PositionLongitude        *float64
	PositionAltitude         *int32
	NextOwners               []string
	PreviousOwners           []string
	ReleasePoint             *string
	Marked                   bool
	Registration             *string
	TrackingController       string
	RunwayCleared            bool
	UnexpectedChangeFields   []string
	ControllerModifiedFields []string
	EngineType               string
	IsManual                 bool
	PersonsOnBoard           *int32
	FplType                  *string
	Language                 *string
	HasFp                    bool
	CdmData                  []byte
	RunwayConfirmed          bool
	PdcData                  []byte
	ValidationStatus         []byte
	StartReq                 bool
	SpokenCallsign           *string
	VatsimCid                *string
	VatsimRevision           *int64
	VatsimSeenAt             pgtype.Timestamptz
	EuroscopeSeenAt          pgtype.Timestamptz
	ArrivalEta               []byte
	Star                     *string
}

type TacticalStrip struct {
	ID          int64
	SessionID   int32
	Type        string
	Bay         string
	Label       string
	Aircraft    *string
	ProducedBy  string
	Sequence    int32
	Confirmed   bool
	ConfirmedBy *string
	CreatedAt   pgtype.Timestamptz
	Owner       string
	Marked      bool
}

type Version struct {
	ID        int32
	Name      string
	AppliedAt pgtype.Timestamp
}
