// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"FlightStrips/pkg/models"
	"github.com/jackc/pgx/v5/pgtype"
)

type Airport struct {
	Name string
}

type AirportMasterOrder struct {
	ID       int32
	Airport  string
	Position string
	Priority int32
}

type Controller struct {
	ID                int32
	Session           int32
	Callsign          string
	Position          string
	Cid               pgtype.Text
	LastSeenEuroscope pgtype.Timestamp
	LastSeenFrontend  pgtype.Timestamp
}

type Coordination struct {
	ID            int32
	Session       int32
	StripID       int32
	FromPosition  string
	ToPosition    string
	CoordinatedAt pgtype.Timestamp
}

type SectorOwner struct {
	ID         int32
	Session    int32
	Sector     []string
	Position   string
	Identifier string
}

type Session struct {
	ID            int32
	Name          string
	Airport       string
	ActiveRunways models.ActiveRunways
}

type Strip struct {
	ID                int32
	Version           int32
	Callsign          string
	Session           int32
	Origin            string
	Destination       string
	Alternative       pgtype.Text
	Route             pgtype.Text
	Remarks           pgtype.Text
	AssignedSquawk    pgtype.Text
	Squawk            pgtype.Text
	Sid               pgtype.Text
	ClearedAltitude   pgtype.Int4
	Heading           pgtype.Int4
	AircraftType      pgtype.Text
	Runway            pgtype.Text
	RequestedAltitude pgtype.Int4
	Capabilities      pgtype.Text
	CommunicationType pgtype.Text
	AircraftCategory  pgtype.Text
	Stand             pgtype.Text
	Sequence          pgtype.Int4
	State             pgtype.Text
	Cleared           pgtype.Bool
	Owner             pgtype.Text
	Bay               pgtype.Text
	PositionLatitude  pgtype.Float8
	PositionLongitude pgtype.Float8
	PositionAltitude  pgtype.Int4
	Tobt              pgtype.Text
	Tsat              pgtype.Text
	Ttot              pgtype.Text
	Ctot              pgtype.Text
	Aobt              pgtype.Text
	Asat              pgtype.Text
	Eobt              pgtype.Text
	NextOwners        []string
	PreviousOwners    []string
}

type Version struct {
	ID        int32
	Name      string
	AppliedAt pgtype.Timestamp
}
