// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"FlightStrips/pkg/models"
	"github.com/jackc/pgx/v5/pgtype"
)

type Airport struct {
	Name string
}

type AirportMasterOrder struct {
	ID       int32
	Airport  string
	Position string
	Priority int32
}

type Controller struct {
	ID                int32
	Session           int32
	Callsign          string
	Position          string
	Cid               *string
	LastSeenEuroscope pgtype.Timestamp
	LastSeenFrontend  pgtype.Timestamp
	Layout            *string
}

type Coordination struct {
	ID            int32
	Session       int32
	StripID       int32
	FromPosition  string
	ToPosition    string
	CoordinatedAt pgtype.Timestamp
	FromEs        bool
	EsHandoverCid *string
	IsTagRequest  bool
}

type SectorOwner struct {
	ID         int32
	Session    int32
	Sector     []string
	Position   string
	Identifier string
}

type Session struct {
	ID                 int32
	Name               string
	Airport            string
	ActiveRunways      models.ActiveRunways
	PdcSequence        int32
	PdcMessageSequence int32
	AvailableSids      models.AvailableSids
	CdmMaster          bool
}

type Strip struct {
	ID                       int32
	Version                  int32
	Callsign                 string
	Session                  int32
	Origin                   string
	Destination              string
	Alternative              *string
	Route                    *string
	Remarks                  *string
	AssignedSquawk           *string
	Squawk                   *string
	Sid                      *string
	ClearedAltitude          *int32
	Heading                  *int32
	AircraftType             *string
	Runway                   *string
	RequestedAltitude        *int32
	Capabilities             *string
	CommunicationType        *string
	AircraftCategory         *string
	Stand                    *string
	Sequence                 *int32
	State                    *string
	Cleared                  bool
	Owner                    *string
	Bay                      string
	PositionLatitude         *float64
	PositionLongitude        *float64
	PositionAltitude         *int32
	NextOwners               []string
	PreviousOwners           []string
	ReleasePoint             *string
	Marked                   bool
	Registration             *string
	TrackingController       string
	RunwayCleared            bool
	UnexpectedChangeFields   []string
	ControllerModifiedFields []string
	EngineType               string
	IsManual                 bool
	PersonsOnBoard           *int32
	FplType                  *string
	Language                 *string
	HasFp                    bool
	CdmData                  []byte
	RunwayConfirmed          bool
	PdcData                  []byte
}

type TacticalStrip struct {
	ID          int64
	SessionID   int32
	Type        string
	Bay         string
	Label       string
	Aircraft    *string
	ProducedBy  string
	Sequence    int32
	TimerStart  pgtype.Timestamptz
	Confirmed   bool
	ConfirmedBy *string
	CreatedAt   pgtype.Timestamptz
}

type Version struct {
	ID        int32
	Name      string
	AppliedAt pgtype.Timestamp
}
