// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: navigation_cache.sql

package database

import (
	"context"
)

const listAMANNavigationManifestRevisions = `-- name: ListAMANNavigationManifestRevisions :many
SELECT airport, revision
FROM aman_nav_manifests
WHERE airport = $1
ORDER BY revision DESC
`

type ListAMANNavigationManifestRevisionsRow struct {
	Airport  string
	Revision int64
}

func (q *Queries) ListAMANNavigationManifestRevisions(ctx context.Context, airport string) ([]ListAMANNavigationManifestRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listAMANNavigationManifestRevisions, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAMANNavigationManifestRevisionsRow
	for rows.Next() {
		var i ListAMANNavigationManifestRevisionsRow
		if err := rows.Scan(&i.Airport, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
