// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pdc_clearances.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNextMessageSequence = `-- name: GetNextMessageSequence :one
UPDATE sessions SET pdc_message_sequence = pdc_message_sequence + 1 WHERE id = $1 RETURNING pdc_message_sequence
`

func (q *Queries) GetNextMessageSequence(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextMessageSequence, id)
	var pdc_message_sequence int32
	err := row.Scan(&pdc_message_sequence)
	return pdc_message_sequence, err
}

const getNextPdcSequence = `-- name: GetNextPdcSequence :one
UPDATE sessions SET pdc_sequence = pdc_sequence + 1 WHERE id = $1 RETURNING pdc_sequence
`

func (q *Queries) GetNextPdcSequence(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextPdcSequence, id)
	var pdc_sequence int32
	err := row.Scan(&pdc_sequence)
	return pdc_sequence, err
}

const setPdcMessageSent = `-- name: SetPdcMessageSent :exec
UPDATE strips SET pdc_state = $3, pdc_message_sequence = $4, pdc_message_sent = $5 WHERE callsign = $1 AND session = $2
`

type SetPdcMessageSentParams struct {
	Callsign           string
	Session            int32
	PdcState           string
	PdcMessageSequence *int32
	PdcMessageSent     pgtype.Timestamp
}

func (q *Queries) SetPdcMessageSent(ctx context.Context, arg SetPdcMessageSentParams) error {
	_, err := q.db.Exec(ctx, setPdcMessageSent,
		arg.Callsign,
		arg.Session,
		arg.PdcState,
		arg.PdcMessageSequence,
		arg.PdcMessageSent,
	)
	return err
}

const setPdcRequested = `-- name: SetPdcRequested :exec
UPDATE strips SET pdc_state = $3, pdc_requested_at = $4 WHERE callsign = $1 AND session = $2
`

type SetPdcRequestedParams struct {
	Callsign       string
	Session        int32
	PdcState       string
	PdcRequestedAt pgtype.Timestamp
}

func (q *Queries) SetPdcRequested(ctx context.Context, arg SetPdcRequestedParams) error {
	_, err := q.db.Exec(ctx, setPdcRequested,
		arg.Callsign,
		arg.Session,
		arg.PdcState,
		arg.PdcRequestedAt,
	)
	return err
}

const updatePdcStatus = `-- name: UpdatePdcStatus :exec
UPDATE strips SET pdc_state = $3 WHERE callsign = $1 AND session = $2
`

type UpdatePdcStatusParams struct {
	Callsign string
	Session  int32
	PdcState string
}

func (q *Queries) UpdatePdcStatus(ctx context.Context, arg UpdatePdcStatusParams) error {
	_, err := q.db.Exec(ctx, updatePdcStatus, arg.Callsign, arg.Session, arg.PdcState)
	return err
}
