// Code generated by sqlc. DO NOT EDIT.
// source: pdc_web_requests.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPdcWebRequest = `-- name: InsertPdcWebRequest :one
INSERT INTO pdc_web_requests (
    session_id, callsign, vatsim_cid, atis, stand, remarks, status, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, session_id, callsign, vatsim_cid, atis, stand, remarks, status, clearance_text, error_message, created_at, expires_at, pilot_acknowledged_at
`

type InsertPdcWebRequestParams struct {
	SessionID int32
	Callsign  string
	VatsimCid string
	Atis      string
	Stand     *string
	Remarks   *string
	Status    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertPdcWebRequest(ctx context.Context, arg InsertPdcWebRequestParams) (PdcWebRequest, error) {
	row := q.db.QueryRow(ctx, insertPdcWebRequest,
		arg.SessionID,
		arg.Callsign,
		arg.VatsimCid,
		arg.Atis,
		arg.Stand,
		arg.Remarks,
		arg.Status,
		arg.ExpiresAt,
	)
	var i PdcWebRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Callsign,
		&i.VatsimCid,
		&i.Atis,
		&i.Stand,
		&i.Remarks,
		&i.Status,
		&i.ClearanceText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PilotAcknowledgedAt,
	)
	return i, err
}

const getPdcWebRequestByID = `-- name: GetPdcWebRequestByID :one
SELECT id, session_id, callsign, vatsim_cid, atis, stand, remarks, status, clearance_text, error_message, created_at, expires_at, pilot_acknowledged_at
FROM pdc_web_requests WHERE id = $1
`

func (q *Queries) GetPdcWebRequestByID(ctx context.Context, id int64) (PdcWebRequest, error) {
	row := q.db.QueryRow(ctx, getPdcWebRequestByID, id)
	var i PdcWebRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Callsign,
		&i.VatsimCid,
		&i.Atis,
		&i.Stand,
		&i.Remarks,
		&i.Status,
		&i.ClearanceText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PilotAcknowledgedAt,
	)
	return i, err
}

const getPendingPdcWebRequestBySessionCallsign = `-- name: GetPendingPdcWebRequestBySessionCallsign :one
SELECT id, session_id, callsign, vatsim_cid, atis, stand, remarks, status, clearance_text, error_message, created_at, expires_at, pilot_acknowledged_at
FROM pdc_web_requests
WHERE session_id = $1 AND callsign = $2 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingPdcWebRequestBySessionCallsignParams struct {
	SessionID int32
	Callsign  string
}

func (q *Queries) GetPendingPdcWebRequestBySessionCallsign(ctx context.Context, arg GetPendingPdcWebRequestBySessionCallsignParams) (PdcWebRequest, error) {
	row := q.db.QueryRow(ctx, getPendingPdcWebRequestBySessionCallsign, arg.SessionID, arg.Callsign)
	var i PdcWebRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Callsign,
		&i.VatsimCid,
		&i.Atis,
		&i.Stand,
		&i.Remarks,
		&i.Status,
		&i.ClearanceText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PilotAcknowledgedAt,
	)
	return i, err
}

const getAwaitingWebPdcBySessionCallsign = `-- name: GetAwaitingWebPdcBySessionCallsign :one
SELECT id, session_id, callsign, vatsim_cid, atis, stand, remarks, status, clearance_text, error_message, created_at, expires_at, pilot_acknowledged_at
FROM pdc_web_requests
WHERE session_id = $1 AND lower(callsign) = lower($2) AND status IN ('pending', 'faults')
ORDER BY created_at DESC
LIMIT 1
`

type GetAwaitingWebPdcBySessionCallsignParams struct {
	SessionID int32
	Callsign  string
}

func (q *Queries) GetAwaitingWebPdcBySessionCallsign(ctx context.Context, arg GetAwaitingWebPdcBySessionCallsignParams) (PdcWebRequest, error) {
	row := q.db.QueryRow(ctx, getAwaitingWebPdcBySessionCallsign, arg.SessionID, arg.Callsign)
	var i PdcWebRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Callsign,
		&i.VatsimCid,
		&i.Atis,
		&i.Stand,
		&i.Remarks,
		&i.Status,
		&i.ClearanceText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PilotAcknowledgedAt,
	)
	return i, err
}

const updatePdcWebRequestStatus = `-- name: UpdatePdcWebRequestStatus :exec
UPDATE pdc_web_requests SET status = $2, error_message = $3 WHERE id = $1
`

type UpdatePdcWebRequestStatusParams struct {
	ID           int64
	Status       string
	ErrorMessage *string
}

func (q *Queries) UpdatePdcWebRequestStatus(ctx context.Context, arg UpdatePdcWebRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updatePdcWebRequestStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const updatePdcWebRequestClearance = `-- name: UpdatePdcWebRequestClearance :exec
UPDATE pdc_web_requests SET status = $2, clearance_text = $3 WHERE id = $1
`

type UpdatePdcWebRequestClearanceParams struct {
	ID            int64
	Status        string
	ClearanceText *string
}

func (q *Queries) UpdatePdcWebRequestClearance(ctx context.Context, arg UpdatePdcWebRequestClearanceParams) error {
	_, err := q.db.Exec(ctx, updatePdcWebRequestClearance, arg.ID, arg.Status, arg.ClearanceText)
	return err
}

const updatePdcWebRequestPilotAck = `-- name: UpdatePdcWebRequestPilotAck :exec
UPDATE pdc_web_requests SET pilot_acknowledged_at = $2 WHERE id = $1 AND vatsim_cid = $3 AND status = 'cleared'
`

type UpdatePdcWebRequestPilotAckParams struct {
	ID                  int64
	PilotAcknowledgedAt pgtype.Timestamptz
	VatsimCid           string
}

func (q *Queries) UpdatePdcWebRequestPilotAck(ctx context.Context, arg UpdatePdcWebRequestPilotAckParams) error {
	_, err := q.db.Exec(ctx, updatePdcWebRequestPilotAck, arg.ID, arg.PilotAcknowledgedAt, arg.VatsimCid)
	return err
}
