// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pdc_clearances.sql

package database

import (
	"context"
)

const getNextMessageSequence = `-- name: GetNextMessageSequence :one
UPDATE sessions SET pdc_message_sequence = pdc_message_sequence + 1 WHERE id = $1 RETURNING pdc_message_sequence
`

func (q *Queries) GetNextMessageSequence(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextMessageSequence, id)
	var pdc_message_sequence int32
	err := row.Scan(&pdc_message_sequence)
	return pdc_message_sequence, err
}

const getNextPdcSequence = `-- name: GetNextPdcSequence :one
UPDATE sessions SET pdc_sequence = pdc_sequence + 1 WHERE id = $1 RETURNING pdc_sequence
`

func (q *Queries) GetNextPdcSequence(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getNextPdcSequence, id)
	var pdc_sequence int32
	err := row.Scan(&pdc_sequence)
	return pdc_sequence, err
}
