// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sector_owners.sql

package database

import (
	"context"
)

const getSectorOwners = `-- name: GetSectorOwners :many
SELECT id, session, sector, position, identifier FROM sector_owners
WHERE session = $1
`

func (q *Queries) GetSectorOwners(ctx context.Context, session int32) ([]SectorOwner, error) {
	rows, err := q.db.Query(ctx, getSectorOwners, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectorOwner
	for rows.Next() {
		var i SectorOwner
		if err := rows.Scan(
			&i.ID,
			&i.Session,
			&i.Sector,
			&i.Position,
			&i.Identifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertSectorOwnersParams struct {
	Session    int32
	Sector     []string
	Position   string
	Identifier string
}

const removeSectorOwners = `-- name: RemoveSectorOwners :exec
DELETE FROM sector_owners WHERE session = $1
`

func (q *Queries) RemoveSectorOwners(ctx context.Context, session int32) error {
	_, err := q.db.Exec(ctx, removeSectorOwners, session)
	return err
}
