// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package database

import (
	"context"

	"FlightStrips/pkg/models"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSession = `-- name: DeleteSession :execrows
DELETE
FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExpiredSessions = `-- name: GetExpiredSessions :many
SELECT id
FROM sessions
WHERE NOT EXISTS (SELECT 1 FROM controllers WHERE last_seen_euroscope > $1)
`

func (q *Queries) GetExpiredSessions(ctx context.Context, expiredTime pgtype.Timestamp) ([]int32, error) {
	rows, err := q.db.Query(ctx, getExpiredSessions, expiredTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, name, airport, active_runways, pdc_sequence, pdc_message_sequence
FROM sessions
WHERE airport = $1
  AND name = $2
`

type GetSessionParams struct {
	Airport string
	Name    string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.Airport, arg.Name)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Airport,
		&i.ActiveRunways,
		&i.PdcSequence,
		&i.PdcMessageSequence,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, name, airport, active_runways, pdc_sequence, pdc_message_sequence
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Airport,
		&i.ActiveRunways,
		&i.PdcSequence,
		&i.PdcMessageSequence,
	)
	return i, err
}

const getSessions = `-- name: GetSessions :many
SELECT id, name, airport, active_runways, pdc_sequence, pdc_message_sequence FROM sessions
`

func (q *Queries) GetSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Airport,
			&i.ActiveRunways,
			&i.PdcSequence,
			&i.PdcMessageSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByNames = `-- name: GetSessionsByNames :many
SELECT id, name, airport, active_runways, pdc_sequence, pdc_message_sequence FROM sessions WHERE name = $1
`

func (q *Queries) GetSessionsByNames(ctx context.Context, name string) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByNames, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Airport,
			&i.ActiveRunways,
			&i.PdcSequence,
			&i.PdcMessageSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (name, airport)
VALUES ($1, $2) RETURNING id
`

type InsertSessionParams struct {
	Name    string
	Airport string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertSession, arg.Name, arg.Airport)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listSessionsByAirport = `-- name: ListSessionsByAirport :many
SELECT id, name, airport, active_runways, pdc_sequence, pdc_message_sequence
FROM sessions
WHERE airport = $1
`

func (q *Queries) ListSessionsByAirport(ctx context.Context, airport string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAirport, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Airport,
			&i.ActiveRunways,
			&i.PdcSequence,
			&i.PdcMessageSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActiveRunways = `-- name: UpdateActiveRunways :exec
UPDATE sessions SET active_runways = $2 WHERE id = $1
`

type UpdateActiveRunwaysParams struct {
	ID            int32
	ActiveRunways models.ActiveRunways
}

func (q *Queries) UpdateActiveRunways(ctx context.Context, arg UpdateActiveRunwaysParams) error {
	_, err := q.db.Exec(ctx, updateActiveRunways, arg.ID, arg.ActiveRunways)
	return err
}
