// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: stand_assignments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStandAssignment = `-- name: CreateStandAssignment :one
INSERT INTO stand_assignments (
    session_id, callsign, stand, direction, stage, source, rule_id, tier,
    matched_variant, conflict_reason, eta, eta_source,
    assigned_at, expires_at, manual, acknowledged, acknowledged_at,
    acknowledged_by, vatsim_cid, vatsim_revision
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20
)
RETURNING id, session_id, callsign, stand, direction, stage, source, rule_id, tier, matched_variant, eta, eta_source, assigned_at, expires_at, manual, acknowledged, acknowledged_at, acknowledged_by, vatsim_cid, vatsim_revision, version, created_at, updated_at, conflict_reason
`

type CreateStandAssignmentParams struct {
	SessionID      int32
	Callsign       string
	Stand          string
	Direction      string
	Stage          string
	Source         string
	RuleID         *string
	Tier           *int32
	MatchedVariant *string
	ConflictReason *string
	Eta            pgtype.Timestamptz
	EtaSource      *string
	AssignedAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	Manual         bool
	Acknowledged   bool
	AcknowledgedAt pgtype.Timestamptz
	AcknowledgedBy *string
	VatsimCid      *int64
	VatsimRevision *int64
}

func (q *Queries) CreateStandAssignment(ctx context.Context, arg CreateStandAssignmentParams) (StandAssignment, error) {
	row := q.db.QueryRow(ctx, createStandAssignment,
		arg.SessionID,
		arg.Callsign,
		arg.Stand,
		arg.Direction,
		arg.Stage,
		arg.Source,
		arg.RuleID,
		arg.Tier,
		arg.MatchedVariant,
		arg.ConflictReason,
		arg.Eta,
		arg.EtaSource,
		arg.AssignedAt,
		arg.ExpiresAt,
		arg.Manual,
		arg.Acknowledged,
		arg.AcknowledgedAt,
		arg.AcknowledgedBy,
		arg.VatsimCid,
		arg.VatsimRevision,
	)
	var i StandAssignment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Callsign,
		&i.Stand,
		&i.Direction,
		&i.Stage,
		&i.Source,
		&i.RuleID,
		&i.Tier,
		&i.MatchedVariant,
		&i.Eta,
		&i.EtaSource,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.Manual,
		&i.Acknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.VatsimCid,
		&i.VatsimRevision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConflictReason,
	)
	return i, err
}

const createStandBlock = `-- name: CreateStandBlock :one
INSERT INTO stand_blocks (
    session_id, stand, block_type, source, reason, callsign, created_by,
    expires_at, manual
)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9
FROM (SELECT id FROM sessions WHERE id = $1 FOR UPDATE) AS locked_session
RETURNING id, session_id, stand, block_type, source, reason, callsign, created_by, expires_at, manual, version, created_at, updated_at
`

type CreateStandBlockParams struct {
	SessionID int32
	Stand     string
	BlockType string
	Source    string
	Reason    *string
	Callsign  *string
	CreatedBy *string
	ExpiresAt pgtype.Timestamptz
	Manual    bool
}

func (q *Queries) CreateStandBlock(ctx context.Context, arg CreateStandBlockParams) (StandBlock, error) {
	row := q.db.QueryRow(ctx, createStandBlock,
		arg.SessionID,
		arg.Stand,
		arg.BlockType,
		arg.Source,
		arg.Reason,
		arg.Callsign,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.Manual,
	)
	var i StandBlock
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Stand,
		&i.BlockType,
		&i.Source,
		&i.Reason,
		&i.Callsign,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.Manual,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStandAssignment = `-- name: DeleteStandAssignment :execrows
DELETE FROM stand_assignments
WHERE id = $1 AND session_id = $2 AND version = $3
`

type DeleteStandAssignmentParams struct {
	ID        int64
	SessionID int32
	Version   int32
}

func (q *Queries) DeleteStandAssignment(ctx context.Context, arg DeleteStandAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStandAssignment, arg.ID, arg.SessionID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStandBlock = `-- name: DeleteStandBlock :execrows
DELETE FROM stand_blocks
WHERE id = $1 AND session_id = $2 AND version = $3
`

type DeleteStandBlockParams struct {
	ID        int64
	SessionID int32
	Version   int32
}

func (q *Queries) DeleteStandBlock(ctx context.Context, arg DeleteStandBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStandBlock, arg.ID, arg.SessionID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStandAssignment = `-- name: GetStandAssignment :one
SELECT id, session_id, callsign, stand, direction, stage, source, rule_id, tier, matched_variant, eta, eta_source, assigned_at, expires_at, manual, acknowledged, acknowledged_at, acknowledged_by, vatsim_cid, vatsim_revision, version, created_at, updated_at, conflict_reason
FROM stand_assignments
WHERE session_id = $1 AND callsign = $2
`

type GetStandAssignmentParams struct {
	SessionID int32
	Callsign  string
}

func (q *Queries) GetStandAssignment(ctx context.Context, arg GetStandAssignmentParams) (StandAssignment, error) {
	row := q.db.QueryRow(ctx, getStandAssignment, arg.SessionID, arg.Callsign)
	var i StandAssignment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Callsign,
		&i.Stand,
		&i.Direction,
		&i.Stage,
		&i.Source,
		&i.RuleID,
		&i.Tier,
		&i.MatchedVariant,
		&i.Eta,
		&i.EtaSource,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.Manual,
		&i.Acknowledged,
		&i.AcknowledgedAt,
		&i.AcknowledgedBy,
		&i.VatsimCid,
		&i.VatsimRevision,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConflictReason,
	)
	return i, err
}

const getStandBlock = `-- name: GetStandBlock :one
SELECT id, session_id, stand, block_type, source, reason, callsign, created_by, expires_at, manual, version, created_at, updated_at
FROM stand_blocks
WHERE id = $1 AND session_id = $2
`

type GetStandBlockParams struct {
	ID        int64
	SessionID int32
}

func (q *Queries) GetStandBlock(ctx context.Context, arg GetStandBlockParams) (StandBlock, error) {
	row := q.db.QueryRow(ctx, getStandBlock, arg.ID, arg.SessionID)
	var i StandBlock
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Stand,
		&i.BlockType,
		&i.Source,
		&i.Reason,
		&i.Callsign,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.Manual,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStandAssignments = `-- name: ListStandAssignments :many
SELECT id, session_id, callsign, stand, direction, stage, source, rule_id, tier, matched_variant, eta, eta_source, assigned_at, expires_at, manual, acknowledged, acknowledged_at, acknowledged_by, vatsim_cid, vatsim_revision, version, created_at, updated_at, conflict_reason
FROM stand_assignments
WHERE session_id = $1
ORDER BY callsign
`

func (q *Queries) ListStandAssignments(ctx context.Context, sessionID int32) ([]StandAssignment, error) {
	rows, err := q.db.Query(ctx, listStandAssignments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandAssignment
	for rows.Next() {
		var i StandAssignment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Callsign,
			&i.Stand,
			&i.Direction,
			&i.Stage,
			&i.Source,
			&i.RuleID,
			&i.Tier,
			&i.MatchedVariant,
			&i.Eta,
			&i.EtaSource,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.Manual,
			&i.Acknowledged,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.VatsimCid,
			&i.VatsimRevision,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConflictReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandBlocks = `-- name: ListStandBlocks :many
SELECT id, session_id, stand, block_type, source, reason, callsign, created_by, expires_at, manual, version, created_at, updated_at
FROM stand_blocks
WHERE session_id = $1
ORDER BY stand, id
`

func (q *Queries) ListStandBlocks(ctx context.Context, sessionID int32) ([]StandBlock, error) {
	rows, err := q.db.Query(ctx, listStandBlocks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandBlock
	for rows.Next() {
		var i StandBlock
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Stand,
			&i.BlockType,
			&i.Source,
			&i.Reason,
			&i.Callsign,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.Manual,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStandBlocksByStand = `-- name: ListStandBlocksByStand :many
SELECT id, session_id, stand, block_type, source, reason, callsign, created_by, expires_at, manual, version, created_at, updated_at
FROM stand_blocks
WHERE session_id = $1 AND stand = $2
ORDER BY id
`

type ListStandBlocksByStandParams struct {
	SessionID int32
	Stand     string
}

func (q *Queries) ListStandBlocksByStand(ctx context.Context, arg ListStandBlocksByStandParams) ([]StandBlock, error) {
	rows, err := q.db.Query(ctx, listStandBlocksByStand, arg.SessionID, arg.Stand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandBlock
	for rows.Next() {
		var i StandBlock
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Stand,
			&i.BlockType,
			&i.Source,
			&i.Reason,
			&i.Callsign,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.Manual,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveManualStandBlocks = `-- name: LockActiveManualStandBlocks :many
SELECT id, session_id, stand, block_type, source, reason, callsign, created_by, expires_at, manual, version, created_at, updated_at
FROM stand_blocks
WHERE session_id = $1
  AND manual = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY stand, id
FOR UPDATE
`

func (q *Queries) LockActiveManualStandBlocks(ctx context.Context, sessionID int32) ([]StandBlock, error) {
	rows, err := q.db.Query(ctx, lockActiveManualStandBlocks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandBlock
	for rows.Next() {
		var i StandBlock
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Stand,
			&i.BlockType,
			&i.Source,
			&i.Reason,
			&i.Callsign,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.Manual,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStandAssignments = `-- name: LockStandAssignments :many
SELECT id, session_id, callsign, stand, direction, stage, source, rule_id, tier, matched_variant, eta, eta_source, assigned_at, expires_at, manual, acknowledged, acknowledged_at, acknowledged_by, vatsim_cid, vatsim_revision, version, created_at, updated_at, conflict_reason
FROM stand_assignments
WHERE session_id = $1
  AND (callsign = $2 OR expires_at IS NULL OR expires_at > NOW())
ORDER BY callsign
FOR UPDATE
`

type LockStandAssignmentsParams struct {
	SessionID int32
	Callsign  string
}

func (q *Queries) LockStandAssignments(ctx context.Context, arg LockStandAssignmentsParams) ([]StandAssignment, error) {
	rows, err := q.db.Query(ctx, lockStandAssignments, arg.SessionID, arg.Callsign)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandAssignment
	for rows.Next() {
		var i StandAssignment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Callsign,
			&i.Stand,
			&i.Direction,
			&i.Stage,
			&i.Source,
			&i.RuleID,
			&i.Tier,
			&i.MatchedVariant,
			&i.Eta,
			&i.EtaSource,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.Manual,
			&i.Acknowledged,
			&i.AcknowledgedAt,
			&i.AcknowledgedBy,
			&i.VatsimCid,
			&i.VatsimRevision,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConflictReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStandAssignment = `-- name: UpdateStandAssignment :execrows
UPDATE stand_assignments
SET stand = $3,
    direction = $4,
    stage = $5,
    source = $6,
    rule_id = $7,
    tier = $8,
    matched_variant = $9,
    conflict_reason = $10,
    eta = $11,
    eta_source = $12,
    assigned_at = $13,
    expires_at = $14,
    manual = $15,
    acknowledged = $16,
    acknowledged_at = $17,
    acknowledged_by = $18,
    vatsim_cid = $19,
    vatsim_revision = $20,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND session_id = $2 AND version = $21
`

type UpdateStandAssignmentParams struct {
	ID             int64
	SessionID      int32
	Stand          string
	Direction      string
	Stage          string
	Source         string
	RuleID         *string
	Tier           *int32
	MatchedVariant *string
	ConflictReason *string
	Eta            pgtype.Timestamptz
	EtaSource      *string
	AssignedAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	Manual         bool
	Acknowledged   bool
	AcknowledgedAt pgtype.Timestamptz
	AcknowledgedBy *string
	VatsimCid      *int64
	VatsimRevision *int64
	Version        int32
}

func (q *Queries) UpdateStandAssignment(ctx context.Context, arg UpdateStandAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStandAssignment,
		arg.ID,
		arg.SessionID,
		arg.Stand,
		arg.Direction,
		arg.Stage,
		arg.Source,
		arg.RuleID,
		arg.Tier,
		arg.MatchedVariant,
		arg.ConflictReason,
		arg.Eta,
		arg.EtaSource,
		arg.AssignedAt,
		arg.ExpiresAt,
		arg.Manual,
		arg.Acknowledged,
		arg.AcknowledgedAt,
		arg.AcknowledgedBy,
		arg.VatsimCid,
		arg.VatsimRevision,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStandBlock = `-- name: UpdateStandBlock :execrows
UPDATE stand_blocks
SET stand = $3,
    block_type = $4,
    source = $5,
    reason = $6,
    callsign = $7,
    created_by = $8,
    expires_at = $9,
    manual = $10,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND session_id = $2 AND version = $11
`

type UpdateStandBlockParams struct {
	ID        int64
	SessionID int32
	Stand     string
	BlockType string
	Source    string
	Reason    *string
	Callsign  *string
	CreatedBy *string
	ExpiresAt pgtype.Timestamptz
	Manual    bool
	Version   int32
}

func (q *Queries) UpdateStandBlock(ctx context.Context, arg UpdateStandBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStandBlock,
		arg.ID,
		arg.SessionID,
		arg.Stand,
		arg.BlockType,
		arg.Source,
		arg.Reason,
		arg.Callsign,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.Manual,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
