// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: strips.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMaxSequenceInBay = `-- name: GetMaxSequenceInBay :one
SELECT COALESCE(max(sequence), 0)::INTEGER AS max_sequence
FROM strips
WHERE session = $1 AND bay = $2::TEXT
`

type GetMaxSequenceInBayParams struct {
	Session int32
	Bay     string
}

func (q *Queries) GetMaxSequenceInBay(ctx context.Context, arg GetMaxSequenceInBayParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceInBay, arg.Session, arg.Bay)
	var max_sequence int32
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const getSequence = `-- name: GetSequence :one
SELECT sequence
FROM strips
WHERE session = $1 AND callsign = $2
LIMIT 1
`

type GetSequenceParams struct {
	Session  int32
	Callsign string
}

func (q *Queries) GetSequence(ctx context.Context, arg GetSequenceParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getSequence, arg.Session, arg.Callsign)
	var sequence pgtype.Int4
	err := row.Scan(&sequence)
	return sequence, err
}

const getStrip = `-- name: GetStrip :one
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat, eobt, next_owners, previous_owners
FROM strips
WHERE callsign = $1 AND session = $2
`

type GetStripParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) GetStrip(ctx context.Context, arg GetStripParams) (Strip, error) {
	row := q.db.QueryRow(ctx, getStrip, arg.Callsign, arg.Session)
	var i Strip
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Callsign,
		&i.Session,
		&i.Origin,
		&i.Destination,
		&i.Alternative,
		&i.Route,
		&i.Remarks,
		&i.AssignedSquawk,
		&i.Squawk,
		&i.Sid,
		&i.ClearedAltitude,
		&i.Heading,
		&i.AircraftType,
		&i.Runway,
		&i.RequestedAltitude,
		&i.Capabilities,
		&i.CommunicationType,
		&i.AircraftCategory,
		&i.Stand,
		&i.Sequence,
		&i.State,
		&i.Cleared,
		&i.Owner,
		&i.Bay,
		&i.PositionLatitude,
		&i.PositionLongitude,
		&i.PositionAltitude,
		&i.Tobt,
		&i.Tsat,
		&i.Ttot,
		&i.Ctot,
		&i.Aobt,
		&i.Asat,
		&i.Eobt,
		&i.NextOwners,
		&i.PreviousOwners,
	)
	return i, err
}

const insertStrip = `-- name: InsertStrip :exec
INSERT INTO strips (version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk,
                    squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities,
                    communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay,
                    position_latitude, position_longitude, position_altitude, tobt, eobt)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23,
        $24, $25, $26, $27, $28, $29)
`

type InsertStripParams struct {
	Callsign          string
	Session           int32
	Origin            string
	Destination       string
	Alternative       pgtype.Text
	Route             pgtype.Text
	Remarks           pgtype.Text
	AssignedSquawk    pgtype.Text
	Squawk            pgtype.Text
	Sid               pgtype.Text
	ClearedAltitude   pgtype.Int4
	Heading           pgtype.Int4
	AircraftType      pgtype.Text
	Runway            pgtype.Text
	RequestedAltitude pgtype.Int4
	Capabilities      pgtype.Text
	CommunicationType pgtype.Text
	AircraftCategory  pgtype.Text
	Stand             pgtype.Text
	Sequence          pgtype.Int4
	State             pgtype.Text
	Cleared           pgtype.Bool
	Owner             pgtype.Text
	Bay               pgtype.Text
	PositionLatitude  pgtype.Float8
	PositionLongitude pgtype.Float8
	PositionAltitude  pgtype.Int4
	Tobt              pgtype.Text
	Eobt              pgtype.Text
}

func (q *Queries) InsertStrip(ctx context.Context, arg InsertStripParams) error {
	_, err := q.db.Exec(ctx, insertStrip,
		arg.Callsign,
		arg.Session,
		arg.Origin,
		arg.Destination,
		arg.Alternative,
		arg.Route,
		arg.Remarks,
		arg.AssignedSquawk,
		arg.Squawk,
		arg.Sid,
		arg.ClearedAltitude,
		arg.Heading,
		arg.AircraftType,
		arg.Runway,
		arg.RequestedAltitude,
		arg.Capabilities,
		arg.CommunicationType,
		arg.AircraftCategory,
		arg.Stand,
		arg.Sequence,
		arg.State,
		arg.Cleared,
		arg.Owner,
		arg.Bay,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Tobt,
		arg.Eobt,
	)
	return err
}

const listStripSequences = `-- name: ListStripSequences :many
SELECT callsign, sequence
FROM strips
WHERE session = $1
ORDER BY sequence, callsign
`

type ListStripSequencesRow struct {
	Callsign string
	Sequence pgtype.Int4
}

func (q *Queries) ListStripSequences(ctx context.Context, session int32) ([]ListStripSequencesRow, error) {
	rows, err := q.db.Query(ctx, listStripSequences, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStripSequencesRow
	for rows.Next() {
		var i ListStripSequencesRow
		if err := rows.Scan(&i.Callsign, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrips = `-- name: ListStrips :many
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat, eobt, next_owners, previous_owners
FROM strips
WHERE session = $1
ORDER BY callsign
`

func (q *Queries) ListStrips(ctx context.Context, session int32) ([]Strip, error) {
	rows, err := q.db.Query(ctx, listStrips, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strip
	for rows.Next() {
		var i Strip
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Callsign,
			&i.Session,
			&i.Origin,
			&i.Destination,
			&i.Alternative,
			&i.Route,
			&i.Remarks,
			&i.AssignedSquawk,
			&i.Squawk,
			&i.Sid,
			&i.ClearedAltitude,
			&i.Heading,
			&i.AircraftType,
			&i.Runway,
			&i.RequestedAltitude,
			&i.Capabilities,
			&i.CommunicationType,
			&i.AircraftCategory,
			&i.Stand,
			&i.Sequence,
			&i.State,
			&i.Cleared,
			&i.Owner,
			&i.Bay,
			&i.PositionLatitude,
			&i.PositionLongitude,
			&i.PositionAltitude,
			&i.Tobt,
			&i.Tsat,
			&i.Ttot,
			&i.Ctot,
			&i.Aobt,
			&i.Asat,
			&i.Eobt,
			&i.NextOwners,
			&i.PreviousOwners,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStripsByOrigin = `-- name: ListStripsByOrigin :many
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat, eobt, next_owners, previous_owners
FROM strips
WHERE origin = $1 AND session = $2
ORDER BY callsign
`

type ListStripsByOriginParams struct {
	Origin  string
	Session int32
}

func (q *Queries) ListStripsByOrigin(ctx context.Context, arg ListStripsByOriginParams) ([]Strip, error) {
	rows, err := q.db.Query(ctx, listStripsByOrigin, arg.Origin, arg.Session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strip
	for rows.Next() {
		var i Strip
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Callsign,
			&i.Session,
			&i.Origin,
			&i.Destination,
			&i.Alternative,
			&i.Route,
			&i.Remarks,
			&i.AssignedSquawk,
			&i.Squawk,
			&i.Sid,
			&i.ClearedAltitude,
			&i.Heading,
			&i.AircraftType,
			&i.Runway,
			&i.RequestedAltitude,
			&i.Capabilities,
			&i.CommunicationType,
			&i.AircraftCategory,
			&i.Stand,
			&i.Sequence,
			&i.State,
			&i.Cleared,
			&i.Owner,
			&i.Bay,
			&i.PositionLatitude,
			&i.PositionLongitude,
			&i.PositionAltitude,
			&i.Tobt,
			&i.Tsat,
			&i.Ttot,
			&i.Ctot,
			&i.Aobt,
			&i.Asat,
			&i.Eobt,
			&i.NextOwners,
			&i.PreviousOwners,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateStripSequences = `-- name: RecalculateStripSequences :exec
WITH row_numbers AS (
    SELECT s.id, ((ROW_NUMBER() OVER (ORDER BY s.sequence, s.callsign)) - 1) * $2::INT AS new_sequence
    FROM strips as s
    WHERE s.session = $1
)
UPDATE strips
SET sequence = row_numbers.new_sequence,
    version  = strips.version + 1
FROM row_numbers
WHERE strips.id = row_numbers.id AND strips.session = $1
`

type RecalculateStripSequencesParams struct {
	Session int32
	Spacing int32
}

func (q *Queries) RecalculateStripSequences(ctx context.Context, arg RecalculateStripSequencesParams) error {
	_, err := q.db.Exec(ctx, recalculateStripSequences, arg.Session, arg.Spacing)
	return err
}

const removeStripByID = `-- name: RemoveStripByID :exec
DELETE
FROM strips
WHERE callsign = $1 AND session = $2
`

type RemoveStripByIDParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) RemoveStripByID(ctx context.Context, arg RemoveStripByIDParams) error {
	_, err := q.db.Exec(ctx, removeStripByID, arg.Callsign, arg.Session)
	return err
}

const setNextAndPreviousOwners = `-- name: SetNextAndPreviousOwners :exec
UPDATE strips SET next_owners = $3, previous_owners = $4 WHERE session = $1 AND callsign = $2
`

type SetNextAndPreviousOwnersParams struct {
	Session        int32
	Callsign       string
	NextOwners     []string
	PreviousOwners []string
}

func (q *Queries) SetNextAndPreviousOwners(ctx context.Context, arg SetNextAndPreviousOwnersParams) error {
	_, err := q.db.Exec(ctx, setNextAndPreviousOwners,
		arg.Session,
		arg.Callsign,
		arg.NextOwners,
		arg.PreviousOwners,
	)
	return err
}

const setNextOwners = `-- name: SetNextOwners :exec
UPDATE strips SET next_owners = $3 WHERE session = $1 AND callsign = $2
`

type SetNextOwnersParams struct {
	Session    int32
	Callsign   string
	NextOwners []string
}

func (q *Queries) SetNextOwners(ctx context.Context, arg SetNextOwnersParams) error {
	_, err := q.db.Exec(ctx, setNextOwners, arg.Session, arg.Callsign, arg.NextOwners)
	return err
}

const setPreviousOwners = `-- name: SetPreviousOwners :exec
UPDATE strips SET previous_owners = $3 WHERE session = $1 AND callsign = $2
`

type SetPreviousOwnersParams struct {
	Session        int32
	Callsign       string
	PreviousOwners []string
}

func (q *Queries) SetPreviousOwners(ctx context.Context, arg SetPreviousOwnersParams) error {
	_, err := q.db.Exec(ctx, setPreviousOwners, arg.Session, arg.Callsign, arg.PreviousOwners)
	return err
}

const setStripOwner = `-- name: SetStripOwner :execrows
UPDATE strips
SET owner   = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND version = $4
`

type SetStripOwnerParams struct {
	Owner    pgtype.Text
	Callsign string
	Session  int32
	Version  int32
}

func (q *Queries) SetStripOwner(ctx context.Context, arg SetStripOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStripOwner,
		arg.Owner,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStrip = `-- name: UpdateStrip :execrows
UPDATE strips
SET (version, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, eobt
        ) = (
             version + 1, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22,
             $23, $24, $25, $26, $27, $28, $29)
WHERE callsign = $1 AND session = $2
`

type UpdateStripParams struct {
	Callsign          string
	Session           int32
	Origin            string
	Destination       string
	Alternative       pgtype.Text
	Route             pgtype.Text
	Remarks           pgtype.Text
	AssignedSquawk    pgtype.Text
	Squawk            pgtype.Text
	Sid               pgtype.Text
	ClearedAltitude   pgtype.Int4
	Heading           pgtype.Int4
	AircraftType      pgtype.Text
	Runway            pgtype.Text
	RequestedAltitude pgtype.Int4
	Capabilities      pgtype.Text
	CommunicationType pgtype.Text
	AircraftCategory  pgtype.Text
	Stand             pgtype.Text
	Sequence          pgtype.Int4
	State             pgtype.Text
	Cleared           pgtype.Bool
	Owner             pgtype.Text
	Bay               pgtype.Text
	PositionLatitude  pgtype.Float8
	PositionLongitude pgtype.Float8
	PositionAltitude  pgtype.Int4
	Tobt              pgtype.Text
	Eobt              pgtype.Text
}

func (q *Queries) UpdateStrip(ctx context.Context, arg UpdateStripParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStrip,
		arg.Callsign,
		arg.Session,
		arg.Origin,
		arg.Destination,
		arg.Alternative,
		arg.Route,
		arg.Remarks,
		arg.AssignedSquawk,
		arg.Squawk,
		arg.Sid,
		arg.ClearedAltitude,
		arg.Heading,
		arg.AircraftType,
		arg.Runway,
		arg.RequestedAltitude,
		arg.Capabilities,
		arg.CommunicationType,
		arg.AircraftCategory,
		arg.Stand,
		arg.Sequence,
		arg.State,
		arg.Cleared,
		arg.Owner,
		arg.Bay,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Tobt,
		arg.Eobt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripAircraftPositionByID = `-- name: UpdateStripAircraftPositionByID :execrows
UPDATE strips
SET position_latitude  = $1,
    position_longitude = $2,
    position_altitude  = $3,
    bay                = $4
WHERE callsign = $5 AND session = $6 AND (version = $7 OR $7 IS NULL)
`

type UpdateStripAircraftPositionByIDParams struct {
	PositionLatitude  pgtype.Float8
	PositionLongitude pgtype.Float8
	PositionAltitude  pgtype.Int4
	Bay               pgtype.Text
	Callsign          string
	Session           int32
	Version           pgtype.Int4
}

func (q *Queries) UpdateStripAircraftPositionByID(ctx context.Context, arg UpdateStripAircraftPositionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripAircraftPositionByID,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripAssignedSquawkByID = `-- name: UpdateStripAssignedSquawkByID :execrows
UPDATE strips
SET assigned_squawk = $1,
    version         = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripAssignedSquawkByIDParams struct {
	AssignedSquawk pgtype.Text
	Callsign       string
	Session        int32
	Version        pgtype.Int4
}

func (q *Queries) UpdateStripAssignedSquawkByID(ctx context.Context, arg UpdateStripAssignedSquawkByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripAssignedSquawkByID,
		arg.AssignedSquawk,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripClearedAltitudeByID = `-- name: UpdateStripClearedAltitudeByID :execrows
UPDATE strips
SET cleared_altitude = $1,
    version          = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripClearedAltitudeByIDParams struct {
	ClearedAltitude pgtype.Int4
	Callsign        string
	Session         int32
	Version         pgtype.Int4
}

func (q *Queries) UpdateStripClearedAltitudeByID(ctx context.Context, arg UpdateStripClearedAltitudeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripClearedAltitudeByID,
		arg.ClearedAltitude,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripClearedFlagByID = `-- name: UpdateStripClearedFlagByID :execrows
UPDATE strips
SET cleared = $1,
    bay     = $2,
    version = version + 1
WHERE callsign = $3 AND session = $4 AND (version = $5 OR $5 IS NULL)
`

type UpdateStripClearedFlagByIDParams struct {
	Cleared  pgtype.Bool
	Bay      pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripClearedFlagByID(ctx context.Context, arg UpdateStripClearedFlagByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripClearedFlagByID,
		arg.Cleared,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripCommunicationTypeByID = `-- name: UpdateStripCommunicationTypeByID :execrows
UPDATE strips
SET communication_type = $1,
    version            = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripCommunicationTypeByIDParams struct {
	CommunicationType pgtype.Text
	Callsign          string
	Session           int32
	Version           pgtype.Int4
}

func (q *Queries) UpdateStripCommunicationTypeByID(ctx context.Context, arg UpdateStripCommunicationTypeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripCommunicationTypeByID,
		arg.CommunicationType,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripGroundStateByID = `-- name: UpdateStripGroundStateByID :execrows
UPDATE strips
SET state   = $1,
    bay     = $2,
    version = version + 1
WHERE callsign = $3 AND session = $4 AND (version = $5 OR $5 IS NULL)
`

type UpdateStripGroundStateByIDParams struct {
	State    pgtype.Text
	Bay      pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripGroundStateByID(ctx context.Context, arg UpdateStripGroundStateByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripGroundStateByID,
		arg.State,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripHeadingByID = `-- name: UpdateStripHeadingByID :execrows
UPDATE strips
SET heading = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripHeadingByIDParams struct {
	Heading  pgtype.Int4
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripHeadingByID(ctx context.Context, arg UpdateStripHeadingByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripHeadingByID,
		arg.Heading,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripRequestedAltitudeByID = `-- name: UpdateStripRequestedAltitudeByID :execrows
UPDATE strips
SET requested_altitude = $1,
    version            = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripRequestedAltitudeByIDParams struct {
	RequestedAltitude pgtype.Int4
	Callsign          string
	Session           int32
	Version           pgtype.Int4
}

func (q *Queries) UpdateStripRequestedAltitudeByID(ctx context.Context, arg UpdateStripRequestedAltitudeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripRequestedAltitudeByID,
		arg.RequestedAltitude,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripSequence = `-- name: UpdateStripSequence :execrows
UPDATE strips
SET sequence = $3::INT,
    version  = version + 1
WHERE session = $1 AND callsign = $2
`

type UpdateStripSequenceParams struct {
	Session  int32
	Callsign string
	Sequence int32
}

func (q *Queries) UpdateStripSequence(ctx context.Context, arg UpdateStripSequenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripSequence, arg.Session, arg.Callsign, arg.Sequence)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripSequenceBulk = `-- name: UpdateStripSequenceBulk :exec
UPDATE strips AS s
SET sequence = u.new_sequence,
    version  = s.version + 1
FROM (SELECT unnest($2::TEXT[]) AS callsign, unnest($3::INT[]) AS new_sequence) AS u
WHERE s.session = $1 AND s.callsign = u.callsign
`

type UpdateStripSequenceBulkParams struct {
	Session   int32
	Callsigns []string
	Sequences []int32
}

func (q *Queries) UpdateStripSequenceBulk(ctx context.Context, arg UpdateStripSequenceBulkParams) error {
	_, err := q.db.Exec(ctx, updateStripSequenceBulk, arg.Session, arg.Callsigns, arg.Sequences)
	return err
}

const updateStripSquawkByID = `-- name: UpdateStripSquawkByID :execrows
UPDATE strips
SET squawk  = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripSquawkByIDParams struct {
	Squawk   pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripSquawkByID(ctx context.Context, arg UpdateStripSquawkByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripSquawkByID,
		arg.Squawk,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripStandByID = `-- name: UpdateStripStandByID :execrows
UPDATE strips
SET stand   = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripStandByIDParams struct {
	Stand    pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripStandByID(ctx context.Context, arg UpdateStripStandByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripStandByID,
		arg.Stand,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
