// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: strips.sql

package database

import (
	"context"
)

const appendControllerModifiedField = `-- name: AppendControllerModifiedField :exec
UPDATE strips
SET controller_modified_fields = array_append(controller_modified_fields, $3)
WHERE session = $1 AND callsign = $2 AND NOT ($3 = ANY(controller_modified_fields))
`

type AppendControllerModifiedFieldParams struct {
	Session     int32
	Callsign    string
	ArrayAppend interface{}
}

func (q *Queries) AppendControllerModifiedField(ctx context.Context, arg AppendControllerModifiedFieldParams) error {
	_, err := q.db.Exec(ctx, appendControllerModifiedField, arg.Session, arg.Callsign, arg.ArrayAppend)
	return err
}

const appendUnexpectedChangeField = `-- name: AppendUnexpectedChangeField :exec
UPDATE strips
SET unexpected_change_fields = array_append(unexpected_change_fields, $3)
WHERE session = $1 AND callsign = $2 AND NOT ($3 = ANY(unexpected_change_fields))
`

type AppendUnexpectedChangeFieldParams struct {
	Session     int32
	Callsign    string
	ArrayAppend interface{}
}

func (q *Queries) AppendUnexpectedChangeField(ctx context.Context, arg AppendUnexpectedChangeFieldParams) error {
	_, err := q.db.Exec(ctx, appendUnexpectedChangeField, arg.Session, arg.Callsign, arg.ArrayAppend)
	return err
}

const getBay = `-- name: GetBay :one
SELECT bay
FROM strips
WHERE session = $1 AND callsign = $2
`

type GetBayParams struct {
	Session  int32
	Callsign string
}

func (q *Queries) GetBay(ctx context.Context, arg GetBayParams) (string, error) {
	row := q.db.QueryRow(ctx, getBay, arg.Session, arg.Callsign)
	var bay string
	err := row.Scan(&bay)
	return bay, err
}

const getCdmData = `-- name: GetCdmData :many
SELECT callsign, cdm_data FROM strips WHERE session = $1
`

type GetCdmDataRow struct {
	Callsign string
	CdmData  []byte
}

func (q *Queries) GetCdmData(ctx context.Context, session int32) ([]GetCdmDataRow, error) {
	rows, err := q.db.Query(ctx, getCdmData, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCdmDataRow
	for rows.Next() {
		var i GetCdmDataRow
		if err := rows.Scan(&i.Callsign, &i.CdmData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCdmDataForCallsign = `-- name: GetCdmDataForCallsign :one
SELECT callsign, cdm_data FROM strips WHERE session = $1 and callsign = $2
`

type GetCdmDataForCallsignParams struct {
	Session  int32
	Callsign string
}

type GetCdmDataForCallsignRow struct {
	Callsign string
	CdmData  []byte
}

func (q *Queries) GetCdmDataForCallsign(ctx context.Context, arg GetCdmDataForCallsignParams) (GetCdmDataForCallsignRow, error) {
	row := q.db.QueryRow(ctx, getCdmDataForCallsign, arg.Session, arg.Callsign)
	var i GetCdmDataForCallsignRow
	err := row.Scan(&i.Callsign, &i.CdmData)
	return i, err
}

const getMaxSequenceInBay = `-- name: GetMaxSequenceInBay :one
SELECT COALESCE(max(sequence), 0)::INTEGER AS max_sequence
FROM strips
WHERE session = $1 AND bay = $2::TEXT
`

type GetMaxSequenceInBayParams struct {
	Session int32
	Bay     string
}

func (q *Queries) GetMaxSequenceInBay(ctx context.Context, arg GetMaxSequenceInBayParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceInBay, arg.Session, arg.Bay)
	var max_sequence int32
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const getMaxSequenceInBayUnified = `-- name: GetMaxSequenceInBayUnified :one
SELECT COALESCE(MAX(seq), 0)::INTEGER AS max_sequence
FROM (
    SELECT sequence AS seq FROM strips          WHERE session = $1 AND bay = $2::TEXT
    UNION ALL
    SELECT sequence AS seq FROM tactical_strips WHERE session_id = $1 AND bay = $2::TEXT
) combined
`

type GetMaxSequenceInBayUnifiedParams struct {
	Session int32
	Bay     string
}

// Returns the maximum sequence value across BOTH strips and tactical_strips for a bay.
func (q *Queries) GetMaxSequenceInBayUnified(ctx context.Context, arg GetMaxSequenceInBayUnifiedParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceInBayUnified, arg.Session, arg.Bay)
	var max_sequence int32
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const getMinSequenceInBay = `-- name: GetMinSequenceInBay :one
SELECT COALESCE(min(sequence), 0)::INTEGER AS min_sequence
FROM strips
WHERE session = $1 AND bay = $2::TEXT
`

type GetMinSequenceInBayParams struct {
	Session int32
	Bay     string
}

func (q *Queries) GetMinSequenceInBay(ctx context.Context, arg GetMinSequenceInBayParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMinSequenceInBay, arg.Session, arg.Bay)
	var min_sequence int32
	err := row.Scan(&min_sequence)
	return min_sequence, err
}

const getNextSequence = `-- name: GetNextSequence :one
SELECT sequence::INT
FROM strips
WHERE session = $1 AND bay = $2::TEXT AND sequence > $3::INT
`

type GetNextSequenceParams struct {
	Session  int32
	Bay      string
	Sequence int32
}

func (q *Queries) GetNextSequence(ctx context.Context, arg GetNextSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSequence, arg.Session, arg.Bay, arg.Sequence)
	var sequence int32
	err := row.Scan(&sequence)
	return sequence, err
}

const getNextSequenceUnified = `-- name: GetNextSequenceUnified :one
SELECT seq::INT AS next_sequence
FROM (
    SELECT sequence AS seq FROM strips          WHERE session = $1 AND bay = $2::TEXT AND sequence > $3::INT
    UNION ALL
    SELECT sequence AS seq FROM tactical_strips WHERE session_id = $1 AND bay = $2::TEXT AND sequence > $3::INT
) combined
ORDER BY seq
LIMIT 1
`

type GetNextSequenceUnifiedParams struct {
	Session int32
	Bay     string
	Prev    int32
}

// Returns the smallest sequence > prev across BOTH strips and tactical_strips in the bay.
// Returns pgx.ErrNoRows if nothing exists above prev (append to bottom).
func (q *Queries) GetNextSequenceUnified(ctx context.Context, arg GetNextSequenceUnifiedParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSequenceUnified, arg.Session, arg.Bay, arg.Prev)
	var next_sequence int32
	err := row.Scan(&next_sequence)
	return next_sequence, err
}

const getPrevSequence = `-- name: GetPrevSequence :one
SELECT sequence::INT
FROM strips
WHERE session = $1 AND bay = $2::TEXT AND sequence < $3::INT AND callsign != $4::TEXT
ORDER BY sequence DESC
LIMIT 1
`

type GetPrevSequenceParams struct {
	Session         int32
	Bay             string
	Seq             int32
	ExcludeCallsign string
}

func (q *Queries) GetPrevSequence(ctx context.Context, arg GetPrevSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPrevSequence,
		arg.Session,
		arg.Bay,
		arg.Seq,
		arg.ExcludeCallsign,
	)
	var sequence int32
	err := row.Scan(&sequence)
	return sequence, err
}

const getPrevSequenceUnified = `-- name: GetPrevSequenceUnified :one
SELECT seq::INT AS prev_sequence
FROM (
    SELECT sequence AS seq FROM strips          WHERE session = $1 AND bay = $2::TEXT AND sequence < $3::INT AND callsign != $4::TEXT
    UNION ALL
    SELECT sequence AS seq FROM tactical_strips WHERE session_id = $1 AND bay = $2::TEXT AND sequence < $3::INT
) combined
ORDER BY seq DESC
LIMIT 1
`

type GetPrevSequenceUnifiedParams struct {
	Session         int32
	Bay             string
	Seq             int32
	ExcludeCallsign string
}

// Returns the largest sequence < seq across BOTH strips and tactical_strips in the bay,
// excluding a specific callsign from the strips table (the flight strip being moved).
// Returns pgx.ErrNoRows if nothing exists below seq (strip is already at top).
func (q *Queries) GetPrevSequenceUnified(ctx context.Context, arg GetPrevSequenceUnifiedParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPrevSequenceUnified,
		arg.Session,
		arg.Bay,
		arg.Seq,
		arg.ExcludeCallsign,
	)
	var prev_sequence int32
	err := row.Scan(&prev_sequence)
	return prev_sequence, err
}

const getSequence = `-- name: GetSequence :one
SELECT sequence::INT
FROM strips
WHERE session = $1 AND callsign = $2 AND bay = $3::TEXT
LIMIT 1
`

type GetSequenceParams struct {
	Session  int32
	Callsign string
	Bay      string
}

func (q *Queries) GetSequence(ctx context.Context, arg GetSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSequence, arg.Session, arg.Callsign, arg.Bay)
	var sequence int32
	err := row.Scan(&sequence)
	return sequence, err
}

const getStrip = `-- name: GetStrip :one
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, next_owners, previous_owners, release_point, marked, registration, tracking_controller, runway_cleared, unexpected_change_fields, controller_modified_fields, engine_type, is_manual, persons_on_board, fpl_type, language, has_fp, cdm_data, runway_confirmed, pdc_data, validation_status
FROM strips
WHERE callsign = $1 AND session = $2
`

type GetStripParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) GetStrip(ctx context.Context, arg GetStripParams) (Strip, error) {
	row := q.db.QueryRow(ctx, getStrip, arg.Callsign, arg.Session)
	var i Strip
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Callsign,
		&i.Session,
		&i.Origin,
		&i.Destination,
		&i.Alternative,
		&i.Route,
		&i.Remarks,
		&i.AssignedSquawk,
		&i.Squawk,
		&i.Sid,
		&i.ClearedAltitude,
		&i.Heading,
		&i.AircraftType,
		&i.Runway,
		&i.RequestedAltitude,
		&i.Capabilities,
		&i.CommunicationType,
		&i.AircraftCategory,
		&i.Stand,
		&i.Sequence,
		&i.State,
		&i.Cleared,
		&i.Owner,
		&i.Bay,
		&i.PositionLatitude,
		&i.PositionLongitude,
		&i.PositionAltitude,
		&i.NextOwners,
		&i.PreviousOwners,
		&i.ReleasePoint,
		&i.Marked,
		&i.Registration,
		&i.TrackingController,
		&i.RunwayCleared,
		&i.UnexpectedChangeFields,
		&i.ControllerModifiedFields,
		&i.EngineType,
		&i.IsManual,
		&i.PersonsOnBoard,
		&i.FplType,
		&i.Language,
		&i.HasFp,
		&i.CdmData,
		&i.RunwayConfirmed,
		&i.PdcData,
		&i.ValidationStatus,
	)
	return i, err
}

const insertStrip = `-- name: InsertStrip :exec
INSERT INTO strips (version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk,
                    squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities,
                    communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay,
                    position_latitude, position_longitude, position_altitude, cdm_data, registration,
                    tracking_controller, engine_type)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23,
        $24, $25, $26, $27, $28, $29, $30, $31)
`

type InsertStripParams struct {
	Callsign           string
	Session            int32
	Origin             string
	Destination        string
	Alternative        *string
	Route              *string
	Remarks            *string
	AssignedSquawk     *string
	Squawk             *string
	Sid                *string
	ClearedAltitude    *int32
	Heading            *int32
	AircraftType       *string
	Runway             *string
	RequestedAltitude  *int32
	Capabilities       *string
	CommunicationType  *string
	AircraftCategory   *string
	Stand              *string
	Sequence           *int32
	State              *string
	Cleared            bool
	Owner              *string
	Bay                string
	PositionLatitude   *float64
	PositionLongitude  *float64
	PositionAltitude   *int32
	CdmData            []byte
	Registration       *string
	TrackingController string
	EngineType         string
}

func (q *Queries) InsertStrip(ctx context.Context, arg InsertStripParams) error {
	_, err := q.db.Exec(ctx, insertStrip,
		arg.Callsign,
		arg.Session,
		arg.Origin,
		arg.Destination,
		arg.Alternative,
		arg.Route,
		arg.Remarks,
		arg.AssignedSquawk,
		arg.Squawk,
		arg.Sid,
		arg.ClearedAltitude,
		arg.Heading,
		arg.AircraftType,
		arg.Runway,
		arg.RequestedAltitude,
		arg.Capabilities,
		arg.CommunicationType,
		arg.AircraftCategory,
		arg.Stand,
		arg.Sequence,
		arg.State,
		arg.Cleared,
		arg.Owner,
		arg.Bay,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.CdmData,
		arg.Registration,
		arg.TrackingController,
		arg.EngineType,
	)
	return err
}

const listStripSequences = `-- name: ListStripSequences :many
SELECT callsign, sequence
FROM strips
WHERE session = $1 AND bay = $2::TEXT
ORDER BY sequence, callsign
`

type ListStripSequencesParams struct {
	Session int32
	Bay     string
}

type ListStripSequencesRow struct {
	Callsign string
	Sequence *int32
}

func (q *Queries) ListStripSequences(ctx context.Context, arg ListStripSequencesParams) ([]ListStripSequencesRow, error) {
	rows, err := q.db.Query(ctx, listStripSequences, arg.Session, arg.Bay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStripSequencesRow
	for rows.Next() {
		var i ListStripSequencesRow
		if err := rows.Scan(&i.Callsign, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrips = `-- name: ListStrips :many
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, next_owners, previous_owners, release_point, marked, registration, tracking_controller, runway_cleared, unexpected_change_fields, controller_modified_fields, engine_type, is_manual, persons_on_board, fpl_type, language, has_fp, cdm_data, runway_confirmed, pdc_data, validation_status
FROM strips
WHERE session = $1
ORDER BY callsign
`

func (q *Queries) ListStrips(ctx context.Context, session int32) ([]Strip, error) {
	rows, err := q.db.Query(ctx, listStrips, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strip
	for rows.Next() {
		var i Strip
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Callsign,
			&i.Session,
			&i.Origin,
			&i.Destination,
			&i.Alternative,
			&i.Route,
			&i.Remarks,
			&i.AssignedSquawk,
			&i.Squawk,
			&i.Sid,
			&i.ClearedAltitude,
			&i.Heading,
			&i.AircraftType,
			&i.Runway,
			&i.RequestedAltitude,
			&i.Capabilities,
			&i.CommunicationType,
			&i.AircraftCategory,
			&i.Stand,
			&i.Sequence,
			&i.State,
			&i.Cleared,
			&i.Owner,
			&i.Bay,
			&i.PositionLatitude,
			&i.PositionLongitude,
			&i.PositionAltitude,
			&i.NextOwners,
			&i.PreviousOwners,
			&i.ReleasePoint,
			&i.Marked,
			&i.Registration,
			&i.TrackingController,
			&i.RunwayCleared,
			&i.UnexpectedChangeFields,
			&i.ControllerModifiedFields,
			&i.EngineType,
			&i.IsManual,
			&i.PersonsOnBoard,
			&i.FplType,
			&i.Language,
			&i.HasFp,
			&i.CdmData,
			&i.RunwayConfirmed,
			&i.PdcData,
			&i.ValidationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStripsByOrigin = `-- name: ListStripsByOrigin :many
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, next_owners, previous_owners, release_point, marked, registration, tracking_controller, runway_cleared, unexpected_change_fields, controller_modified_fields, engine_type, is_manual, persons_on_board, fpl_type, language, has_fp, cdm_data, runway_confirmed, pdc_data, validation_status
FROM strips
WHERE origin = $1 AND session = $2
ORDER BY callsign
`

type ListStripsByOriginParams struct {
	Origin  string
	Session int32
}

func (q *Queries) ListStripsByOrigin(ctx context.Context, arg ListStripsByOriginParams) ([]Strip, error) {
	rows, err := q.db.Query(ctx, listStripsByOrigin, arg.Origin, arg.Session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strip
	for rows.Next() {
		var i Strip
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Callsign,
			&i.Session,
			&i.Origin,
			&i.Destination,
			&i.Alternative,
			&i.Route,
			&i.Remarks,
			&i.AssignedSquawk,
			&i.Squawk,
			&i.Sid,
			&i.ClearedAltitude,
			&i.Heading,
			&i.AircraftType,
			&i.Runway,
			&i.RequestedAltitude,
			&i.Capabilities,
			&i.CommunicationType,
			&i.AircraftCategory,
			&i.Stand,
			&i.Sequence,
			&i.State,
			&i.Cleared,
			&i.Owner,
			&i.Bay,
			&i.PositionLatitude,
			&i.PositionLongitude,
			&i.PositionAltitude,
			&i.NextOwners,
			&i.PreviousOwners,
			&i.ReleasePoint,
			&i.Marked,
			&i.Registration,
			&i.TrackingController,
			&i.RunwayCleared,
			&i.UnexpectedChangeFields,
			&i.ControllerModifiedFields,
			&i.EngineType,
			&i.IsManual,
			&i.PersonsOnBoard,
			&i.FplType,
			&i.Language,
			&i.HasFp,
			&i.CdmData,
			&i.RunwayConfirmed,
			&i.PdcData,
			&i.ValidationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateStripSequences = `-- name: RecalculateStripSequences :exec
WITH row_numbers AS (
    SELECT s.id, (ROW_NUMBER() OVER (ORDER BY s.sequence, s.callsign)) * $2::INT AS new_sequence
    FROM strips as s
    WHERE s.session = $1 AND s.bay = $3::TEXT
)
UPDATE strips
SET sequence = row_numbers.new_sequence,
    version  = strips.version + 1
FROM row_numbers
WHERE strips.id = row_numbers.id AND strips.session = $1
`

type RecalculateStripSequencesParams struct {
	Session int32
	Spacing int32
	Bay     string
}

func (q *Queries) RecalculateStripSequences(ctx context.Context, arg RecalculateStripSequencesParams) error {
	_, err := q.db.Exec(ctx, recalculateStripSequences, arg.Session, arg.Spacing, arg.Bay)
	return err
}

const removeStripByID = `-- name: RemoveStripByID :exec
DELETE
FROM strips
WHERE callsign = $1 AND session = $2
`

type RemoveStripByIDParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) RemoveStripByID(ctx context.Context, arg RemoveStripByIDParams) error {
	_, err := q.db.Exec(ctx, removeStripByID, arg.Callsign, arg.Session)
	return err
}

const removeUnexpectedChangeField = `-- name: RemoveUnexpectedChangeField :exec
UPDATE strips
SET unexpected_change_fields = array_remove(unexpected_change_fields, $3)
WHERE session = $1 AND callsign = $2
`

type RemoveUnexpectedChangeFieldParams struct {
	Session     int32
	Callsign    string
	ArrayRemove interface{}
}

func (q *Queries) RemoveUnexpectedChangeField(ctx context.Context, arg RemoveUnexpectedChangeFieldParams) error {
	_, err := q.db.Exec(ctx, removeUnexpectedChangeField, arg.Session, arg.Callsign, arg.ArrayRemove)
	return err
}

const resetRunwayClearance = `-- name: ResetRunwayClearance :execrows
UPDATE strips
SET runway_cleared   = false,
    runway_confirmed = false,
    version          = version + 1
WHERE callsign = $1 AND session = $2
`

type ResetRunwayClearanceParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) ResetRunwayClearance(ctx context.Context, arg ResetRunwayClearanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetRunwayClearance, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCdmData = `-- name: SetCdmData :execrows
UPDATE strips SET cdm_data = $3 WHERE session = $1 AND callsign = $2
`

type SetCdmDataParams struct {
	Session  int32
	Callsign string
	CdmData  []byte
}

func (q *Queries) SetCdmData(ctx context.Context, arg SetCdmDataParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCdmData, arg.Session, arg.Callsign, arg.CdmData)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNextAndPreviousOwners = `-- name: SetNextAndPreviousOwners :exec
UPDATE strips SET next_owners = $3, previous_owners = $4 WHERE session = $1 AND callsign = $2
`

type SetNextAndPreviousOwnersParams struct {
	Session        int32
	Callsign       string
	NextOwners     []string
	PreviousOwners []string
}

func (q *Queries) SetNextAndPreviousOwners(ctx context.Context, arg SetNextAndPreviousOwnersParams) error {
	_, err := q.db.Exec(ctx, setNextAndPreviousOwners,
		arg.Session,
		arg.Callsign,
		arg.NextOwners,
		arg.PreviousOwners,
	)
	return err
}

const setNextOwners = `-- name: SetNextOwners :exec
UPDATE strips SET next_owners = $3 WHERE session = $1 AND callsign = $2
`

type SetNextOwnersParams struct {
	Session    int32
	Callsign   string
	NextOwners []string
}

func (q *Queries) SetNextOwners(ctx context.Context, arg SetNextOwnersParams) error {
	_, err := q.db.Exec(ctx, setNextOwners, arg.Session, arg.Callsign, arg.NextOwners)
	return err
}

const setPdcData = `-- name: SetPdcData :exec
UPDATE strips SET pdc_data = $3 WHERE session = $1 AND callsign = $2
`

type SetPdcDataParams struct {
	Session  int32
	Callsign string
	PdcData  []byte
}

func (q *Queries) SetPdcData(ctx context.Context, arg SetPdcDataParams) error {
	_, err := q.db.Exec(ctx, setPdcData, arg.Session, arg.Callsign, arg.PdcData)
	return err
}

const setPreviousOwners = `-- name: SetPreviousOwners :exec
UPDATE strips SET previous_owners = $3 WHERE session = $1 AND callsign = $2
`

type SetPreviousOwnersParams struct {
	Session        int32
	Callsign       string
	PreviousOwners []string
}

func (q *Queries) SetPreviousOwners(ctx context.Context, arg SetPreviousOwnersParams) error {
	_, err := q.db.Exec(ctx, setPreviousOwners, arg.Session, arg.Callsign, arg.PreviousOwners)
	return err
}

const setStripOwner = `-- name: SetStripOwner :execrows
UPDATE strips
SET owner   = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND version = $4
`

type SetStripOwnerParams struct {
	Owner    *string
	Callsign string
	Session  int32
	Version  int32
}

func (q *Queries) SetStripOwner(ctx context.Context, arg SetStripOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStripOwner,
		arg.Owner,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateReleasePoint = `-- name: UpdateReleasePoint :execrows
UPDATE strips SET release_point = $3 WHERE session = $1 AND callsign = $2
`

type UpdateReleasePointParams struct {
	Session      int32
	Callsign     string
	ReleasePoint *string
}

func (q *Queries) UpdateReleasePoint(ctx context.Context, arg UpdateReleasePointParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReleasePoint, arg.Session, arg.Callsign, arg.ReleasePoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRunwayClearance = `-- name: UpdateRunwayClearance :execrows
UPDATE strips
SET bay            = CASE
                       WHEN bay = 'TAXI_LWR' THEN 'DEPART'
                       WHEN bay = 'FINAL'    THEN 'RWY_ARR'
                       ELSE bay
                     END,
    runway_cleared    = true,
    runway_confirmed  = NOT EXISTS (
                          SELECT 1
                          FROM strips AS s2
                          WHERE s2.session = $2
                            AND s2.callsign != $1
                            AND s2.runway_confirmed = true
                            AND s2.bay IN ('DEPART', 'RWY_ARR')
                            AND s2.runway = (SELECT s3.runway FROM strips s3 WHERE s3.callsign = $1 AND s3.session = $2)
                        ),
    version        = version + 1
WHERE callsign = $1 AND session = $2
`

type UpdateRunwayClearanceParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) UpdateRunwayClearance(ctx context.Context, arg UpdateRunwayClearanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunwayClearance, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRunwayConfirmation = `-- name: UpdateRunwayConfirmation :execrows
UPDATE strips
SET runway_confirmed = true,
    version          = version + 1
WHERE callsign = $1 AND session = $2
`

type UpdateRunwayConfirmationParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) UpdateRunwayConfirmation(ctx context.Context, arg UpdateRunwayConfirmationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRunwayConfirmation, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStrip = `-- name: UpdateStrip :execrows
UPDATE strips
SET (version, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude,
     heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand,
     sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, cdm_data,
     registration, tracking_controller, engine_type
    ) = (
         version + 1, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22,
         $23, $24, $25, $26, $27, $28, $29, $30, $31)
WHERE callsign = $1 AND session = $2
`

type UpdateStripParams struct {
	Callsign           string
	Session            int32
	Origin             string
	Destination        string
	Alternative        *string
	Route              *string
	Remarks            *string
	AssignedSquawk     *string
	Squawk             *string
	Sid                *string
	ClearedAltitude    *int32
	Heading            *int32
	AircraftType       *string
	Runway             *string
	RequestedAltitude  *int32
	Capabilities       *string
	CommunicationType  *string
	AircraftCategory   *string
	Stand              *string
	Sequence           *int32
	State              *string
	Cleared            bool
	Owner              *string
	Bay                string
	PositionLatitude   *float64
	PositionLongitude  *float64
	PositionAltitude   *int32
	CdmData            []byte
	Registration       *string
	TrackingController string
	EngineType         string
}

func (q *Queries) UpdateStrip(ctx context.Context, arg UpdateStripParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStrip,
		arg.Callsign,
		arg.Session,
		arg.Origin,
		arg.Destination,
		arg.Alternative,
		arg.Route,
		arg.Remarks,
		arg.AssignedSquawk,
		arg.Squawk,
		arg.Sid,
		arg.ClearedAltitude,
		arg.Heading,
		arg.AircraftType,
		arg.Runway,
		arg.RequestedAltitude,
		arg.Capabilities,
		arg.CommunicationType,
		arg.AircraftCategory,
		arg.Stand,
		arg.Sequence,
		arg.State,
		arg.Cleared,
		arg.Owner,
		arg.Bay,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.CdmData,
		arg.Registration,
		arg.TrackingController,
		arg.EngineType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripAircraftPositionByID = `-- name: UpdateStripAircraftPositionByID :execrows
UPDATE strips
SET position_latitude  = $1,
    position_longitude = $2,
    position_altitude  = $3,
    bay                = $4
WHERE callsign = $5 AND session = $6 AND (version = $7 OR $7 IS NULL)
`

type UpdateStripAircraftPositionByIDParams struct {
	PositionLatitude  *float64
	PositionLongitude *float64
	PositionAltitude  *int32
	Bay               string
	Callsign          string
	Session           int32
	Version           *int32
}

func (q *Queries) UpdateStripAircraftPositionByID(ctx context.Context, arg UpdateStripAircraftPositionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripAircraftPositionByID,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripAssignedSquawkByID = `-- name: UpdateStripAssignedSquawkByID :execrows
UPDATE strips
SET assigned_squawk = $1,
    version         = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripAssignedSquawkByIDParams struct {
	AssignedSquawk *string
	Callsign       string
	Session        int32
	Version        *int32
}

func (q *Queries) UpdateStripAssignedSquawkByID(ctx context.Context, arg UpdateStripAssignedSquawkByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripAssignedSquawkByID,
		arg.AssignedSquawk,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripBayAndSequence = `-- name: UpdateStripBayAndSequence :execrows
UPDATE strips
SET bay      = $3,
    sequence = $4::INT,
    version  = version + 1
WHERE session = $1 AND callsign = $2
`

type UpdateStripBayAndSequenceParams struct {
	Session  int32
	Callsign string
	Bay      string
	Sequence int32
}

func (q *Queries) UpdateStripBayAndSequence(ctx context.Context, arg UpdateStripBayAndSequenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripBayAndSequence,
		arg.Session,
		arg.Callsign,
		arg.Bay,
		arg.Sequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripBayByID = `-- name: UpdateStripBayByID :execrows
UPDATE strips
SET bay     = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripBayByIDParams struct {
	Bay      string
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripBayByID(ctx context.Context, arg UpdateStripBayByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripBayByID,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripClearedAltitudeByID = `-- name: UpdateStripClearedAltitudeByID :execrows
UPDATE strips
SET cleared_altitude = $1,
    version          = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripClearedAltitudeByIDParams struct {
	ClearedAltitude *int32
	Callsign        string
	Session         int32
	Version         *int32
}

func (q *Queries) UpdateStripClearedAltitudeByID(ctx context.Context, arg UpdateStripClearedAltitudeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripClearedAltitudeByID,
		arg.ClearedAltitude,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripClearedFlagByID = `-- name: UpdateStripClearedFlagByID :execrows
UPDATE strips
SET cleared = $1,
    bay     = $2,
    version = version + 1
WHERE callsign = $3 AND session = $4 AND (version = $5 OR $5 IS NULL)
`

type UpdateStripClearedFlagByIDParams struct {
	Cleared  bool
	Bay      string
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripClearedFlagByID(ctx context.Context, arg UpdateStripClearedFlagByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripClearedFlagByID,
		arg.Cleared,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripCommunicationTypeByID = `-- name: UpdateStripCommunicationTypeByID :execrows
UPDATE strips
SET communication_type = $1,
    version            = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripCommunicationTypeByIDParams struct {
	CommunicationType *string
	Callsign          string
	Session           int32
	Version           *int32
}

func (q *Queries) UpdateStripCommunicationTypeByID(ctx context.Context, arg UpdateStripCommunicationTypeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripCommunicationTypeByID,
		arg.CommunicationType,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripGroundStateByID = `-- name: UpdateStripGroundStateByID :execrows
UPDATE strips
SET state   = $1,
    bay     = $2,
    version = version + 1
WHERE callsign = $3 AND session = $4 AND (version = $5 OR $5 IS NULL)
`

type UpdateStripGroundStateByIDParams struct {
	State    *string
	Bay      string
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripGroundStateByID(ctx context.Context, arg UpdateStripGroundStateByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripGroundStateByID,
		arg.State,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripHeadingByID = `-- name: UpdateStripHeadingByID :execrows
UPDATE strips
SET heading = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripHeadingByIDParams struct {
	Heading  *int32
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripHeadingByID(ctx context.Context, arg UpdateStripHeadingByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripHeadingByID,
		arg.Heading,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripMarkedByID = `-- name: UpdateStripMarkedByID :execrows
UPDATE strips
SET marked  = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripMarkedByIDParams struct {
	Marked   bool
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripMarkedByID(ctx context.Context, arg UpdateStripMarkedByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripMarkedByID,
		arg.Marked,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripRegistration = `-- name: UpdateStripRegistration :execrows
UPDATE strips
SET registration = $1,
    version      = version + 1
WHERE callsign = $2 AND session = $3
`

type UpdateStripRegistrationParams struct {
	Registration *string
	Callsign     string
	Session      int32
}

func (q *Queries) UpdateStripRegistration(ctx context.Context, arg UpdateStripRegistrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripRegistration, arg.Registration, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripRequestedAltitudeByID = `-- name: UpdateStripRequestedAltitudeByID :execrows
UPDATE strips
SET requested_altitude = $1,
    version            = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripRequestedAltitudeByIDParams struct {
	RequestedAltitude *int32
	Callsign          string
	Session           int32
	Version           *int32
}

func (q *Queries) UpdateStripRequestedAltitudeByID(ctx context.Context, arg UpdateStripRequestedAltitudeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripRequestedAltitudeByID,
		arg.RequestedAltitude,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripRunwayByID = `-- name: UpdateStripRunwayByID :execrows
UPDATE strips
SET runway  = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripRunwayByIDParams struct {
	Runway   *string
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripRunwayByID(ctx context.Context, arg UpdateStripRunwayByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripRunwayByID,
		arg.Runway,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripSequence = `-- name: UpdateStripSequence :execrows
UPDATE strips
SET sequence = $3::INT,
    version  = version + 1
WHERE session = $1 AND callsign = $2
`

type UpdateStripSequenceParams struct {
	Session  int32
	Callsign string
	Sequence int32
}

func (q *Queries) UpdateStripSequence(ctx context.Context, arg UpdateStripSequenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripSequence, arg.Session, arg.Callsign, arg.Sequence)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripSequenceBulk = `-- name: UpdateStripSequenceBulk :exec
UPDATE strips AS s
SET sequence = u.new_sequence,
    version  = s.version + 1
FROM (SELECT unnest($2::TEXT[]) AS callsign, unnest($3::INT[]) AS new_sequence) AS u
WHERE s.session = $1 AND s.callsign = u.callsign
`

type UpdateStripSequenceBulkParams struct {
	Session   int32
	Callsigns []string
	Sequences []int32
}

func (q *Queries) UpdateStripSequenceBulk(ctx context.Context, arg UpdateStripSequenceBulkParams) error {
	_, err := q.db.Exec(ctx, updateStripSequenceBulk, arg.Session, arg.Callsigns, arg.Sequences)
	return err
}

const updateStripSquawkByID = `-- name: UpdateStripSquawkByID :execrows
UPDATE strips
SET squawk  = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripSquawkByIDParams struct {
	Squawk   *string
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripSquawkByID(ctx context.Context, arg UpdateStripSquawkByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripSquawkByID,
		arg.Squawk,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripStandByID = `-- name: UpdateStripStandByID :execrows
UPDATE strips
SET stand   = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3
  AND (stand IS DISTINCT FROM $1)
  AND (version = $4 OR $4 IS NULL)
`

type UpdateStripStandByIDParams struct {
	Stand    *string
	Callsign string
	Session  int32
	Version  *int32
}

func (q *Queries) UpdateStripStandByID(ctx context.Context, arg UpdateStripStandByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripStandByID,
		arg.Stand,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTrackingController = `-- name: UpdateTrackingController :execrows
UPDATE strips
SET tracking_controller = $1
WHERE callsign = $2 AND session = $3
`

type UpdateTrackingControllerParams struct {
	TrackingController string
	Callsign           string
	Session            int32
}

func (q *Queries) UpdateTrackingController(ctx context.Context, arg UpdateTrackingControllerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTrackingController, arg.TrackingController, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
