package database

import "context"

// ManualFPLFields holds the extra columns added by migrations 0017/0018 that are not
// generated by sqlc.
type ManualFPLFields struct {
	IsManual       bool
	PersonsOnBoard *int32
	FplType        *string
	Language       *string
	HasFP          bool
}

// ManualFPLFieldsRow is returned by ListManualFPLFieldsBySession for bulk lookups.
type ManualFPLFieldsRow struct {
	Callsign       string
	IsManual       bool
	PersonsOnBoard *int32
	FplType        *string
	Language       *string
	HasFP          bool
}

// UpdateIFRManualFPLFieldsParams holds the parameters for UpdateIFRManualFPLFields.
type UpdateIFRManualFPLFieldsParams struct {
	Session           int32
	Callsign          string
	Destination       string
	Sid               *string
	AssignedSquawk    *string
	Eobt              *string
	AircraftType      *string
	RequestedAltitude *int32
	Route             *string
	Stand             *string
	Runway            *string
}

const updateIFRManualFPLFields = `
UPDATE strips
SET destination        = $3,
    sid                = COALESCE($4, sid),
    assigned_squawk    = COALESCE($5, assigned_squawk),
    cdm_data           = CASE
                           WHEN $6 IS NULL THEN cdm_data
                           ELSE jsonb_set(
                               jsonb_set(
                                   cdm_data,
                                   '{canonical}',
                                   COALESCE(cdm_data->'canonical', '{}'::jsonb),
                                   true
                               ),
                               '{canonical,eobt}',
                               to_jsonb($6::text),
                               true
                           )
                         END,
    aircraft_type      = COALESCE($7, aircraft_type),
    requested_altitude = COALESCE($8, requested_altitude),
    route              = COALESCE($9, route),
    stand              = COALESCE($10, stand),
    runway             = COALESCE($11, runway),
    is_manual          = TRUE,
    has_fp             = TRUE,
    version            = version + 1
WHERE session = $1 AND callsign = $2`

// UpdateIFRManualFPLFields sets IFR flight-plan fields on an existing strip and
// marks it as manually created (is_manual = TRUE). Returns the number of rows affected.
func (q *Queries) UpdateIFRManualFPLFields(ctx context.Context, arg UpdateIFRManualFPLFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIFRManualFPLFields,
		arg.Session, arg.Callsign, arg.Destination,
		arg.Sid, arg.AssignedSquawk, arg.Eobt, arg.AircraftType,
		arg.RequestedAltitude, arg.Route, arg.Stand, arg.Runway,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

// UpdateVFRManualFPLFieldsParams holds the parameters for UpdateVFRManualFPLFields.
type UpdateVFRManualFPLFieldsParams struct {
	Session        int32
	Callsign       string
	AircraftType   *string
	PersonsOnBoard *int32
	AssignedSquawk string
	FplType        *string
	Language       *string
	Remarks        *string
	Bay            string
}

const updateVFRManualFPLFields = `
UPDATE strips
SET aircraft_type   = COALESCE($3, aircraft_type),
    persons_on_board = COALESCE($4, persons_on_board),
    assigned_squawk = $5,
    fpl_type        = COALESCE($6, fpl_type),
    language        = COALESCE($7, language),
    remarks         = COALESCE($8, remarks),
    is_manual       = TRUE,
    has_fp          = TRUE,
    bay             = $9,
    version         = version + 1
WHERE session = $1 AND callsign = $2`

// UpdateVFRManualFPLFields sets VFR flight-plan fields and moves the strip to the
// given bay (expected: CONTROLZONE). Returns the number of rows affected.
func (q *Queries) UpdateVFRManualFPLFields(ctx context.Context, arg UpdateVFRManualFPLFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVFRManualFPLFields,
		arg.Session, arg.Callsign, arg.AircraftType,
		arg.PersonsOnBoard, arg.AssignedSquawk,
		arg.FplType, arg.Language, arg.Remarks, arg.Bay,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManualFPLFields = `
SELECT is_manual, persons_on_board, fpl_type, language, has_fp
FROM strips
WHERE session = $1 AND callsign = $2`

// GetManualFPLFields fetches the manual-FPL columns for a single strip.
func (q *Queries) GetManualFPLFields(ctx context.Context, session int32, callsign string) (ManualFPLFields, error) {
	row := q.db.QueryRow(ctx, getManualFPLFields, session, callsign)
	var f ManualFPLFields
	err := row.Scan(&f.IsManual, &f.PersonsOnBoard, &f.FplType, &f.Language, &f.HasFP)
	return f, err
}

const listManualFPLFieldsBySession = `
SELECT callsign, is_manual, persons_on_board, fpl_type, language, has_fp
FROM strips
WHERE session = $1`

// ListManualFPLFieldsBySession fetches manual-FPL columns for all strips in a
// session in a single query (avoids N+1 in List).
func (q *Queries) ListManualFPLFieldsBySession(ctx context.Context, session int32) ([]ManualFPLFieldsRow, error) {
	rows, err := q.db.Query(ctx, listManualFPLFieldsBySession, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualFPLFieldsRow
	for rows.Next() {
		var r ManualFPLFieldsRow
		if err := rows.Scan(&r.Callsign, &r.IsManual, &r.PersonsOnBoard, &r.FplType, &r.Language, &r.HasFP); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}

const setHasFP = `
UPDATE strips SET has_fp = $3, version = version + 1
WHERE session = $1 AND callsign = $2`

// SetHasFP sets the has_fp flag on a strip. Used when a FPL is received from EuroScope
// for an aircraft that was previously tracked without a flight plan.
func (q *Queries) SetHasFP(ctx context.Context, session int32, callsign string, hasFP bool) error {
	_, err := q.db.Exec(ctx, setHasFP, session, callsign, hasFP)
	return err
}

// ValidationStatusRow is returned by GetValidationStatusBySession for bulk lookups.
type ValidationStatusRow struct {
	Callsign         string
	ValidationStatus []byte
}

const getValidationStatusBySession = `
SELECT callsign, validation_status
FROM strips
WHERE session = $1`

// GetValidationStatusBySession bulk-fetches the validation_status JSONB column for all
// strips in a session (avoids N+1 in List).
func (q *Queries) GetValidationStatusBySession(ctx context.Context, session int32) ([]ValidationStatusRow, error) {
	rows, err := q.db.Query(ctx, getValidationStatusBySession, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationStatusRow
	for rows.Next() {
		var r ValidationStatusRow
		if err := rows.Scan(&r.Callsign, &r.ValidationStatus); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}

const getValidationStatusForCallsign = `
SELECT validation_status
FROM strips
WHERE session = $1 AND callsign = $2`

// GetValidationStatusForCallsign fetches the validation_status JSONB for a single strip.
func (q *Queries) GetValidationStatusForCallsign(ctx context.Context, session int32, callsign string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getValidationStatusForCallsign, session, callsign)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const setValidationStatusSQL = `
UPDATE strips
SET validation_status = $3, version = version + 1
WHERE session = $1 AND callsign = $2`

// SetValidationStatus persists validation_status JSONB for a strip, bumping the version.
func (q *Queries) SetValidationStatus(ctx context.Context, session int32, callsign string, data []byte) error {
	_, err := q.db.Exec(ctx, setValidationStatusSQL, session, callsign, data)
	return err
}

const acknowledgeValidationStatusSQL = `
UPDATE strips
SET validation_status = jsonb_set(validation_status, '{active}', 'false'), version = version + 1
WHERE session = $1 AND callsign = $2
  AND validation_status->>'activation_key' = $3
  AND (validation_status->>'active')::boolean = true`

// AcknowledgeValidationStatus sets active=false on validation_status if the activation_key
// matches and the status is currently active. Returns the number of rows updated (0 = no-op).
func (q *Queries) AcknowledgeValidationStatus(ctx context.Context, session int32, callsign string, activationKey string) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeValidationStatusSQL, session, callsign, activationKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearValidationStatusSQL = `
UPDATE strips
SET validation_status = NULL, version = version + 1
WHERE session = $1 AND callsign = $2`

// ClearValidationStatus removes the validation_status (sets to NULL) for a strip.
func (q *Queries) ClearValidationStatus(ctx context.Context, session int32, callsign string) error {
	_, err := q.db.Exec(ctx, clearValidationStatusSQL, session, callsign)
	return err
}
