package database

import "context"

// ManualFPLFields holds the extra columns added by migration 0017 that are not
// generated by sqlc.
type ManualFPLFields struct {
	IsManual       bool
	PersonsOnBoard *int32
	FplType        *string
	Language       *string
}

// ManualFPLFieldsRow is returned by ListManualFPLFieldsBySession for bulk lookups.
type ManualFPLFieldsRow struct {
	Callsign       string
	IsManual       bool
	PersonsOnBoard *int32
	FplType        *string
	Language       *string
}

// UpdateIFRManualFPLFieldsParams holds the parameters for UpdateIFRManualFPLFields.
type UpdateIFRManualFPLFieldsParams struct {
	Session           int32
	Callsign          string
	Destination       string
	Sid               *string
	AssignedSquawk    *string
	Eobt              *string
	AircraftType      *string
	RequestedAltitude *int32
	Route             *string
	Stand             *string
	Runway            *string
}

const updateIFRManualFPLFields = `
UPDATE strips
SET destination        = $3,
    sid                = COALESCE($4, sid),
    assigned_squawk    = COALESCE($5, assigned_squawk),
    eobt               = COALESCE($6, eobt),
    aircraft_type      = COALESCE($7, aircraft_type),
    requested_altitude = COALESCE($8, requested_altitude),
    route              = COALESCE($9, route),
    stand              = COALESCE($10, stand),
    runway             = COALESCE($11, runway),
    is_manual          = TRUE,
    version            = version + 1
WHERE session = $1 AND callsign = $2`

// UpdateIFRManualFPLFields sets IFR flight-plan fields on an existing strip and
// marks it as manually created (is_manual = TRUE). Returns the number of rows affected.
func (q *Queries) UpdateIFRManualFPLFields(ctx context.Context, arg UpdateIFRManualFPLFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIFRManualFPLFields,
		arg.Session, arg.Callsign, arg.Destination,
		arg.Sid, arg.AssignedSquawk, arg.Eobt, arg.AircraftType,
		arg.RequestedAltitude, arg.Route, arg.Stand, arg.Runway,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

// UpdateVFRManualFPLFieldsParams holds the parameters for UpdateVFRManualFPLFields.
type UpdateVFRManualFPLFieldsParams struct {
	Session        int32
	Callsign       string
	AircraftType   *string
	PersonsOnBoard *int32
	AssignedSquawk string
	FplType        *string
	Language       *string
	Remarks        *string
	Bay            string
}

const updateVFRManualFPLFields = `
UPDATE strips
SET aircraft_type   = COALESCE($3, aircraft_type),
    persons_on_board = COALESCE($4, persons_on_board),
    assigned_squawk = $5,
    fpl_type        = COALESCE($6, fpl_type),
    language        = COALESCE($7, language),
    remarks         = COALESCE($8, remarks),
    is_manual       = TRUE,
    bay             = $9,
    version         = version + 1
WHERE session = $1 AND callsign = $2`

// UpdateVFRManualFPLFields sets VFR flight-plan fields and moves the strip to the
// given bay (expected: CONTROLZONE). Returns the number of rows affected.
func (q *Queries) UpdateVFRManualFPLFields(ctx context.Context, arg UpdateVFRManualFPLFieldsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVFRManualFPLFields,
		arg.Session, arg.Callsign, arg.AircraftType,
		arg.PersonsOnBoard, arg.AssignedSquawk,
		arg.FplType, arg.Language, arg.Remarks, arg.Bay,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManualFPLFields = `
SELECT is_manual, persons_on_board, fpl_type, language
FROM strips
WHERE session = $1 AND callsign = $2`

// GetManualFPLFields fetches the manual-FPL columns for a single strip.
func (q *Queries) GetManualFPLFields(ctx context.Context, session int32, callsign string) (ManualFPLFields, error) {
	row := q.db.QueryRow(ctx, getManualFPLFields, session, callsign)
	var f ManualFPLFields
	err := row.Scan(&f.IsManual, &f.PersonsOnBoard, &f.FplType, &f.Language)
	return f, err
}

const listManualFPLFieldsBySession = `
SELECT callsign, is_manual, persons_on_board, fpl_type, language
FROM strips
WHERE session = $1`

// ListManualFPLFieldsBySession fetches manual-FPL columns for all strips in a
// session in a single query (avoids N+1 in List).
func (q *Queries) ListManualFPLFieldsBySession(ctx context.Context, session int32) ([]ManualFPLFieldsRow, error) {
	rows, err := q.db.Query(ctx, listManualFPLFieldsBySession, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualFPLFieldsRow
	for rows.Next() {
		var r ManualFPLFieldsRow
		if err := rows.Scan(&r.Callsign, &r.IsManual, &r.PersonsOnBoard, &r.FplType, &r.Language); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}
