// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tactical_strips.sql

package database

import (
	"context"
)

const confirmTacticalStrip = `-- name: ConfirmTacticalStrip :one
UPDATE tactical_strips
SET confirmed = TRUE, confirmed_by = $3
WHERE id = $1 AND session_id = $2
RETURNING id, session_id, type, bay, label, aircraft, produced_by, sequence, timer_start, confirmed, confirmed_by, created_at
`

type ConfirmTacticalStripParams struct {
	ID          int64
	SessionID   int32
	ConfirmedBy *string
}

func (q *Queries) ConfirmTacticalStrip(ctx context.Context, arg ConfirmTacticalStripParams) (TacticalStrip, error) {
	row := q.db.QueryRow(ctx, confirmTacticalStrip, arg.ID, arg.SessionID, arg.ConfirmedBy)
	var i TacticalStrip
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Bay,
		&i.Label,
		&i.Aircraft,
		&i.ProducedBy,
		&i.Sequence,
		&i.TimerStart,
		&i.Confirmed,
		&i.ConfirmedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTacticalStrip = `-- name: CreateTacticalStrip :one
INSERT INTO tactical_strips (session_id, type, bay, label, aircraft, produced_by, sequence)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, session_id, type, bay, label, aircraft, produced_by, sequence, timer_start, confirmed, confirmed_by, created_at
`

type CreateTacticalStripParams struct {
	SessionID  int32
	Type       string
	Bay        string
	Label      string
	Aircraft   *string
	ProducedBy string
	Sequence   int32
}

func (q *Queries) CreateTacticalStrip(ctx context.Context, arg CreateTacticalStripParams) (TacticalStrip, error) {
	row := q.db.QueryRow(ctx, createTacticalStrip,
		arg.SessionID,
		arg.Type,
		arg.Bay,
		arg.Label,
		arg.Aircraft,
		arg.ProducedBy,
		arg.Sequence,
	)
	var i TacticalStrip
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Bay,
		&i.Label,
		&i.Aircraft,
		&i.ProducedBy,
		&i.Sequence,
		&i.TimerStart,
		&i.Confirmed,
		&i.ConfirmedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTacticalStrip = `-- name: DeleteTacticalStrip :exec
DELETE FROM tactical_strips WHERE id = $1 AND session_id = $2
`

type DeleteTacticalStripParams struct {
	ID        int64
	SessionID int32
}

func (q *Queries) DeleteTacticalStrip(ctx context.Context, arg DeleteTacticalStripParams) error {
	_, err := q.db.Exec(ctx, deleteTacticalStrip, arg.ID, arg.SessionID)
	return err
}

const getTacticalStripSequenceByID = `-- name: GetTacticalStripSequenceByID :one
SELECT sequence::INT FROM tactical_strips WHERE id = $1 AND session_id = $2
`

type GetTacticalStripSequenceByIDParams struct {
	ID        int64
	SessionID int32
}

func (q *Queries) GetTacticalStripSequenceByID(ctx context.Context, arg GetTacticalStripSequenceByIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, getTacticalStripSequenceByID, arg.ID, arg.SessionID)
	var sequence int32
	err := row.Scan(&sequence)
	return sequence, err
}

const listTacticalStripBaySequences = `-- name: ListTacticalStripBaySequences :many
SELECT id, sequence FROM tactical_strips
WHERE session_id = $1 AND bay = $2::TEXT
ORDER BY sequence, id
`

type ListTacticalStripBaySequencesParams struct {
	SessionID int32
	Bay       string
}

type ListTacticalStripBaySequencesRow struct {
	ID       int64
	Sequence int32
}

func (q *Queries) ListTacticalStripBaySequences(ctx context.Context, arg ListTacticalStripBaySequencesParams) ([]ListTacticalStripBaySequencesRow, error) {
	rows, err := q.db.Query(ctx, listTacticalStripBaySequences, arg.SessionID, arg.Bay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTacticalStripBaySequencesRow
	for rows.Next() {
		var i ListTacticalStripBaySequencesRow
		if err := rows.Scan(&i.ID, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTacticalStripsByBay = `-- name: ListTacticalStripsByBay :many
SELECT id, session_id, type, bay, label, aircraft, produced_by, sequence, timer_start, confirmed, confirmed_by, created_at FROM tactical_strips
WHERE session_id = $1 AND bay = $2
ORDER BY sequence ASC
`

type ListTacticalStripsByBayParams struct {
	SessionID int32
	Bay       string
}

func (q *Queries) ListTacticalStripsByBay(ctx context.Context, arg ListTacticalStripsByBayParams) ([]TacticalStrip, error) {
	rows, err := q.db.Query(ctx, listTacticalStripsByBay, arg.SessionID, arg.Bay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TacticalStrip
	for rows.Next() {
		var i TacticalStrip
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Bay,
			&i.Label,
			&i.Aircraft,
			&i.ProducedBy,
			&i.Sequence,
			&i.TimerStart,
			&i.Confirmed,
			&i.ConfirmedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTacticalStripsBySession = `-- name: ListTacticalStripsBySession :many
SELECT id, session_id, type, bay, label, aircraft, produced_by, sequence, timer_start, confirmed, confirmed_by, created_at FROM tactical_strips
WHERE session_id = $1
ORDER BY bay, sequence ASC
`

func (q *Queries) ListTacticalStripsBySession(ctx context.Context, sessionID int32) ([]TacticalStrip, error) {
	rows, err := q.db.Query(ctx, listTacticalStripsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TacticalStrip
	for rows.Next() {
		var i TacticalStrip
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Bay,
			&i.Label,
			&i.Aircraft,
			&i.ProducedBy,
			&i.Sequence,
			&i.TimerStart,
			&i.Confirmed,
			&i.ConfirmedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTacticalStripTimer = `-- name: StartTacticalStripTimer :one
UPDATE tactical_strips
SET timer_start = NOW()
WHERE id = $1 AND session_id = $2
RETURNING id, session_id, type, bay, label, aircraft, produced_by, sequence, timer_start, confirmed, confirmed_by, created_at
`

type StartTacticalStripTimerParams struct {
	ID        int64
	SessionID int32
}

func (q *Queries) StartTacticalStripTimer(ctx context.Context, arg StartTacticalStripTimerParams) (TacticalStrip, error) {
	row := q.db.QueryRow(ctx, startTacticalStripTimer, arg.ID, arg.SessionID)
	var i TacticalStrip
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Bay,
		&i.Label,
		&i.Aircraft,
		&i.ProducedBy,
		&i.Sequence,
		&i.TimerStart,
		&i.Confirmed,
		&i.ConfirmedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateTacticalStripSequence = `-- name: UpdateTacticalStripSequence :one
UPDATE tactical_strips
SET sequence = $3::INT
WHERE id = $1 AND session_id = $2
RETURNING id, session_id, type, bay, label, aircraft, produced_by, sequence, timer_start, confirmed, confirmed_by, created_at
`

type UpdateTacticalStripSequenceParams struct {
	ID        int64
	SessionID int32
	Sequence  int32
}

func (q *Queries) UpdateTacticalStripSequence(ctx context.Context, arg UpdateTacticalStripSequenceParams) (TacticalStrip, error) {
	row := q.db.QueryRow(ctx, updateTacticalStripSequence, arg.ID, arg.SessionID, arg.Sequence)
	var i TacticalStrip
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Bay,
		&i.Label,
		&i.Aircraft,
		&i.ProducedBy,
		&i.Sequence,
		&i.TimerStart,
		&i.Confirmed,
		&i.ConfirmedBy,
		&i.CreatedAt,
	)
	return i, err
}
