// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: versions.sql

package database

import (
	"context"
)

const getAllDatabaseVersions = `-- name: GetAllDatabaseVersions :many
SELECT id, name FROM versions
`

type GetAllDatabaseVersionsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetAllDatabaseVersions(ctx context.Context) ([]GetAllDatabaseVersionsRow, error) {
	rows, err := q.db.Query(ctx, getAllDatabaseVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDatabaseVersionsRow
	for rows.Next() {
		var i GetAllDatabaseVersionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDatabaseVersion = `-- name: InsertDatabaseVersion :exec
INSERT INTO versions (id, name)
VALUES($1, $2)
`

type InsertDatabaseVersionParams struct {
	ID   int32
	Name string
}

func (q *Queries) InsertDatabaseVersion(ctx context.Context, arg InsertDatabaseVersionParams) error {
	_, err := q.db.Exec(ctx, insertDatabaseVersion, arg.ID, arg.Name)
	return err
}
