UPDATE strips SET cleared = false WHERE cleared IS NULL;
UPDATE strips SET bay = 'UNKNOWN' WHERE bay IS NULL;
ALTER TABLE strips ALTER COLUMN cleared SET DEFAULT false;
ALTER TABLE strips ALTER COLUMN cleared SET NOT NULL;
ALTER TABLE strips ALTER COLUMN bay SET DEFAULT 'UNKNOWN';
ALTER TABLE strips ALTER COLUMN bay SET NOT NULL;
