ALTER TABLE strips ADD COLUMN IF NOT EXISTS is_manual BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE strips ADD COLUMN IF NOT EXISTS persons_on_board INTEGER;
ALTER TABLE strips ADD COLUMN IF NOT EXISTS fpl_type VARCHAR;
ALTER TABLE strips ADD COLUMN IF NOT EXISTS language VARCHAR;
