// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vatsim.Scandinavia.FlightStrips.Persistence.EfCore;

#nullable disable

namespace Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Migrations
{
    [DbContext(typeof(FlightStripsDbContext))]
    [Migration("20231021131719_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Default")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Bays");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.OnlinePositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("OnlinePositions");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.PositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.StripEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BayId")
                        .HasColumnType("int");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Cleared")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BayId");

                    b.ToTable("Strips");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayEntity", b =>
                {
                    b.OwnsMany("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayFilter", "Filters", b1 =>
                        {
                            b1.Property<string>("Callsign")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("BayEntityId")
                                .HasColumnType("int");

                            b1.HasKey("Callsign");

                            b1.HasIndex("BayEntityId");

                            b1.ToTable("BayFilter");

                            b1.WithOwner()
                                .HasForeignKey("BayEntityId");
                        });

                    b.Navigation("Filters");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.OnlinePositionEntity", b =>
                {
                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.PositionEntity", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.StripEntity", b =>
                {
                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayEntity", "Bay")
                        .WithMany()
                        .HasForeignKey("BayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bay");
                });
#pragma warning restore 612, 618
        }
    }
}
