// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vatsim.Scandinavia.FlightStrips.Persistence.EfCore;

#nullable disable

namespace Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Migrations
{
    [DbContext(typeof(FlightStripsDbContext))]
    [Migration("20231030151109_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Airport")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Default")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Name", "Airport");

                    b.ToTable("Bays");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.CoordinationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FromFrequency")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("ToFrequency")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FromFrequency", "Airport");

                    b.HasIndex("ToFrequency", "Airport");

                    b.HasIndex("Callsign", "Airport", "Session");

                    b.ToTable("Coordination");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.OnlinePositionEntity", b =>
                {
                    b.Property<string>("PositionName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Session")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Airport")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PositionFrequency")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("PositionName", "Session", "Airport");

                    b.HasIndex("PositionFrequency", "Airport");

                    b.ToTable("OnlinePositions");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.PositionEntity", b =>
                {
                    b.Property<string>("Airport")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Frequency")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Airport", "Frequency");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.StripEntity", b =>
                {
                    b.Property<string>("Callsign")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Session")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Airport")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BayName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Cleared")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionFrequency")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Callsign", "Session", "Airport");

                    b.HasIndex("BayName", "Airport");

                    b.HasIndex("PositionFrequency", "Airport");

                    b.ToTable("Strips");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayEntity", b =>
                {
                    b.OwnsMany("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayFilter", "Filters", b1 =>
                        {
                            b1.Property<string>("Callsign")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("BayEntityAirport")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("BayEntityName")
                                .IsRequired()
                                .HasColumnType("varchar(255)");

                            b1.HasKey("Callsign");

                            b1.HasIndex("BayEntityName", "BayEntityAirport");

                            b1.ToTable("BayFilter");

                            b1.WithOwner()
                                .HasForeignKey("BayEntityName", "BayEntityAirport");
                        });

                    b.Navigation("Filters");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.CoordinationEntity", b =>
                {
                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.PositionEntity", "From")
                        .WithMany()
                        .HasForeignKey("FromFrequency", "Airport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.PositionEntity", "To")
                        .WithMany()
                        .HasForeignKey("ToFrequency", "Airport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.StripEntity", "Strip")
                        .WithMany()
                        .HasForeignKey("Callsign", "Airport", "Session")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("Strip");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.OnlinePositionEntity", b =>
                {
                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.PositionEntity", "Position")
                        .WithMany()
                        .HasForeignKey("PositionFrequency", "Airport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.StripEntity", b =>
                {
                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.BayEntity", "Bay")
                        .WithMany()
                        .HasForeignKey("BayName", "Airport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.PositionEntity", "Position")
                        .WithMany()
                        .HasForeignKey("PositionFrequency", "Airport");

                    b.Navigation("Bay");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
