// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vatsim.Scandinavia.FlightStrips.Persistence.EfCore;

#nullable disable

namespace Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Migrations
{
    [DbContext(typeof(FlightStripsDbContext))]
    partial class FlightStripsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.CoordinationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Airport")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("FromFrequency")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("ToFrequency")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("Callsign", "Session", "Airport");

                    b.ToTable("Coordination");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.OnlinePositionEntity", b =>
                {
                    b.Property<string>("PositionName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Session")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Airport")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("ArrivalRunway")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("ConnectedWithUi")
                        .HasColumnType("boolean");

                    b.Property<string>("DepartureRunway")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("FromPlugin")
                        .HasColumnType("boolean");

                    b.Property<string>("PositionFrequency")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("Sector")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("PositionName", "Session", "Airport");

                    b.ToTable("OnlinePositions");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.RunwayConfigurationEntity", b =>
                {
                    b.Property<string>("Session")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Airport")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Arrival")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Session", "Airport");

                    b.ToTable("RunwayConfigs");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.StripEntity", b =>
                {
                    b.Property<string>("Callsign")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Session")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Airport")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("AOBT")
                        .HasColumnType("text");

                    b.Property<string>("ASAT")
                        .HasColumnType("text");

                    b.Property<int>("AircraftCategory")
                        .HasColumnType("integer");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Alternate")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("AssignedSquawk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CTOT")
                        .HasColumnType("text");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Cleared")
                        .HasColumnType("boolean");

                    b.Property<int>("ClearedAltitude")
                        .HasColumnType("integer");

                    b.Property<int>("CommunicationType")
                        .HasColumnType("integer");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("FinalAltitude")
                        .HasColumnType("integer");

                    b.Property<int?>("Heading")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("PositionFrequency")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Runway")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Squawk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TOBT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TSAT")
                        .HasColumnType("text");

                    b.Property<string>("TTOT")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Callsign", "Session", "Airport");

                    b.ToTable("Strips");
                });

            modelBuilder.Entity("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.CoordinationEntity", b =>
                {
                    b.HasOne("Vatsim.Scandinavia.FlightStrips.Persistence.EfCore.Entities.StripEntity", "Strip")
                        .WithMany()
                        .HasForeignKey("Callsign", "Session", "Airport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strip");
                });
#pragma warning restore 612, 618
        }
    }
}
