// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForBulkInsertControllers implements pgx.CopyFromSource.
type iteratorForBulkInsertControllers struct {
	rows                 []BulkInsertControllersParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertControllers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertControllers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Callsign,
		r.rows[0].Session,
		r.rows[0].Position,
	}, nil
}

func (r iteratorForBulkInsertControllers) Err() error {
	return nil
}

func (q *Queries) BulkInsertControllers(ctx context.Context, arg []BulkInsertControllersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"controllers"}, []string{"callsign", "session", "position"}, &iteratorForBulkInsertControllers{rows: arg})
}
