// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkInsertControllersParams struct {
	Callsign string
	Session  int32
	Position string
}

const createCoordination = `-- name: CreateCoordination :one
INSERT INTO coordinations (session, strip_id, from_position, to_position)
VALUES ($1, $2, $3, $4) RETURNING id, session, strip_id, from_position, to_position, coordinated_at
`

type CreateCoordinationParams struct {
	Session      int32
	StripID      int32
	FromPosition string
	ToPosition   string
}

func (q *Queries) CreateCoordination(ctx context.Context, arg CreateCoordinationParams) (Coordination, error) {
	row := q.db.QueryRow(ctx, createCoordination,
		arg.Session,
		arg.StripID,
		arg.FromPosition,
		arg.ToPosition,
	)
	var i Coordination
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.StripID,
		&i.FromPosition,
		&i.ToPosition,
		&i.CoordinatedAt,
	)
	return i, err
}

const deleteCoordinationByID = `-- name: DeleteCoordinationByID :execrows
DELETE
FROM coordinations
WHERE id = $1
`

func (q *Queries) DeleteCoordinationByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCoordinationByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE
FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getController = `-- name: GetController :one
SELECT id, session, callsign, position, cid, last_seen_euroscope, last_seen_frontend
FROM controllers
WHERE callsign = $1 AND session = $2
`

type GetControllerParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) GetController(ctx context.Context, arg GetControllerParams) (Controller, error) {
	row := q.db.QueryRow(ctx, getController, arg.Callsign, arg.Session)
	var i Controller
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Callsign,
		&i.Position,
		&i.Cid,
		&i.LastSeenEuroscope,
		&i.LastSeenFrontend,
	)
	return i, err
}

const getControllerByCid = `-- name: GetControllerByCid :one
SELECT id, session, callsign, position, cid, last_seen_euroscope, last_seen_frontend
FROM controllers
WHERE cid = $1::text LIMIT 1
`

func (q *Queries) GetControllerByCid(ctx context.Context, cid string) (Controller, error) {
	row := q.db.QueryRow(ctx, getControllerByCid, cid)
	var i Controller
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.Callsign,
		&i.Position,
		&i.Cid,
		&i.LastSeenEuroscope,
		&i.LastSeenFrontend,
	)
	return i, err
}

const getCoordinationByStripCallsign = `-- name: GetCoordinationByStripCallsign :one
SELECT c.id, c.session, c.strip_id, c.from_position, c.to_position, c.coordinated_at
FROM coordinations c
         JOIN strips s ON s.id = c.strip_id
WHERE s.session = $1
  AND s.callsign = $2
`

type GetCoordinationByStripCallsignParams struct {
	Session  int32
	Callsign string
}

func (q *Queries) GetCoordinationByStripCallsign(ctx context.Context, arg GetCoordinationByStripCallsignParams) (Coordination, error) {
	row := q.db.QueryRow(ctx, getCoordinationByStripCallsign, arg.Session, arg.Callsign)
	var i Coordination
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.StripID,
		&i.FromPosition,
		&i.ToPosition,
		&i.CoordinatedAt,
	)
	return i, err
}

const getCoordinationByStripID = `-- name: GetCoordinationByStripID :one
SELECT id, session, strip_id, from_position, to_position, coordinated_at
FROM coordinations
WHERE session = $1 AND strip_id = $2
`

type GetCoordinationByStripIDParams struct {
	Session int32
	StripID int32
}

func (q *Queries) GetCoordinationByStripID(ctx context.Context, arg GetCoordinationByStripIDParams) (Coordination, error) {
	row := q.db.QueryRow(ctx, getCoordinationByStripID, arg.Session, arg.StripID)
	var i Coordination
	err := row.Scan(
		&i.ID,
		&i.Session,
		&i.StripID,
		&i.FromPosition,
		&i.ToPosition,
		&i.CoordinatedAt,
	)
	return i, err
}

const getExpiredSessions = `-- name: GetExpiredSessions :many
SELECT id
FROM sessions
WHERE NOT EXISTS (SELECT 1 FROM controllers WHERE last_seen_euroscope > $1)
`

func (q *Queries) GetExpiredSessions(ctx context.Context, expiredTime pgtype.Timestamp) ([]int32, error) {
	rows, err := q.db.Query(ctx, getExpiredSessions, expiredTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, name, airport
FROM sessions
WHERE airport = $1
  AND name = $2
`

type GetSessionParams struct {
	Airport string
	Name    string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.Airport, arg.Name)
	var i Session
	err := row.Scan(&i.ID, &i.Name, &i.Airport)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, name, airport
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionById, id)
	var i Session
	err := row.Scan(&i.ID, &i.Name, &i.Airport)
	return i, err
}

const getStrip = `-- name: GetStrip :one
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat, eobt
FROM strips
WHERE callsign = $1 AND session = $2
`

type GetStripParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) GetStrip(ctx context.Context, arg GetStripParams) (Strip, error) {
	row := q.db.QueryRow(ctx, getStrip, arg.Callsign, arg.Session)
	var i Strip
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Callsign,
		&i.Session,
		&i.Origin,
		&i.Destination,
		&i.Alternative,
		&i.Route,
		&i.Remarks,
		&i.AssignedSquawk,
		&i.Squawk,
		&i.Sid,
		&i.ClearedAltitude,
		&i.Heading,
		&i.AircraftType,
		&i.Runway,
		&i.RequestedAltitude,
		&i.Capabilities,
		&i.CommunicationType,
		&i.AircraftCategory,
		&i.Stand,
		&i.Sequence,
		&i.State,
		&i.Cleared,
		&i.Owner,
		&i.Bay,
		&i.PositionLatitude,
		&i.PositionLongitude,
		&i.PositionAltitude,
		&i.Tobt,
		&i.Tsat,
		&i.Ttot,
		&i.Ctot,
		&i.Aobt,
		&i.Asat,
		&i.Eobt,
	)
	return i, err
}

const insertAirport = `-- name: InsertAirport :exec
INSERT INTO airports (name)
VALUES ($1)
`

func (q *Queries) InsertAirport(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertAirport, name)
	return err
}

const insertController = `-- name: InsertController :exec
INSERT INTO controllers (callsign, session, position, cid, last_seen_euroscope, last_seen_frontend)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertControllerParams struct {
	Callsign          string
	Session           int32
	Position          string
	Cid               pgtype.Text
	LastSeenEuroscope pgtype.Timestamp
	LastSeenFrontend  pgtype.Timestamp
}

func (q *Queries) InsertController(ctx context.Context, arg InsertControllerParams) error {
	_, err := q.db.Exec(ctx, insertController,
		arg.Callsign,
		arg.Session,
		arg.Position,
		arg.Cid,
		arg.LastSeenEuroscope,
		arg.LastSeenFrontend,
	)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (name, airport)
VALUES ($1, $2) RETURNING id
`

type InsertSessionParams struct {
	Name    string
	Airport string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertSession, arg.Name, arg.Airport)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertStrip = `-- name: InsertStrip :exec
INSERT INTO strips (version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk,
                    squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities,
                    communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay,
                    position_latitude, position_longitude, position_altitude, tobt, eobt)
VALUES (1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23,
        $24, $25, $26, $27, $28, $29)
`

type InsertStripParams struct {
	Callsign          string
	Session           int32
	Origin            string
	Destination       string
	Alternative       pgtype.Text
	Route             pgtype.Text
	Remarks           pgtype.Text
	AssignedSquawk    pgtype.Text
	Squawk            pgtype.Text
	Sid               pgtype.Text
	ClearedAltitude   pgtype.Int4
	Heading           pgtype.Int4
	AircraftType      pgtype.Text
	Runway            pgtype.Text
	RequestedAltitude pgtype.Int4
	Capabilities      pgtype.Text
	CommunicationType pgtype.Text
	AircraftCategory  pgtype.Text
	Stand             pgtype.Text
	Sequence          pgtype.Int4
	State             pgtype.Text
	Cleared           pgtype.Bool
	Owner             pgtype.Text
	Bay               pgtype.Text
	PositionLatitude  pgtype.Float8
	PositionLongitude pgtype.Float8
	PositionAltitude  pgtype.Int4
	Tobt              pgtype.Text
	Eobt              pgtype.Text
}

func (q *Queries) InsertStrip(ctx context.Context, arg InsertStripParams) error {
	_, err := q.db.Exec(ctx, insertStrip,
		arg.Callsign,
		arg.Session,
		arg.Origin,
		arg.Destination,
		arg.Alternative,
		arg.Route,
		arg.Remarks,
		arg.AssignedSquawk,
		arg.Squawk,
		arg.Sid,
		arg.ClearedAltitude,
		arg.Heading,
		arg.AircraftType,
		arg.Runway,
		arg.RequestedAltitude,
		arg.Capabilities,
		arg.CommunicationType,
		arg.AircraftCategory,
		arg.Stand,
		arg.Sequence,
		arg.State,
		arg.Cleared,
		arg.Owner,
		arg.Bay,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Tobt,
		arg.Eobt,
	)
	return err
}

const listControllers = `-- name: ListControllers :many
SELECT id, session, callsign, position, cid, last_seen_euroscope, last_seen_frontend
FROM controllers
WHERE session = $1
ORDER BY callsign
`

func (q *Queries) ListControllers(ctx context.Context, session int32) ([]Controller, error) {
	rows, err := q.db.Query(ctx, listControllers, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Controller
	for rows.Next() {
		var i Controller
		if err := rows.Scan(
			&i.ID,
			&i.Session,
			&i.Callsign,
			&i.Position,
			&i.Cid,
			&i.LastSeenEuroscope,
			&i.LastSeenFrontend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoordinationsBySession = `-- name: ListCoordinationsBySession :many
SELECT id, session, strip_id, from_position, to_position, coordinated_at
FROM coordinations
WHERE session = $1
ORDER BY coordinated_at DESC
`

func (q *Queries) ListCoordinationsBySession(ctx context.Context, session int32) ([]Coordination, error) {
	rows, err := q.db.Query(ctx, listCoordinationsBySession, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coordination
	for rows.Next() {
		var i Coordination
		if err := rows.Scan(
			&i.ID,
			&i.Session,
			&i.StripID,
			&i.FromPosition,
			&i.ToPosition,
			&i.CoordinatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByAirport = `-- name: ListSessionsByAirport :many
SELECT id, name, airport
FROM sessions
WHERE airport = $1
`

func (q *Queries) ListSessionsByAirport(ctx context.Context, airport string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAirport, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(&i.ID, &i.Name, &i.Airport); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrips = `-- name: ListStrips :many
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat, eobt
FROM strips
WHERE session = $1
ORDER BY callsign
`

func (q *Queries) ListStrips(ctx context.Context, session int32) ([]Strip, error) {
	rows, err := q.db.Query(ctx, listStrips, session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strip
	for rows.Next() {
		var i Strip
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Callsign,
			&i.Session,
			&i.Origin,
			&i.Destination,
			&i.Alternative,
			&i.Route,
			&i.Remarks,
			&i.AssignedSquawk,
			&i.Squawk,
			&i.Sid,
			&i.ClearedAltitude,
			&i.Heading,
			&i.AircraftType,
			&i.Runway,
			&i.RequestedAltitude,
			&i.Capabilities,
			&i.CommunicationType,
			&i.AircraftCategory,
			&i.Stand,
			&i.Sequence,
			&i.State,
			&i.Cleared,
			&i.Owner,
			&i.Bay,
			&i.PositionLatitude,
			&i.PositionLongitude,
			&i.PositionAltitude,
			&i.Tobt,
			&i.Tsat,
			&i.Ttot,
			&i.Ctot,
			&i.Aobt,
			&i.Asat,
			&i.Eobt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStripsByOrigin = `-- name: ListStripsByOrigin :many
SELECT id, version, callsign, session, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, tsat, ttot, ctot, aobt, asat, eobt
FROM strips
WHERE origin = $1 AND session = $2
ORDER BY callsign
`

type ListStripsByOriginParams struct {
	Origin  string
	Session int32
}

func (q *Queries) ListStripsByOrigin(ctx context.Context, arg ListStripsByOriginParams) ([]Strip, error) {
	rows, err := q.db.Query(ctx, listStripsByOrigin, arg.Origin, arg.Session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Strip
	for rows.Next() {
		var i Strip
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Callsign,
			&i.Session,
			&i.Origin,
			&i.Destination,
			&i.Alternative,
			&i.Route,
			&i.Remarks,
			&i.AssignedSquawk,
			&i.Squawk,
			&i.Sid,
			&i.ClearedAltitude,
			&i.Heading,
			&i.AircraftType,
			&i.Runway,
			&i.RequestedAltitude,
			&i.Capabilities,
			&i.CommunicationType,
			&i.AircraftCategory,
			&i.Stand,
			&i.Sequence,
			&i.State,
			&i.Cleared,
			&i.Owner,
			&i.Bay,
			&i.PositionLatitude,
			&i.PositionLongitude,
			&i.PositionAltitude,
			&i.Tobt,
			&i.Tsat,
			&i.Ttot,
			&i.Ctot,
			&i.Aobt,
			&i.Asat,
			&i.Eobt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeController = `-- name: RemoveController :execrows
DELETE
FROM controllers
WHERE callsign = $1 AND session = $2
`

type RemoveControllerParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) RemoveController(ctx context.Context, arg RemoveControllerParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeController, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeStripByID = `-- name: RemoveStripByID :exec
DELETE
FROM strips
WHERE callsign = $1 AND session = $2
`

type RemoveStripByIDParams struct {
	Callsign string
	Session  int32
}

func (q *Queries) RemoveStripByID(ctx context.Context, arg RemoveStripByIDParams) error {
	_, err := q.db.Exec(ctx, removeStripByID, arg.Callsign, arg.Session)
	return err
}

const setControllerCid = `-- name: SetControllerCid :execrows
UPDATE controllers
SET cid = $1
WHERE callsign = $2 AND session = $3
`

type SetControllerCidParams struct {
	Cid      pgtype.Text
	Callsign string
	Session  int32
}

func (q *Queries) SetControllerCid(ctx context.Context, arg SetControllerCidParams) (int64, error) {
	result, err := q.db.Exec(ctx, setControllerCid, arg.Cid, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setControllerEuroscopeSeen = `-- name: SetControllerEuroscopeSeen :execrows
UPDATE controllers
SET last_seen_euroscope = $1
WHERE cid = $3::text AND session = $2
`

type SetControllerEuroscopeSeenParams struct {
	LastSeenEuroscope pgtype.Timestamp
	Session           int32
	Cid               string
}

func (q *Queries) SetControllerEuroscopeSeen(ctx context.Context, arg SetControllerEuroscopeSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setControllerEuroscopeSeen, arg.LastSeenEuroscope, arg.Session, arg.Cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setControllerFrontendSeen = `-- name: SetControllerFrontendSeen :execrows
UPDATE controllers
SET last_seen_frontend = $1
WHERE cid = $3::text AND session = $2
`

type SetControllerFrontendSeenParams struct {
	LastSeenFrontend pgtype.Timestamp
	Session          int32
	Cid              string
}

func (q *Queries) SetControllerFrontendSeen(ctx context.Context, arg SetControllerFrontendSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setControllerFrontendSeen, arg.LastSeenFrontend, arg.Session, arg.Cid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setControllerPosition = `-- name: SetControllerPosition :execrows
UPDATE controllers
SET position = $1
WHERE callsign = $2 AND session = $3
`

type SetControllerPositionParams struct {
	Position string
	Callsign string
	Session  int32
}

func (q *Queries) SetControllerPosition(ctx context.Context, arg SetControllerPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setControllerPosition, arg.Position, arg.Callsign, arg.Session)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStripOwner = `-- name: SetStripOwner :execrows
UPDATE strips
SET owner   = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND version = $4
`

type SetStripOwnerParams struct {
	Owner    pgtype.Text
	Callsign string
	Session  int32
	Version  int32
}

func (q *Queries) SetStripOwner(ctx context.Context, arg SetStripOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStripOwner,
		arg.Owner,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStrip = `-- name: UpdateStrip :execrows
UPDATE strips
SET (version, origin, destination, alternative, route, remarks, assigned_squawk, squawk, sid, cleared_altitude, heading, aircraft_type, runway, requested_altitude, capabilities, communication_type, aircraft_category, stand, sequence, state, cleared, owner, bay, position_latitude, position_longitude, position_altitude, tobt, eobt
        ) = (
             version + 1, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22,
             $23, $24, $25, $26, $27, $28, $29)
WHERE callsign = $1 AND session = $2
`

type UpdateStripParams struct {
	Callsign          string
	Session           int32
	Origin            string
	Destination       string
	Alternative       pgtype.Text
	Route             pgtype.Text
	Remarks           pgtype.Text
	AssignedSquawk    pgtype.Text
	Squawk            pgtype.Text
	Sid               pgtype.Text
	ClearedAltitude   pgtype.Int4
	Heading           pgtype.Int4
	AircraftType      pgtype.Text
	Runway            pgtype.Text
	RequestedAltitude pgtype.Int4
	Capabilities      pgtype.Text
	CommunicationType pgtype.Text
	AircraftCategory  pgtype.Text
	Stand             pgtype.Text
	Sequence          pgtype.Int4
	State             pgtype.Text
	Cleared           pgtype.Bool
	Owner             pgtype.Text
	Bay               pgtype.Text
	PositionLatitude  pgtype.Float8
	PositionLongitude pgtype.Float8
	PositionAltitude  pgtype.Int4
	Tobt              pgtype.Text
	Eobt              pgtype.Text
}

func (q *Queries) UpdateStrip(ctx context.Context, arg UpdateStripParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStrip,
		arg.Callsign,
		arg.Session,
		arg.Origin,
		arg.Destination,
		arg.Alternative,
		arg.Route,
		arg.Remarks,
		arg.AssignedSquawk,
		arg.Squawk,
		arg.Sid,
		arg.ClearedAltitude,
		arg.Heading,
		arg.AircraftType,
		arg.Runway,
		arg.RequestedAltitude,
		arg.Capabilities,
		arg.CommunicationType,
		arg.AircraftCategory,
		arg.Stand,
		arg.Sequence,
		arg.State,
		arg.Cleared,
		arg.Owner,
		arg.Bay,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Tobt,
		arg.Eobt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripAircraftPositionByID = `-- name: UpdateStripAircraftPositionByID :execrows
UPDATE strips
SET position_latitude  = $1,
    position_longitude = $2,
    position_altitude  = $3,
    bay                = $4
WHERE callsign = $5 AND session = $6 AND (version = $7 OR $7 IS NULL)
`

type UpdateStripAircraftPositionByIDParams struct {
	PositionLatitude  pgtype.Float8
	PositionLongitude pgtype.Float8
	PositionAltitude  pgtype.Int4
	Bay               pgtype.Text
	Callsign          string
	Session           int32
	Version           pgtype.Int4
}

func (q *Queries) UpdateStripAircraftPositionByID(ctx context.Context, arg UpdateStripAircraftPositionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripAircraftPositionByID,
		arg.PositionLatitude,
		arg.PositionLongitude,
		arg.PositionAltitude,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripAssignedSquawkByID = `-- name: UpdateStripAssignedSquawkByID :execrows
UPDATE strips
SET assigned_squawk = $1,
    version         = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripAssignedSquawkByIDParams struct {
	AssignedSquawk pgtype.Text
	Callsign       string
	Session        int32
	Version        pgtype.Int4
}

func (q *Queries) UpdateStripAssignedSquawkByID(ctx context.Context, arg UpdateStripAssignedSquawkByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripAssignedSquawkByID,
		arg.AssignedSquawk,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripClearedAltitudeByID = `-- name: UpdateStripClearedAltitudeByID :execrows
UPDATE strips
SET cleared_altitude = $1,
    version          = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripClearedAltitudeByIDParams struct {
	ClearedAltitude pgtype.Int4
	Callsign        string
	Session         int32
	Version         pgtype.Int4
}

func (q *Queries) UpdateStripClearedAltitudeByID(ctx context.Context, arg UpdateStripClearedAltitudeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripClearedAltitudeByID,
		arg.ClearedAltitude,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripClearedFlagByID = `-- name: UpdateStripClearedFlagByID :execrows
UPDATE strips
SET cleared = $1,
    bay     = $2,
    version = version + 1
WHERE callsign = $3 AND session = $4 AND (version = $5 OR $5 IS NULL)
`

type UpdateStripClearedFlagByIDParams struct {
	Cleared  pgtype.Bool
	Bay      pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripClearedFlagByID(ctx context.Context, arg UpdateStripClearedFlagByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripClearedFlagByID,
		arg.Cleared,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripCommunicationTypeByID = `-- name: UpdateStripCommunicationTypeByID :execrows
UPDATE strips
SET communication_type = $1,
    version            = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripCommunicationTypeByIDParams struct {
	CommunicationType pgtype.Text
	Callsign          string
	Session           int32
	Version           pgtype.Int4
}

func (q *Queries) UpdateStripCommunicationTypeByID(ctx context.Context, arg UpdateStripCommunicationTypeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripCommunicationTypeByID,
		arg.CommunicationType,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripGroundStateByID = `-- name: UpdateStripGroundStateByID :execrows
UPDATE strips
SET state   = $1,
    bay     = $2,
    version = version + 1
WHERE callsign = $3 AND session = $4 AND (version = $5 OR $5 IS NULL)
`

type UpdateStripGroundStateByIDParams struct {
	State    pgtype.Text
	Bay      pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripGroundStateByID(ctx context.Context, arg UpdateStripGroundStateByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripGroundStateByID,
		arg.State,
		arg.Bay,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripHeadingByID = `-- name: UpdateStripHeadingByID :execrows
UPDATE strips
SET heading = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripHeadingByIDParams struct {
	Heading  pgtype.Int4
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripHeadingByID(ctx context.Context, arg UpdateStripHeadingByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripHeadingByID,
		arg.Heading,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripRequestedAltitudeByID = `-- name: UpdateStripRequestedAltitudeByID :execrows
UPDATE strips
SET requested_altitude = $1,
    version            = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripRequestedAltitudeByIDParams struct {
	RequestedAltitude pgtype.Int4
	Callsign          string
	Session           int32
	Version           pgtype.Int4
}

func (q *Queries) UpdateStripRequestedAltitudeByID(ctx context.Context, arg UpdateStripRequestedAltitudeByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripRequestedAltitudeByID,
		arg.RequestedAltitude,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripSquawkByID = `-- name: UpdateStripSquawkByID :execrows
UPDATE strips
SET squawk  = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripSquawkByIDParams struct {
	Squawk   pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripSquawkByID(ctx context.Context, arg UpdateStripSquawkByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripSquawkByID,
		arg.Squawk,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStripStandByID = `-- name: UpdateStripStandByID :execrows
UPDATE strips
SET stand   = $1,
    version = version + 1
WHERE callsign = $2 AND session = $3 AND (version = $4 OR $4 IS NULL)
`

type UpdateStripStandByIDParams struct {
	Stand    pgtype.Text
	Callsign string
	Session  int32
	Version  pgtype.Int4
}

func (q *Queries) UpdateStripStandByID(ctx context.Context, arg UpdateStripStandByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStripStandByID,
		arg.Stand,
		arg.Callsign,
		arg.Session,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
