// Code generated by generate.go; DO NOT EDIT.
package amancandidate

import (
	"FlightStrips/internal/aman"
	"FlightStrips/internal/aman/navdata"
	pb "FlightStrips/pkg/events/cluster"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"time"
)

func encodeAmanFlight(v *aman.AMANFlight) *pb.AmanFlight {
	if v == nil {
		return nil
	}
	r := &pb.AmanFlight{}
	r.Callsign = string(v.Callsign)
	r.State = string(v.State)
	r.SequenceDisposition = string(v.SequenceDisposition)
	r.DataStatus = string(v.DataStatus)
	r.Prediction = encodeAmanPrediction(v.Prediction)
	if v.RawTETASamples != nil {
		r.RawTetaSamples = make([]*pb.AmanRawTetaSample, len(v.RawTETASamples))
		for i := range v.RawTETASamples {
			r.RawTetaSamples[i] = encodeAmanRawTetaSample(&v.RawTETASamples[i])
		}
	}
	r.ArrivalBaseline = encodeAmanBaseline(v.ArrivalBaseline)
	r.LatestObservation = encodeAmanFlightObservation(v.LatestObservation)
	r.SelectedRunwayGroup = optionalString[string](v.SelectedRunwayGroup)
	r.SelectedStarFamily = optionalString[string](v.SelectedSTARFamily)
	r.SelectedFeederFix = optionalString[string](v.SelectedFeederFix)
	r.SelectedHolding = optionalString[string](v.SelectedHolding)
	r.FeederEta = encodeAmanFeederEta(v.FeederETA)
	r.DerivedFeederEta = encodeAmanFeederEta(v.DerivedFeederETA)
	r.HoldingClearance = encodeAmanHoldingClearance(v.HoldingClearance)
	r.HoldingStack = encodeAmanHoldingStack(v.HoldingStack)
	r.ActiveRouteFact = encodeAmanRouteFact(v.ActiveRouteFact)
	r.ActiveRouteKey = optionalString[string](v.ActiveRouteKey)
	r.ActiveRouteDatasetId = optionalString[string](v.ActiveRouteDatasetID)
	r.RouteProgress = encodeAmanRouteProgress(v.RouteProgress)
	r.TmaEntry = encodeAmanTmaEntry(v.TMAEntry)
	r.ManualSequenceIncluded = bool(v.ManualSequenceIncluded)
	r.FreezeReason = string(v.FreezeReason)
	r.FrozenAt = optionalTimestamp(v.FrozenAt)
	r.FrozenOperationalTeta = optionalTimestamp(v.FrozenOperationalTETA)
	r.FrozenSlot = encodeAmanSlot(v.FrozenSlot)
	r.Slot = encodeAmanSlot(v.Slot)
	r.Order = optionalNumber[int32](v.Order)
	r.ManualOrder = optionalNumber[int32](v.ManualOrder)
	if v.QueueOffers != nil {
		r.QueueOffers = make([]*pb.AmanQueueOffer, len(v.QueueOffers))
		for i := range v.QueueOffers {
			r.QueueOffers[i] = encodeAmanQueueOffer(&v.QueueOffers[i])
		}
	}
	r.EtaReview = encodeAmanETAReview(v.ETAReview)
	r.OperationalException = encodeAmanOperationalException(v.OperationalException)
	r.GapException = encodeAmanGapException(v.RunwayGapException)
	r.GoAroundDetection = encodeAmanGoAroundDetection(v.GoAroundDetection)
	r.GoAroundConfirmation = encodeAmanGoAroundConfirmation(v.GoAroundConfirmation)
	r.Lifecycle = encodeAmanLifecycle(v.Lifecycle)
	r.UpdatedAt = timestamp(v.UpdatedAt)
	r.SelectedFeeder = optionalString[string](v.SelectedFeeder)
	return r
}
func decodeAmanFlight(v *pb.AmanFlight) *aman.AMANFlight {
	if v == nil {
		return nil
	}
	r := &aman.AMANFlight{}
	r.Callsign = string(v.Callsign)
	r.State = aman.FlightState(v.State)
	r.SequenceDisposition = aman.SequenceDisposition(v.SequenceDisposition)
	r.DataStatus = aman.DataStatus(v.DataStatus)
	r.Prediction = decodeAmanPrediction(v.Prediction)
	if v.RawTetaSamples != nil {
		r.RawTETASamples = make([]aman.RawTETASample, len(v.RawTetaSamples))
		for i := range v.RawTetaSamples {
			r.RawTETASamples[i] = *decodeAmanRawTetaSample(v.RawTetaSamples[i])
		}
	}
	r.ArrivalBaseline = decodeAmanBaseline(v.ArrivalBaseline)
	r.LatestObservation = decodeAmanFlightObservation(v.LatestObservation)
	r.SelectedRunwayGroup = optionalString[aman.RunwayGroupID](v.SelectedRunwayGroup)
	r.SelectedSTARFamily = optionalString[string](v.SelectedStarFamily)
	r.SelectedFeederFix = optionalString[string](v.SelectedFeederFix)
	r.SelectedHolding = optionalString[string](v.SelectedHolding)
	r.FeederETA = decodeAmanFeederEta(v.FeederEta)
	r.DerivedFeederETA = decodeAmanFeederEta(v.DerivedFeederEta)
	r.HoldingClearance = decodeAmanHoldingClearance(v.HoldingClearance)
	r.HoldingStack = decodeAmanHoldingStack(v.HoldingStack)
	r.ActiveRouteFact = decodeAmanRouteFact(v.ActiveRouteFact)
	r.ActiveRouteKey = optionalString[string](v.ActiveRouteKey)
	r.ActiveRouteDatasetID = optionalString[string](v.ActiveRouteDatasetId)
	r.RouteProgress = decodeAmanRouteProgress(v.RouteProgress)
	r.TMAEntry = decodeAmanTmaEntry(v.TmaEntry)
	r.ManualSequenceIncluded = bool(v.ManualSequenceIncluded)
	r.FreezeReason = aman.FreezeReason(v.FreezeReason)
	r.FrozenAt = optionalInstant(v.FrozenAt)
	r.FrozenOperationalTETA = optionalInstant(v.FrozenOperationalTeta)
	r.FrozenSlot = decodeAmanSlot(v.FrozenSlot)
	r.Slot = decodeAmanSlot(v.Slot)
	r.Order = optionalNumber[int](v.Order)
	r.ManualOrder = optionalNumber[int](v.ManualOrder)
	if v.QueueOffers != nil {
		r.QueueOffers = make([]aman.QueueOffer, len(v.QueueOffers))
		for i := range v.QueueOffers {
			r.QueueOffers[i] = *decodeAmanQueueOffer(v.QueueOffers[i])
		}
	}
	r.ETAReview = decodeAmanETAReview(v.EtaReview)
	r.OperationalException = decodeAmanOperationalException(v.OperationalException)
	r.RunwayGapException = decodeAmanGapException(v.GapException)
	r.GoAroundDetection = decodeAmanGoAroundDetection(v.GoAroundDetection)
	r.GoAroundConfirmation = decodeAmanGoAroundConfirmation(v.GoAroundConfirmation)
	r.Lifecycle = decodeAmanLifecycle(v.Lifecycle)
	r.UpdatedAt = instant(v.UpdatedAt)
	r.SelectedFeeder = optionalString[string](v.SelectedFeeder)
	return r
}
func encodeAmanRunwayGroup(v *aman.RunwayGroupPolicy) *pb.AmanRunwayGroup {
	if v == nil {
		return nil
	}
	r := &pb.AmanRunwayGroup{}
	r.Id = string(v.ID)
	r.Selected = bool(v.Selected)
	r.ActiveRatePerHour = uint32(v.ActiveRatePerHour)
	r.RateEffectiveAt = optionalTimestamp(v.RateEffectiveAt)
	if v.Gaps != nil {
		r.Gaps = make([]*pb.AmanGap, len(v.Gaps))
		for i := range v.Gaps {
			r.Gaps[i] = encodeAmanGap(&v.Gaps[i])
		}
	}
	if v.Closures != nil {
		r.Closures = make([]*pb.AmanClosure, len(v.Closures))
		for i := range v.Closures {
			r.Closures[i] = encodeAmanClosure(&v.Closures[i])
		}
	}
	if v.CapacityReservations != nil {
		r.Reservations = make([]*pb.AmanReservation, len(v.CapacityReservations))
		for i := range v.CapacityReservations {
			r.Reservations[i] = encodeAmanReservation(&v.CapacityReservations[i])
		}
	}
	r.Active = bool(v.Active)
	if v.SelectionSchedule != nil {
		r.SelectionSchedule = make([]*pb.AmanRunwaySelectionPoint, len(v.SelectionSchedule))
		for i := range v.SelectionSchedule {
			r.SelectionSchedule[i] = encodeAmanRunwaySelectionPoint(&v.SelectionSchedule[i])
		}
	}
	r.SelectionConflict = optionalString[string](v.SelectionConflict)
	if v.RateSchedule != nil {
		r.RateSchedule = make([]*pb.AmanRunwayRatePoint, len(v.RateSchedule))
		for i := range v.RateSchedule {
			r.RateSchedule[i] = encodeAmanRunwayRatePoint(&v.RateSchedule[i])
		}
	}
	r.SameStarSpacing = encodeAmanSameStarSpacing(v.SameSTARSpacing)
	if v.SequenceWarnings != nil {
		r.SequenceWarnings = make([]*pb.AmanSequenceWarning, len(v.SequenceWarnings))
		for i := range v.SequenceWarnings {
			r.SequenceWarnings[i] = encodeAmanSequenceWarning(&v.SequenceWarnings[i])
		}
	}
	return r
}
func decodeAmanRunwayGroup(v *pb.AmanRunwayGroup) *aman.RunwayGroupPolicy {
	if v == nil {
		return nil
	}
	r := &aman.RunwayGroupPolicy{}
	r.ID = aman.RunwayGroupID(v.Id)
	r.Selected = bool(v.Selected)
	r.ActiveRatePerHour = uint32(v.ActiveRatePerHour)
	r.RateEffectiveAt = optionalInstant(v.RateEffectiveAt)
	if v.Gaps != nil {
		r.Gaps = make([]aman.RunwayGap, len(v.Gaps))
		for i := range v.Gaps {
			r.Gaps[i] = *decodeAmanGap(v.Gaps[i])
		}
	}
	if v.Closures != nil {
		r.Closures = make([]aman.RunwayClosure, len(v.Closures))
		for i := range v.Closures {
			r.Closures[i] = *decodeAmanClosure(v.Closures[i])
		}
	}
	if v.Reservations != nil {
		r.CapacityReservations = make([]aman.RunwayCapacityReservation, len(v.Reservations))
		for i := range v.Reservations {
			r.CapacityReservations[i] = *decodeAmanReservation(v.Reservations[i])
		}
	}
	r.Active = bool(v.Active)
	if v.SelectionSchedule != nil {
		r.SelectionSchedule = make([]aman.RunwayGroupSelectionPoint, len(v.SelectionSchedule))
		for i := range v.SelectionSchedule {
			r.SelectionSchedule[i] = *decodeAmanRunwaySelectionPoint(v.SelectionSchedule[i])
		}
	}
	r.SelectionConflict = optionalString[string](v.SelectionConflict)
	if v.RateSchedule != nil {
		r.RateSchedule = make([]aman.RunwayGroupRatePoint, len(v.RateSchedule))
		for i := range v.RateSchedule {
			r.RateSchedule[i] = *decodeAmanRunwayRatePoint(v.RateSchedule[i])
		}
	}
	r.SameSTARSpacing = decodeAmanSameStarSpacing(v.SameStarSpacing)
	if v.SequenceWarnings != nil {
		r.SequenceWarnings = make([]aman.RunwayGroupSequenceWarning, len(v.SequenceWarnings))
		for i := range v.SequenceWarnings {
			r.SequenceWarnings[i] = *decodeAmanSequenceWarning(v.SequenceWarnings[i])
		}
	}
	return r
}
func encodeAmanRunwaySelectionPoint(v *aman.RunwayGroupSelectionPoint) *pb.AmanRunwaySelectionPoint {
	if v == nil {
		return nil
	}
	r := &pb.AmanRunwaySelectionPoint{}
	r.EffectiveAt = timestamp(v.EffectiveAt)
	r.CommandRevision = uint64(v.CommandRevision)
	r.Source = string(v.Source)
	return r
}
func decodeAmanRunwaySelectionPoint(v *pb.AmanRunwaySelectionPoint) *aman.RunwayGroupSelectionPoint {
	if v == nil {
		return nil
	}
	r := &aman.RunwayGroupSelectionPoint{}
	r.EffectiveAt = instant(v.EffectiveAt)
	r.CommandRevision = aman.SequenceRevision(v.CommandRevision)
	r.Source = aman.RunwayGroupSelectionSource(v.Source)
	return r
}
func encodeAmanRunwayRatePoint(v *aman.RunwayGroupRatePoint) *pb.AmanRunwayRatePoint {
	if v == nil {
		return nil
	}
	r := &pb.AmanRunwayRatePoint{}
	r.EffectiveAt = timestamp(v.EffectiveAt)
	r.ArrivalsPerHour = uint32(v.ArrivalsPerHour)
	return r
}
func decodeAmanRunwayRatePoint(v *pb.AmanRunwayRatePoint) *aman.RunwayGroupRatePoint {
	if v == nil {
		return nil
	}
	r := &aman.RunwayGroupRatePoint{}
	r.EffectiveAt = instant(v.EffectiveAt)
	r.ArrivalsPerHour = uint32(v.ArrivalsPerHour)
	return r
}
func encodeAmanSameStarSpacing(v *aman.SameSTARSpacingPolicy) *pb.AmanSameStarSpacing {
	if v == nil {
		return nil
	}
	r := &pb.AmanSameStarSpacing{}
	r.Enabled = bool(v.Enabled)
	r.ActivationRatePerHour = uint32(v.ActivationRatePerHour)
	r.MinimumEmptySlots = uint32(v.MinimumEmptySlots)
	return r
}
func decodeAmanSameStarSpacing(v *pb.AmanSameStarSpacing) *aman.SameSTARSpacingPolicy {
	if v == nil {
		return nil
	}
	r := &aman.SameSTARSpacingPolicy{}
	r.Enabled = bool(v.Enabled)
	r.ActivationRatePerHour = uint32(v.ActivationRatePerHour)
	r.MinimumEmptySlots = uint32(v.MinimumEmptySlots)
	return r
}
func encodeAmanSequenceWarning(v *aman.RunwayGroupSequenceWarning) *pb.AmanSequenceWarning {
	if v == nil {
		return nil
	}
	r := &pb.AmanSequenceWarning{}
	r.Code = string(v.Code)
	r.Callsign = string(v.Callsign)
	r.RelatedCallsign = string(v.RelatedCallsign)
	r.StarFamily = string(v.STARFamily)
	return r
}
func decodeAmanSequenceWarning(v *pb.AmanSequenceWarning) *aman.RunwayGroupSequenceWarning {
	if v == nil {
		return nil
	}
	r := &aman.RunwayGroupSequenceWarning{}
	r.Code = string(v.Code)
	r.Callsign = string(v.Callsign)
	r.RelatedCallsign = string(v.RelatedCallsign)
	r.STARFamily = string(v.StarFamily)
	return r
}
func encodeAmanGap(v *aman.RunwayGap) *pb.AmanGap {
	if v == nil {
		return nil
	}
	r := &pb.AmanGap{}
	r.Id = string(v.ID)
	r.Start = timestamp(v.Start)
	r.End = timestamp(v.End)
	r.Label = string(v.Label)
	r.CreatedBy = string(v.CreatedBy)
	r.CreatedAt = timestamp(v.CreatedAt)
	return r
}
func decodeAmanGap(v *pb.AmanGap) *aman.RunwayGap {
	if v == nil {
		return nil
	}
	r := &aman.RunwayGap{}
	r.ID = aman.RunwayGapID(v.Id)
	r.Start = instant(v.Start)
	r.End = instant(v.End)
	r.Label = string(v.Label)
	r.CreatedBy = string(v.CreatedBy)
	r.CreatedAt = instant(v.CreatedAt)
	return r
}
func encodeAmanClosure(v *aman.RunwayClosure) *pb.AmanClosure {
	if v == nil {
		return nil
	}
	r := &pb.AmanClosure{}
	r.Id = string(v.ID)
	r.Start = timestamp(v.Start)
	r.End = optionalTimestamp(v.End)
	r.Reason = string(v.Reason)
	r.CreatedBy = string(v.CreatedBy)
	r.CreatedAt = timestamp(v.CreatedAt)
	return r
}
func decodeAmanClosure(v *pb.AmanClosure) *aman.RunwayClosure {
	if v == nil {
		return nil
	}
	r := &aman.RunwayClosure{}
	r.ID = aman.RunwayClosureID(v.Id)
	r.Start = instant(v.Start)
	r.End = optionalInstant(v.End)
	r.Reason = string(v.Reason)
	r.CreatedBy = string(v.CreatedBy)
	r.CreatedAt = instant(v.CreatedAt)
	return r
}
func encodeAmanReservation(v *aman.RunwayCapacityReservation) *pb.AmanReservation {
	if v == nil {
		return nil
	}
	r := &pb.AmanReservation{}
	r.Id = string(v.ID)
	r.Start = timestamp(v.Start)
	r.End = timestamp(v.End)
	r.Label = string(v.Label)
	r.CreatedBy = string(v.CreatedBy)
	r.CreatedAt = timestamp(v.CreatedAt)
	return r
}
func decodeAmanReservation(v *pb.AmanReservation) *aman.RunwayCapacityReservation {
	if v == nil {
		return nil
	}
	r := &aman.RunwayCapacityReservation{}
	r.ID = aman.RunwayCapacityReservationID(v.Id)
	r.Start = instant(v.Start)
	r.End = instant(v.End)
	r.Label = string(v.Label)
	r.CreatedBy = string(v.CreatedBy)
	r.CreatedAt = instant(v.CreatedAt)
	return r
}
func encodeAmanFlightObservation(v *aman.FlightObservation) *pb.AmanFlightObservation {
	if v == nil {
		return nil
	}
	r := &pb.AmanFlightObservation{}
	r.Callsign = string(v.Callsign)
	r.Origin = string(v.Origin)
	r.Destination = string(v.Destination)
	r.AircraftType = optionalString[string](v.AircraftType)
	r.WakeCategory = optionalString[string](v.WakeCategory)
	r.FiledRoute = optionalString[string](v.FiledRoute)
	r.RequestedLevel = optionalNumber[int32](v.RequestedLevel)
	r.PlannedTiming = encodeAmanPlannedTiming(v.PlannedTiming)
	r.FlightPlan = encodeAmanFlightPlanFact(&v.FlightPlan)
	r.Surveillance = encodeAmanSurveillanceFact(v.Surveillance)
	r.HoldingClearance = encodeAmanHoldingClearance(v.HoldingClearance)
	r.SurveillanceSource = string(v.SurveillanceSource)
	r.Provider = string(v.Provider)
	r.TakeoffDetected = optionalTimestamp(v.TakeoffDetected)
	r.ReconciledAt = timestamp(v.ReconciledAt)
	r.SourceStatus = string(v.SourceStatus)
	r.Missing = bool(v.Missing)
	return r
}
func decodeAmanFlightObservation(v *pb.AmanFlightObservation) *aman.FlightObservation {
	if v == nil {
		return nil
	}
	r := &aman.FlightObservation{}
	r.Callsign = string(v.Callsign)
	r.Origin = string(v.Origin)
	r.Destination = string(v.Destination)
	r.AircraftType = optionalString[string](v.AircraftType)
	r.WakeCategory = optionalString[string](v.WakeCategory)
	r.FiledRoute = optionalString[string](v.FiledRoute)
	r.RequestedLevel = optionalNumber[int](v.RequestedLevel)
	r.PlannedTiming = decodeAmanPlannedTiming(v.PlannedTiming)
	r.FlightPlan = *decodeAmanFlightPlanFact(v.FlightPlan)
	r.Surveillance = decodeAmanSurveillanceFact(v.Surveillance)
	r.HoldingClearance = decodeAmanHoldingClearance(v.HoldingClearance)
	r.SurveillanceSource = aman.SurveillanceSource(v.SurveillanceSource)
	r.Provider = aman.ObservationProvider(v.Provider)
	r.TakeoffDetected = optionalInstant(v.TakeoffDetected)
	r.ReconciledAt = instant(v.ReconciledAt)
	r.SourceStatus = aman.DataStatus(v.SourceStatus)
	r.Missing = bool(v.Missing)
	return r
}
func encodeAmanPlannedTiming(v *aman.PlannedTiming) *pb.AmanPlannedTiming {
	if v == nil {
		return nil
	}
	r := &pb.AmanPlannedTiming{}
	r.EstimatedOffBlockTime = optionalTimestamp(v.EstimatedOffBlockTime)
	r.EstimatedEnrouteTime = optionalDuration(v.EstimatedEnrouteTime)
	return r
}
func decodeAmanPlannedTiming(v *pb.AmanPlannedTiming) *aman.PlannedTiming {
	if v == nil {
		return nil
	}
	r := &aman.PlannedTiming{}
	r.EstimatedOffBlockTime = optionalInstant(v.EstimatedOffBlockTime)
	r.EstimatedEnrouteTime = optionalDomainDuration(v.EstimatedEnrouteTime)
	return r
}
func encodeAmanFlightPlanFact(v *aman.FlightPlanFact) *pb.AmanFlightPlanFact {
	if v == nil {
		return nil
	}
	r := &pb.AmanFlightPlanFact{}
	r.Revision = optionalNumber[uint64](v.Revision)
	r.ObservedAt = optionalTimestamp(v.ObservedAt)
	return r
}
func decodeAmanFlightPlanFact(v *pb.AmanFlightPlanFact) *aman.FlightPlanFact {
	if v == nil {
		return nil
	}
	r := &aman.FlightPlanFact{}
	r.Revision = optionalNumber[uint64](v.Revision)
	r.ObservedAt = optionalInstant(v.ObservedAt)
	return r
}
func encodeAmanSurveillanceFact(v *aman.SurveillanceFact) *pb.AmanSurveillanceFact {
	if v == nil {
		return nil
	}
	r := &pb.AmanSurveillanceFact{}
	r.LatitudeDegrees = float64(v.LatitudeDegrees)
	r.LongitudeDegrees = float64(v.LongitudeDegrees)
	r.AltitudeFeet = optionalNumber[int32](v.AltitudeFeet)
	r.GroundspeedKnots = optionalNumber[float64](v.GroundspeedKnots)
	r.TrackTrueDegrees = optionalNumber[float64](v.TrackTrueDegrees)
	r.Sequence = optionalNumber[uint64](v.Sequence)
	r.ObservedAt = optionalTimestamp(v.ObservedAt)
	return r
}
func decodeAmanSurveillanceFact(v *pb.AmanSurveillanceFact) *aman.SurveillanceFact {
	if v == nil {
		return nil
	}
	r := &aman.SurveillanceFact{}
	r.LatitudeDegrees = float64(v.LatitudeDegrees)
	r.LongitudeDegrees = float64(v.LongitudeDegrees)
	r.AltitudeFeet = optionalNumber[int](v.AltitudeFeet)
	r.GroundspeedKnots = optionalNumber[float64](v.GroundspeedKnots)
	r.TrackTrueDegrees = optionalNumber[float64](v.TrackTrueDegrees)
	r.Sequence = optionalNumber[uint64](v.Sequence)
	r.ObservedAt = optionalInstant(v.ObservedAt)
	return r
}
func encodeAmanHoldingClearance(v *aman.HoldingClearance) *pb.AmanHoldingClearance {
	if v == nil {
		return nil
	}
	r := &pb.AmanHoldingClearance{}
	r.Hold = string(v.Hold)
	r.HoldType = string(v.HoldType)
	r.HoldEat = string(v.HoldEAT)
	r.ClearedAltitude = optionalNumber[int32](v.ClearedAltitude)
	r.ObservedAt = timestamp(v.ObservedAt)
	return r
}
func decodeAmanHoldingClearance(v *pb.AmanHoldingClearance) *aman.HoldingClearance {
	if v == nil {
		return nil
	}
	r := &aman.HoldingClearance{}
	r.Hold = string(v.Hold)
	r.HoldType = aman.HoldingClearanceType(v.HoldType)
	r.HoldEAT = string(v.HoldEat)
	r.ClearedAltitude = optionalNumber[int32](v.ClearedAltitude)
	r.ObservedAt = instant(v.ObservedAt)
	return r
}
func encodeAmanPrediction(v *aman.Prediction) *pb.AmanPrediction {
	if v == nil {
		return nil
	}
	r := &pb.AmanPrediction{}
	r.RawTeta = timestamp(v.RawTETA)
	r.RawReta = optionalTimestamp(v.RawRETA)
	r.OperationalTeta = timestamp(v.OperationalTETA)
	r.OperationalReason = string(v.OperationalReason)
	r.GeneratedAt = timestamp(v.GeneratedAt)
	r.InputObservedAt = timestamp(v.InputObservedAt)
	r.Confidence = string(v.Confidence)
	r.Publishable = bool(v.Publishable)
	r.DegradationReason = optionalString[string](v.DegradationReason)
	r.DatasetVersion = string(v.DatasetVersion)
	r.GeometryDigest = string(v.GeometryDigest)
	r.DistanceToGoNm = optionalNumber[float64](v.DistanceToGoNM)
	r.HoldingFixEta = optionalTimestamp(v.HoldingFixETA)
	r.HoldingPlan = encodeAmanHoldingPlan(v.HoldingPlan)
	r.ModelVersion = string(v.ModelVersion)
	r.ConfigVersion = string(v.ConfigVersion)
	r.Basis = string(v.Basis)
	r.PerformanceProfileId = optionalString[string](v.PerformanceProfileID)
	r.WeatherSource = optionalString[string](v.WeatherSource)
	if v.Sources != nil {
		r.Sources = make([]string, len(v.Sources))
		for i := range v.Sources {
			r.Sources[i] = string(v.Sources[i])
		}
	}
	r.Calculation = encodeAmanPredictionCalculation(v.Calculation)
	return r
}
func decodeAmanPrediction(v *pb.AmanPrediction) *aman.Prediction {
	if v == nil {
		return nil
	}
	r := &aman.Prediction{}
	r.RawTETA = instant(v.RawTeta)
	r.RawRETA = optionalInstant(v.RawReta)
	r.OperationalTETA = instant(v.OperationalTeta)
	r.OperationalReason = aman.OperationalReason(v.OperationalReason)
	r.GeneratedAt = instant(v.GeneratedAt)
	r.InputObservedAt = instant(v.InputObservedAt)
	r.Confidence = aman.Confidence(v.Confidence)
	r.Publishable = bool(v.Publishable)
	r.DegradationReason = optionalString[string](v.DegradationReason)
	r.DatasetVersion = string(v.DatasetVersion)
	r.GeometryDigest = string(v.GeometryDigest)
	r.DistanceToGoNM = optionalNumber[float64](v.DistanceToGoNm)
	r.HoldingFixETA = optionalInstant(v.HoldingFixEta)
	r.HoldingPlan = decodeAmanHoldingPlan(v.HoldingPlan)
	r.ModelVersion = string(v.ModelVersion)
	r.ConfigVersion = string(v.ConfigVersion)
	r.Basis = aman.PredictionBasis(v.Basis)
	r.PerformanceProfileID = optionalString[string](v.PerformanceProfileId)
	r.WeatherSource = optionalString[string](v.WeatherSource)
	if v.Sources != nil {
		r.Sources = make([]string, len(v.Sources))
		for i := range v.Sources {
			r.Sources[i] = string(v.Sources[i])
		}
	}
	r.Calculation = decodeAmanPredictionCalculation(v.Calculation)
	return r
}
func encodeAmanFeederEta(v *aman.FeederETAState) *pb.AmanFeederEta {
	if v == nil {
		return nil
	}
	r := &pb.AmanFeederEta{}
	r.Eta = optionalTimestamp(v.ETA)
	r.Source = string(v.Source)
	r.Passed = bool(v.Passed)
	return r
}
func decodeAmanFeederEta(v *pb.AmanFeederEta) *aman.FeederETAState {
	if v == nil {
		return nil
	}
	r := &aman.FeederETAState{}
	r.ETA = optionalInstant(v.Eta)
	r.Source = aman.FeederETASource(v.Source)
	r.Passed = bool(v.Passed)
	return r
}
func encodeAmanHoldingPlan(v *aman.HoldingPlan) *pb.AmanHoldingPlan {
	if v == nil {
		return nil
	}
	r := &pb.AmanHoldingPlan{}
	r.HoldingEntryTime = timestamp(v.HoldingEntryTime)
	r.ApproachReleaseTime = timestamp(v.ApproachReleaseTime)
	r.ExpectedHoldingDuration = durationpb.New(v.ExpectedHoldingDuration)
	r.PostHoldingTransit = durationpb.New(v.PostHoldingTransit)
	return r
}
func decodeAmanHoldingPlan(v *pb.AmanHoldingPlan) *aman.HoldingPlan {
	if v == nil {
		return nil
	}
	r := &aman.HoldingPlan{}
	r.HoldingEntryTime = instant(v.HoldingEntryTime)
	r.ApproachReleaseTime = instant(v.ApproachReleaseTime)
	r.ExpectedHoldingDuration = v.ExpectedHoldingDuration.AsDuration()
	r.PostHoldingTransit = v.PostHoldingTransit.AsDuration()
	return r
}
func encodeAmanHoldingStack(v *aman.HoldingStackState) *pb.AmanHoldingStack {
	if v == nil {
		return nil
	}
	r := &pb.AmanHoldingStack{}
	r.HoldingId = string(v.HoldingID)
	r.CandidateObservedAt = timestamp(v.CandidateObservedAt)
	r.ConsecutiveObservations = uint32(v.ConsecutiveObservations)
	r.Confirmed = bool(v.Confirmed)
	r.FirstObservedAt = timestamp(v.FirstObservedAt)
	return r
}
func decodeAmanHoldingStack(v *pb.AmanHoldingStack) *aman.HoldingStackState {
	if v == nil {
		return nil
	}
	r := &aman.HoldingStackState{}
	r.HoldingID = string(v.HoldingId)
	r.CandidateObservedAt = instant(v.CandidateObservedAt)
	r.ConsecutiveObservations = uint32(v.ConsecutiveObservations)
	r.Confirmed = bool(v.Confirmed)
	r.FirstObservedAt = instant(v.FirstObservedAt)
	return r
}
func encodeAmanPredictionCalculation(v *aman.PredictionCalculation) *pb.AmanPredictionCalculation {
	if v == nil {
		return nil
	}
	r := &pb.AmanPredictionCalculation{}
	r.NoWindDuration = durationpb.New(v.NoWindDuration)
	r.Duration = durationpb.New(v.Duration)
	if v.Legs != nil {
		r.Legs = make([]*pb.AmanPredictionLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = encodeAmanPredictionLeg(&v.Legs[i])
		}
	}
	if v.Segments != nil {
		r.Segments = make([]*pb.AmanPredictionSegment, len(v.Segments))
		for i := range v.Segments {
			r.Segments[i] = encodeAmanPredictionSegment(&v.Segments[i])
		}
	}
	return r
}
func decodeAmanPredictionCalculation(v *pb.AmanPredictionCalculation) *aman.PredictionCalculation {
	if v == nil {
		return nil
	}
	r := &aman.PredictionCalculation{}
	r.NoWindDuration = v.NoWindDuration.AsDuration()
	r.Duration = v.Duration.AsDuration()
	if v.Legs != nil {
		r.Legs = make([]aman.PredictionLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = *decodeAmanPredictionLeg(v.Legs[i])
		}
	}
	if v.Segments != nil {
		r.Segments = make([]aman.PredictionSegment, len(v.Segments))
		for i := range v.Segments {
			r.Segments[i] = *decodeAmanPredictionSegment(v.Segments[i])
		}
	}
	return r
}
func encodeAmanPredictionLeg(v *aman.PredictionLeg) *pb.AmanPredictionLeg {
	if v == nil {
		return nil
	}
	r := &pb.AmanPredictionLeg{}
	r.Id = string(v.ID)
	r.FromFix = string(v.From)
	r.ToFix = string(v.To)
	r.StartLatitude = float64(v.StartLatitude)
	r.StartLongitude = float64(v.StartLongitude)
	r.EndLatitude = float64(v.EndLatitude)
	r.EndLongitude = float64(v.EndLongitude)
	r.DistanceNm = float64(v.DistanceNM)
	r.CourseTrueDegrees = float64(v.CourseTrueDegrees)
	r.NoWindDuration = durationpb.New(v.NoWindDuration)
	r.Duration = durationpb.New(v.Duration)
	return r
}
func decodeAmanPredictionLeg(v *pb.AmanPredictionLeg) *aman.PredictionLeg {
	if v == nil {
		return nil
	}
	r := &aman.PredictionLeg{}
	r.ID = string(v.Id)
	r.From = string(v.FromFix)
	r.To = string(v.ToFix)
	r.StartLatitude = float64(v.StartLatitude)
	r.StartLongitude = float64(v.StartLongitude)
	r.EndLatitude = float64(v.EndLatitude)
	r.EndLongitude = float64(v.EndLongitude)
	r.DistanceNM = float64(v.DistanceNm)
	r.CourseTrueDegrees = float64(v.CourseTrueDegrees)
	r.NoWindDuration = v.NoWindDuration.AsDuration()
	r.Duration = v.Duration.AsDuration()
	return r
}
func encodeAmanPredictionSegment(v *aman.PredictionSegment) *pb.AmanPredictionSegment {
	if v == nil {
		return nil
	}
	r := &pb.AmanPredictionSegment{}
	r.RouteLegIndex = int32(v.RouteLegIndex)
	r.PreTod = bool(v.PreTOD)
	r.PhaseId = string(v.PhaseID)
	r.PhaseName = string(v.PhaseName)
	r.PhaseFormula = string(v.PhaseFormula)
	r.DistanceNm = float64(v.DistanceNM)
	r.CourseTrueDegrees = float64(v.CourseTrueDegrees)
	r.StartAltitudeFeet = float64(v.StartAltitudeFeet)
	r.EndAltitudeFeet = float64(v.EndAltitudeFeet)
	r.AltitudeFeet = float64(v.AltitudeFeet)
	r.IndicatedAirspeedKnots = optionalNumber[float64](v.IndicatedAirspeedKnots)
	r.NoWindGroundspeedKnots = float64(v.NoWindGroundspeedKnots)
	r.GroundspeedKnots = float64(v.GroundspeedKnots)
	r.TailwindKnots = optionalNumber[float64](v.TailwindKnots)
	r.NoWindDuration = durationpb.New(v.NoWindDuration)
	r.Duration = durationpb.New(v.Duration)
	return r
}
func decodeAmanPredictionSegment(v *pb.AmanPredictionSegment) *aman.PredictionSegment {
	if v == nil {
		return nil
	}
	r := &aman.PredictionSegment{}
	r.RouteLegIndex = int(v.RouteLegIndex)
	r.PreTOD = bool(v.PreTod)
	r.PhaseID = string(v.PhaseId)
	r.PhaseName = string(v.PhaseName)
	r.PhaseFormula = string(v.PhaseFormula)
	r.DistanceNM = float64(v.DistanceNm)
	r.CourseTrueDegrees = float64(v.CourseTrueDegrees)
	r.StartAltitudeFeet = float64(v.StartAltitudeFeet)
	r.EndAltitudeFeet = float64(v.EndAltitudeFeet)
	r.AltitudeFeet = float64(v.AltitudeFeet)
	r.IndicatedAirspeedKnots = optionalNumber[float64](v.IndicatedAirspeedKnots)
	r.NoWindGroundspeedKnots = float64(v.NoWindGroundspeedKnots)
	r.GroundspeedKnots = float64(v.GroundspeedKnots)
	r.TailwindKnots = optionalNumber[float64](v.TailwindKnots)
	r.NoWindDuration = v.NoWindDuration.AsDuration()
	r.Duration = v.Duration.AsDuration()
	return r
}
func encodeAmanRawTetaSample(v *aman.RawTETASample) *pb.AmanRawTetaSample {
	if v == nil {
		return nil
	}
	r := &pb.AmanRawTetaSample{}
	r.Teta = timestamp(v.TETA)
	r.GeneratedAt = timestamp(v.GeneratedAt)
	return r
}
func decodeAmanRawTetaSample(v *pb.AmanRawTetaSample) *aman.RawTETASample {
	if v == nil {
		return nil
	}
	r := &aman.RawTETASample{}
	r.TETA = instant(v.Teta)
	r.GeneratedAt = instant(v.GeneratedAt)
	return r
}
func encodeAmanBaseline(v *aman.BaselineState) *pb.AmanBaseline {
	if v == nil {
		return nil
	}
	r := &pb.AmanBaseline{}
	r.ArrivalAt = timestamp(v.ArrivalAt)
	r.AirborneSensedAt = timestamp(v.AirborneSensedAt)
	r.Source = string(v.Source)
	r.Confidence = string(v.Confidence)
	r.DegradationReason = optionalString[string](v.DegradationReason)
	r.SpeedDefaultsVersion = string(v.SpeedDefaultsVersion)
	r.FlightPlanRevision = optionalNumber[uint64](v.FlightPlanRevision)
	r.FlightPlanObservedAt = timestamp(v.FlightPlanObservedAt)
	r.ModelVersion = string(v.ModelVersion)
	r.ConfigVersion = string(v.ConfigVersion)
	return r
}
func decodeAmanBaseline(v *pb.AmanBaseline) *aman.BaselineState {
	if v == nil {
		return nil
	}
	r := &aman.BaselineState{}
	r.ArrivalAt = instant(v.ArrivalAt)
	r.AirborneSensedAt = instant(v.AirborneSensedAt)
	r.Source = aman.BaselineSource(v.Source)
	r.Confidence = aman.Confidence(v.Confidence)
	r.DegradationReason = optionalString[aman.BaselineDegradationReason](v.DegradationReason)
	r.SpeedDefaultsVersion = string(v.SpeedDefaultsVersion)
	r.FlightPlanRevision = optionalNumber[uint64](v.FlightPlanRevision)
	r.FlightPlanObservedAt = instant(v.FlightPlanObservedAt)
	r.ModelVersion = string(v.ModelVersion)
	r.ConfigVersion = string(v.ConfigVersion)
	return r
}
func encodeAmanRouteProgress(v *aman.RouteProgress) *pb.AmanRouteProgress {
	if v == nil {
		return nil
	}
	r := &pb.AmanRouteProgress{}
	r.GeometryDigest = string(v.GeometryDigest)
	r.ManifestRevision = int64(v.ManifestRevision)
	r.TerminalDigest = string(v.TerminalDigest)
	r.FlightPlanRevision = uint64(v.FlightPlanRevision)
	r.RouteFactId = string(v.RouteFactID)
	r.RunwayGroupId = string(v.RunwayGroupID)
	r.LegIndex = int32(v.LegIndex)
	r.RejoinLegIndex = int32(v.RejoinLegIndex)
	r.AlongTrackNm = float64(v.AlongTrackNM)
	r.RecoveryCandidateFix = string(v.RecoveryCandidateFix)
	r.RecoveryCandidateSamples = uint32(v.RecoveryCandidateSamples)
	r.DescentConfirmed = bool(v.DescentConfirmed)
	r.DescentEvidenceSamples = uint32(v.DescentEvidenceSamples)
	return r
}
func decodeAmanRouteProgress(v *pb.AmanRouteProgress) *aman.RouteProgress {
	if v == nil {
		return nil
	}
	r := &aman.RouteProgress{}
	r.GeometryDigest = string(v.GeometryDigest)
	r.ManifestRevision = int64(v.ManifestRevision)
	r.TerminalDigest = string(v.TerminalDigest)
	r.FlightPlanRevision = uint64(v.FlightPlanRevision)
	r.RouteFactID = string(v.RouteFactId)
	r.RunwayGroupID = aman.RunwayGroupID(v.RunwayGroupId)
	r.LegIndex = int(v.LegIndex)
	r.RejoinLegIndex = int(v.RejoinLegIndex)
	r.AlongTrackNM = float64(v.AlongTrackNm)
	r.RecoveryCandidateFix = string(v.RecoveryCandidateFix)
	r.RecoveryCandidateSamples = uint8(v.RecoveryCandidateSamples)
	r.DescentConfirmed = bool(v.DescentConfirmed)
	r.DescentEvidenceSamples = uint8(v.DescentEvidenceSamples)
	return r
}
func encodeAmanTmaEntry(v *aman.TMAEntryState) *pb.AmanTmaEntry {
	if v == nil {
		return nil
	}
	r := &pb.AmanTmaEntry{}
	r.LastContainment = string(v.LastContainment)
	r.LastObservedAt = timestamp(v.LastObservedAt)
	r.FreezeTriggered = bool(v.FreezeTriggered)
	return r
}
func decodeAmanTmaEntry(v *pb.AmanTmaEntry) *aman.TMAEntryState {
	if v == nil {
		return nil
	}
	r := &aman.TMAEntryState{}
	r.LastContainment = aman.TMAContainment(v.LastContainment)
	r.LastObservedAt = instant(v.LastObservedAt)
	r.FreezeTriggered = bool(v.FreezeTriggered)
	return r
}
func encodeAmanOperationalException(v *aman.OperationalException) *pb.AmanOperationalException {
	if v == nil {
		return nil
	}
	r := &pb.AmanOperationalException{}
	r.Reason = string(v.Reason)
	r.DetectedAt = timestamp(v.DetectedAt)
	return r
}
func decodeAmanOperationalException(v *pb.AmanOperationalException) *aman.OperationalException {
	if v == nil {
		return nil
	}
	r := &aman.OperationalException{}
	r.Reason = aman.OperationalExceptionReason(v.Reason)
	r.DetectedAt = instant(v.DetectedAt)
	return r
}
func encodeAmanGoAroundEvidence(v *aman.GoAroundEvidence) *pb.AmanGoAroundEvidence {
	if v == nil {
		return nil
	}
	r := &pb.AmanGoAroundEvidence{}
	r.ObservedAt = timestamp(v.ObservedAt)
	r.Sequence = optionalNumber[uint64](v.Sequence)
	r.LatitudeDegrees = float64(v.LatitudeDegrees)
	r.LongitudeDegrees = float64(v.LongitudeDegrees)
	r.AltitudeFeet = int32(v.AltitudeFeet)
	r.GroundspeedKnots = float64(v.GroundspeedKnots)
	r.TrackTrueDegrees = optionalNumber[float64](v.TrackTrueDegrees)
	r.ClimbEvidence = bool(v.ClimbEvidence)
	r.TrackAwayEvidence = bool(v.TrackAwayEvidence)
	r.RunwayExitEvidence = bool(v.RunwayExitEvidence)
	return r
}
func decodeAmanGoAroundEvidence(v *pb.AmanGoAroundEvidence) *aman.GoAroundEvidence {
	if v == nil {
		return nil
	}
	r := &aman.GoAroundEvidence{}
	r.ObservedAt = instant(v.ObservedAt)
	r.Sequence = optionalNumber[uint64](v.Sequence)
	r.LatitudeDegrees = float64(v.LatitudeDegrees)
	r.LongitudeDegrees = float64(v.LongitudeDegrees)
	r.AltitudeFeet = int(v.AltitudeFeet)
	r.GroundspeedKnots = float64(v.GroundspeedKnots)
	r.TrackTrueDegrees = optionalNumber[float64](v.TrackTrueDegrees)
	r.ClimbEvidence = bool(v.ClimbEvidence)
	r.TrackAwayEvidence = bool(v.TrackAwayEvidence)
	r.RunwayExitEvidence = bool(v.RunwayExitEvidence)
	return r
}
func encodeAmanGoAroundDetection(v *aman.GoAroundDetectionState) *pb.AmanGoAroundDetection {
	if v == nil {
		return nil
	}
	r := &pb.AmanGoAroundDetection{}
	r.PolicyVersion = string(v.PolicyVersion)
	if v.Evidence != nil {
		r.Evidence = make([]*pb.AmanGoAroundEvidence, len(v.Evidence))
		for i := range v.Evidence {
			r.Evidence[i] = encodeAmanGoAroundEvidence(&v.Evidence[i])
		}
	}
	r.ArmCount = int32(v.ArmCount)
	r.ClimbCount = int32(v.ClimbCount)
	r.TrackAwayCount = int32(v.TrackAwayCount)
	r.RunwayExitCount = int32(v.RunwayExitCount)
	r.Armed = bool(v.Armed)
	r.ArmedAt = optionalTimestamp(v.ArmedAt)
	r.ArmedCorridorId = string(v.ArmedCorridorID)
	r.Episode = uint64(v.Episode)
	r.LastEmittedEpisode = uint64(v.LastEmittedEpisode)
	r.LastProcessedAt = optionalTimestamp(v.LastProcessedAt)
	r.LastProcessedSequence = optionalNumber[uint64](v.LastProcessedSequence)
	r.ThresholdCrossed = bool(v.ThresholdCrossed)
	r.AwaitingReset = bool(v.AwaitingReset)
	r.LastControllerCommandId = string(v.LastControllerCommandID)
	return r
}
func decodeAmanGoAroundDetection(v *pb.AmanGoAroundDetection) *aman.GoAroundDetectionState {
	if v == nil {
		return nil
	}
	r := &aman.GoAroundDetectionState{}
	r.PolicyVersion = string(v.PolicyVersion)
	if v.Evidence != nil {
		r.Evidence = make([]aman.GoAroundEvidence, len(v.Evidence))
		for i := range v.Evidence {
			r.Evidence[i] = *decodeAmanGoAroundEvidence(v.Evidence[i])
		}
	}
	r.ArmCount = int(v.ArmCount)
	r.ClimbCount = int(v.ClimbCount)
	r.TrackAwayCount = int(v.TrackAwayCount)
	r.RunwayExitCount = int(v.RunwayExitCount)
	r.Armed = bool(v.Armed)
	r.ArmedAt = optionalInstant(v.ArmedAt)
	r.ArmedCorridorID = string(v.ArmedCorridorId)
	r.Episode = uint64(v.Episode)
	r.LastEmittedEpisode = uint64(v.LastEmittedEpisode)
	r.LastProcessedAt = optionalInstant(v.LastProcessedAt)
	r.LastProcessedSequence = optionalNumber[uint64](v.LastProcessedSequence)
	r.ThresholdCrossed = bool(v.ThresholdCrossed)
	r.AwaitingReset = bool(v.AwaitingReset)
	r.LastControllerCommandID = string(v.LastControllerCommandId)
	return r
}
func encodeAmanLifecycle(v *aman.LifecycleState) *pb.AmanLifecycle {
	if v == nil {
		return nil
	}
	r := &pb.AmanLifecycle{}
	r.EnteredAt = timestamp(v.EnteredAt)
	r.Reason = string(v.Reason)
	r.LastEventId = string(v.LastEventID)
	r.LastEventFingerprint = string(v.LastEventFingerprint)
	r.LastEventAt = timestamp(v.LastEventAt)
	r.ReconciliationPending = bool(v.ReconciliationPending)
	r.Absence = encodeAmanAbsence(v.Absence)
	return r
}
func decodeAmanLifecycle(v *pb.AmanLifecycle) *aman.LifecycleState {
	if v == nil {
		return nil
	}
	r := &aman.LifecycleState{}
	r.EnteredAt = instant(v.EnteredAt)
	r.Reason = aman.LifecycleReason(v.Reason)
	r.LastEventID = string(v.LastEventId)
	r.LastEventFingerprint = string(v.LastEventFingerprint)
	r.LastEventAt = instant(v.LastEventAt)
	r.ReconciliationPending = bool(v.ReconciliationPending)
	r.Absence = decodeAmanAbsence(v.Absence)
	return r
}
func encodeAmanAbsence(v *aman.AbsenceState) *pb.AmanAbsence {
	if v == nil {
		return nil
	}
	r := &pb.AmanAbsence{}
	r.MissingSince = timestamp(v.MissingSince)
	r.RemovalDueAt = optionalTimestamp(v.RemovalDueAt)
	r.Remaining = durationpb.New(v.Remaining)
	return r
}
func decodeAmanAbsence(v *pb.AmanAbsence) *aman.AbsenceState {
	if v == nil {
		return nil
	}
	r := &aman.AbsenceState{}
	r.MissingSince = instant(v.MissingSince)
	r.RemovalDueAt = optionalInstant(v.RemovalDueAt)
	r.Remaining = v.Remaining.AsDuration()
	return r
}
func encodeAmanRouteFact(v *aman.RouteFact) *pb.AmanRouteFact {
	if v == nil {
		return nil
	}
	r := &pb.AmanRouteFact{}
	r.Id = string(v.ID)
	r.Fix = string(v.Fix)
	r.State = string(v.State)
	r.ObservedAt = timestamp(v.ObservedAt)
	r.Callsign = string(v.Callsign)
	r.Issuer = string(v.Issuer)
	r.ReceivedAt = timestamp(v.ReceivedAt)
	r.DatasetVersion = string(v.DatasetVersion)
	return r
}
func decodeAmanRouteFact(v *pb.AmanRouteFact) *aman.RouteFact {
	if v == nil {
		return nil
	}
	r := &aman.RouteFact{}
	r.ID = string(v.Id)
	r.Fix = string(v.Fix)
	r.State = aman.RouteFactState(v.State)
	r.ObservedAt = instant(v.ObservedAt)
	r.Callsign = string(v.Callsign)
	r.Issuer = string(v.Issuer)
	r.ReceivedAt = instant(v.ReceivedAt)
	r.DatasetVersion = string(v.DatasetVersion)
	return r
}
func encodeAmanSlot(v *aman.Slot) *pb.AmanSlot {
	if v == nil {
		return nil
	}
	r := &pb.AmanSlot{}
	r.Time = timestamp(v.Time)
	r.RunwayGroupId = string(v.RunwayGroupID)
	r.Sequence = uint32(v.Sequence)
	r.Revision = uint64(v.Revision)
	r.Reason = string(v.Reason)
	return r
}
func decodeAmanSlot(v *pb.AmanSlot) *aman.Slot {
	if v == nil {
		return nil
	}
	r := &aman.Slot{}
	r.Time = instant(v.Time)
	r.RunwayGroupID = aman.RunwayGroupID(v.RunwayGroupId)
	r.Sequence = int(v.Sequence)
	r.Revision = aman.SequenceRevision(v.Revision)
	r.Reason = string(v.Reason)
	return r
}
func encodeAmanETAReview(v *aman.ETAReview) *pb.AmanETAReview {
	if v == nil {
		return nil
	}
	r := &pb.AmanETAReview{}
	r.Status = string(v.Status)
	r.CreatedAt = timestamp(v.CreatedAt)
	r.DeadlineAt = timestamp(v.DeadlineAt)
	r.ResolvedAt = optionalTimestamp(v.ResolvedAt)
	r.Actor = optionalString[string](v.Actor)
	r.Note = optionalString[string](v.Note)
	r.InitialBaselineTeta = timestamp(v.InitialBaselineTETA)
	r.CalculatedOperationalTeta = timestamp(v.CalculatedOperationalTETA)
	r.SelectedTeta = timestamp(v.SelectedTETA)
	r.ManualTeta = optionalTimestamp(v.ManualTETA)
	return r
}
func decodeAmanETAReview(v *pb.AmanETAReview) *aman.ETAReview {
	if v == nil {
		return nil
	}
	r := &aman.ETAReview{}
	r.Status = aman.ETAReviewStatus(v.Status)
	r.CreatedAt = instant(v.CreatedAt)
	r.DeadlineAt = instant(v.DeadlineAt)
	r.ResolvedAt = optionalInstant(v.ResolvedAt)
	r.Actor = optionalString[string](v.Actor)
	r.Note = optionalString[string](v.Note)
	r.InitialBaselineTETA = instant(v.InitialBaselineTeta)
	r.CalculatedOperationalTETA = instant(v.CalculatedOperationalTeta)
	r.SelectedTETA = instant(v.SelectedTeta)
	r.ManualTETA = optionalInstant(v.ManualTeta)
	return r
}
func encodeAmanQueueOffer(v *aman.QueueOffer) *pb.AmanQueueOffer {
	if v == nil {
		return nil
	}
	r := &pb.AmanQueueOffer{}
	r.Callsign = string(v.Callsign)
	r.RunwayGroupId = string(v.RunwayGroupID)
	r.CandidateSlot = encodeAmanSlot(&v.CandidateSlot)
	r.QueuePosition = uint32(v.QueuePosition)
	r.ExpiresAt = timestamp(v.ExpiresAt)
	r.AirportRevision = uint64(v.AirportRevision)
	r.Reason = string(v.Reason)
	return r
}
func decodeAmanQueueOffer(v *pb.AmanQueueOffer) *aman.QueueOffer {
	if v == nil {
		return nil
	}
	r := &aman.QueueOffer{}
	r.Callsign = string(v.Callsign)
	r.RunwayGroupID = aman.RunwayGroupID(v.RunwayGroupId)
	r.CandidateSlot = *decodeAmanSlot(v.CandidateSlot)
	r.QueuePosition = int(v.QueuePosition)
	r.ExpiresAt = instant(v.ExpiresAt)
	r.AirportRevision = aman.SequenceRevision(v.AirportRevision)
	r.Reason = aman.QueueOfferReason(v.Reason)
	return r
}
func encodeAmanGoAroundConfirmation(v *aman.GoAroundConfirmation) *pb.AmanGoAroundConfirmation {
	if v == nil {
		return nil
	}
	r := &pb.AmanGoAroundConfirmation{}
	r.EpisodeId = string(v.EpisodeID)
	r.Reason = string(v.Reason)
	r.DetectedAt = timestamp(v.DetectedAt)
	if v.EvidenceTimes != nil {
		r.EvidenceTimes = make([]*timestamppb.Timestamp, len(v.EvidenceTimes))
		for i := range v.EvidenceTimes {
			r.EvidenceTimes[i] = timestamp(v.EvidenceTimes[i])
		}
	}
	r.Status = string(v.Status)
	r.DecidedAt = optionalTimestamp(v.DecidedAt)
	r.DecidedBy = optionalString[string](v.DecidedBy)
	r.ResultingRevision = optionalNumber[uint64](v.ResultingRevision)
	r.DecisionCommandId = optionalString[string](v.DecisionCommandID)
	return r
}
func decodeAmanGoAroundConfirmation(v *pb.AmanGoAroundConfirmation) *aman.GoAroundConfirmation {
	if v == nil {
		return nil
	}
	r := &aman.GoAroundConfirmation{}
	r.EpisodeID = string(v.EpisodeId)
	r.Reason = string(v.Reason)
	r.DetectedAt = instant(v.DetectedAt)
	if v.EvidenceTimes != nil {
		r.EvidenceTimes = make([]time.Time, len(v.EvidenceTimes))
		for i := range v.EvidenceTimes {
			r.EvidenceTimes[i] = instant(v.EvidenceTimes[i])
		}
	}
	r.Status = aman.GoAroundConfirmationStatus(v.Status)
	r.DecidedAt = optionalInstant(v.DecidedAt)
	r.DecidedBy = optionalString[string](v.DecidedBy)
	r.ResultingRevision = optionalNumber[aman.SequenceRevision](v.ResultingRevision)
	r.DecisionCommandID = optionalString[string](v.DecisionCommandId)
	return r
}
func encodeAmanGapException(v *aman.RunwayGapException) *pb.AmanGapException {
	if v == nil {
		return nil
	}
	r := &pb.AmanGapException{}
	r.GapId = string(v.GapID)
	r.RunwayGroupId = string(v.RunwayGroupID)
	r.Opportunity = timestamp(v.Opportunity)
	r.CommandId = string(v.CommandID)
	r.Callsign = string(v.Callsign)
	return r
}
func decodeAmanGapException(v *pb.AmanGapException) *aman.RunwayGapException {
	if v == nil {
		return nil
	}
	r := &aman.RunwayGapException{}
	r.GapID = aman.RunwayGapID(v.GapId)
	r.RunwayGroupID = aman.RunwayGroupID(v.RunwayGroupId)
	r.Opportunity = instant(v.Opportunity)
	r.CommandID = string(v.CommandId)
	r.Callsign = string(v.Callsign)
	return r
}
func encodeNavDatasetVersion(v *navdata.DatasetVersion) *pb.NavDatasetVersion {
	if v == nil {
		return nil
	}
	r := &pb.NavDatasetVersion{}
	r.Cycle = string(v.Cycle)
	r.SourceRevision = string(v.SourceRevision)
	r.EffectiveFrom = timestamp(v.EffectiveFrom)
	r.EffectiveUntil = timestamp(v.EffectiveUntil)
	return r
}
func decodeNavDatasetVersion(v *pb.NavDatasetVersion) *navdata.DatasetVersion {
	if v == nil {
		return nil
	}
	r := &navdata.DatasetVersion{}
	r.Cycle = string(v.Cycle)
	r.SourceRevision = string(v.SourceRevision)
	r.EffectiveFrom = instant(v.EffectiveFrom)
	r.EffectiveUntil = instant(v.EffectiveUntil)
	return r
}
func encodeNavProvenance(v *navdata.Provenance) *pb.NavProvenance {
	if v == nil {
		return nil
	}
	r := &pb.NavProvenance{}
	r.SourceId = string(v.SourceID)
	r.SourceRevision = string(v.SourceRevision)
	r.ImportedAt = timestamp(v.ImportedAt)
	r.EffectiveFrom = timestamp(v.EffectiveFrom)
	r.EffectiveUntil = timestamp(v.EffectiveUntil)
	return r
}
func decodeNavProvenance(v *pb.NavProvenance) *navdata.Provenance {
	if v == nil {
		return nil
	}
	r := &navdata.Provenance{}
	r.SourceID = string(v.SourceId)
	r.SourceRevision = string(v.SourceRevision)
	r.ImportedAt = instant(v.ImportedAt)
	r.EffectiveFrom = instant(v.EffectiveFrom)
	r.EffectiveUntil = instant(v.EffectiveUntil)
	return r
}
func encodeNavCoordinate(v *navdata.Coordinate) *pb.NavCoordinate {
	if v == nil {
		return nil
	}
	r := &pb.NavCoordinate{}
	r.LatitudeDegrees = float64(v.LatitudeDeg)
	r.LongitudeDegrees = float64(v.LongitudeDeg)
	return r
}
func decodeNavCoordinate(v *pb.NavCoordinate) *navdata.Coordinate {
	if v == nil {
		return nil
	}
	r := &navdata.Coordinate{}
	r.LatitudeDeg = float64(v.LatitudeDegrees)
	r.LongitudeDeg = float64(v.LongitudeDegrees)
	return r
}
func encodeNavThreshold(v *navdata.Threshold) *pb.NavThreshold {
	if v == nil {
		return nil
	}
	r := &pb.NavThreshold{}
	r.Position = encodeNavCoordinate(&v.Position)
	r.ElevationFeet = optionalNumber[int32](v.ElevationFt)
	r.CourseTrueDegrees = optionalNumber[float64](v.CourseTrueDeg)
	return r
}
func decodeNavThreshold(v *pb.NavThreshold) *navdata.Threshold {
	if v == nil {
		return nil
	}
	r := &navdata.Threshold{}
	r.Position = *decodeNavCoordinate(v.Position)
	r.ElevationFt = optionalNumber[int](v.ElevationFeet)
	r.CourseTrueDeg = optionalNumber[float64](v.CourseTrueDegrees)
	return r
}
func encodeNavAirport(v *navdata.Airport) *pb.NavAirport {
	if v == nil {
		return nil
	}
	r := &pb.NavAirport{}
	r.Icao = string(v.ID)
	r.Name = string(v.Name)
	r.Position = encodeNavCoordinate(&v.Position)
	r.Provenance = encodeNavProvenance(&v.Provenance)
	return r
}
func decodeNavAirport(v *pb.NavAirport) *navdata.Airport {
	if v == nil {
		return nil
	}
	r := &navdata.Airport{}
	r.ID = navdata.AirportID(v.Icao)
	r.Name = string(v.Name)
	r.Position = *decodeNavCoordinate(v.Position)
	r.Provenance = *decodeNavProvenance(v.Provenance)
	return r
}
func encodeNavRunway(v *navdata.Runway) *pb.NavRunway {
	if v == nil {
		return nil
	}
	r := &pb.NavRunway{}
	r.Id = string(v.ID)
	r.Airport = string(v.Airport)
	r.Threshold = encodeNavThreshold(&v.Threshold)
	r.LengthNm = float64(v.LengthNM)
	r.Provenance = encodeNavProvenance(&v.Provenance)
	return r
}
func decodeNavRunway(v *pb.NavRunway) *navdata.Runway {
	if v == nil {
		return nil
	}
	r := &navdata.Runway{}
	r.ID = navdata.RunwayID(v.Id)
	r.Airport = navdata.AirportID(v.Airport)
	r.Threshold = *decodeNavThreshold(v.Threshold)
	r.LengthNM = float64(v.LengthNm)
	r.Provenance = *decodeNavProvenance(v.Provenance)
	return r
}
func encodeNavProcedure(v *navdata.Procedure) *pb.NavProcedure {
	if v == nil {
		return nil
	}
	r := &pb.NavProcedure{}
	r.Id = string(v.ID)
	r.Airport = string(v.Airport)
	r.Kind = string(v.Kind)
	if v.Runways != nil {
		r.Runways = make([]string, len(v.Runways))
		for i := range v.Runways {
			r.Runways[i] = string(v.Runways[i])
		}
	}
	if v.Legs != nil {
		r.Legs = make([]*pb.NavLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = encodeNavLeg(&v.Legs[i])
		}
	}
	if v.Holdings != nil {
		r.Holdings = make([]*pb.NavHolding, len(v.Holdings))
		for i := range v.Holdings {
			r.Holdings[i] = encodeNavHolding(&v.Holdings[i])
		}
	}
	r.Provenance = encodeNavProvenance(&v.Provenance)
	return r
}
func decodeNavProcedure(v *pb.NavProcedure) *navdata.Procedure {
	if v == nil {
		return nil
	}
	r := &navdata.Procedure{}
	r.ID = navdata.ProcedureID(v.Id)
	r.Airport = navdata.AirportID(v.Airport)
	r.Kind = navdata.ProcedureKind(v.Kind)
	if v.Runways != nil {
		r.Runways = make([]navdata.RunwayID, len(v.Runways))
		for i := range v.Runways {
			r.Runways[i] = navdata.RunwayID(v.Runways[i])
		}
	}
	if v.Legs != nil {
		r.Legs = make([]navdata.ProcedureLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = *decodeNavLeg(v.Legs[i])
		}
	}
	if v.Holdings != nil {
		r.Holdings = make([]navdata.HoldingPattern, len(v.Holdings))
		for i := range v.Holdings {
			r.Holdings[i] = *decodeNavHolding(v.Holdings[i])
		}
	}
	r.Provenance = *decodeNavProvenance(v.Provenance)
	return r
}
func encodeNavLeg(v *navdata.ProcedureLeg) *pb.NavLeg {
	if v == nil {
		return nil
	}
	r := &pb.NavLeg{}
	r.Id = string(v.ID)
	r.PathTerminator = string(v.PathTerminator)
	r.FromFix = optionalString[string](v.FromFix)
	r.ToFix = optionalString[string](v.ToFix)
	r.FromPosition = encodeNavCoordinate(v.FromPosition)
	r.ToPosition = encodeNavCoordinate(v.ToPosition)
	r.CourseTrueDegrees = optionalNumber[float64](v.CourseTrueDeg)
	r.DistanceNm = optionalNumber[float64](v.DistanceNM)
	r.HoldingId = optionalString[string](v.HoldingID)
	return r
}
func decodeNavLeg(v *pb.NavLeg) *navdata.ProcedureLeg {
	if v == nil {
		return nil
	}
	r := &navdata.ProcedureLeg{}
	r.ID = string(v.Id)
	r.PathTerminator = navdata.PathTerminator(v.PathTerminator)
	r.FromFix = optionalString[navdata.FixID](v.FromFix)
	r.ToFix = optionalString[navdata.FixID](v.ToFix)
	r.FromPosition = decodeNavCoordinate(v.FromPosition)
	r.ToPosition = decodeNavCoordinate(v.ToPosition)
	r.CourseTrueDeg = optionalNumber[float64](v.CourseTrueDegrees)
	r.DistanceNM = optionalNumber[float64](v.DistanceNm)
	r.HoldingID = optionalString[navdata.HoldingID](v.HoldingId)
	return r
}
func encodeNavFix(v *navdata.Fix) *pb.NavFix {
	if v == nil {
		return nil
	}
	r := &pb.NavFix{}
	r.Id = string(v.ID)
	r.Position = encodeNavCoordinate(&v.Position)
	r.Provenance = encodeNavProvenance(&v.Provenance)
	return r
}
func decodeNavFix(v *pb.NavFix) *navdata.Fix {
	if v == nil {
		return nil
	}
	r := &navdata.Fix{}
	r.ID = navdata.FixID(v.Id)
	r.Position = *decodeNavCoordinate(v.Position)
	r.Provenance = *decodeNavProvenance(v.Provenance)
	return r
}
func encodeNavTerminalPath(v *navdata.TerminalPath) *pb.NavTerminalPath {
	if v == nil {
		return nil
	}
	r := &pb.NavTerminalPath{}
	r.Version = encodeNavDatasetVersion(&v.Version)
	r.Airport = string(v.Airport)
	r.StarFamily = string(v.STARFamily)
	r.FeederFix = string(v.FeederFix)
	r.HoldingToFeederDuration = optionalDuration(v.HoldingToFeederDuration)
	r.RunwayGroup = string(v.RunwayGroup)
	if v.Legs != nil {
		r.Legs = make([]*pb.NavLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = encodeNavLeg(&v.Legs[i])
		}
	}
	if v.HoldingIDs != nil {
		r.HoldingIds = make([]string, len(v.HoldingIDs))
		for i := range v.HoldingIDs {
			r.HoldingIds[i] = string(v.HoldingIDs[i])
		}
	}
	r.PublishedHeadingMagneticDegrees = optionalNumber[int32](v.PublishedHeadingMagneticDeg)
	r.Coverage = string(v.Coverage)
	if v.Unresolved != nil {
		r.Unresolved = make([]string, len(v.Unresolved))
		for i := range v.Unresolved {
			r.Unresolved[i] = string(v.Unresolved[i])
		}
	}
	r.Provenance = encodeNavProvenance(&v.Provenance)
	r.Digest = string(v.Digest)
	return r
}
func decodeNavTerminalPath(v *pb.NavTerminalPath) *navdata.TerminalPath {
	if v == nil {
		return nil
	}
	r := &navdata.TerminalPath{}
	r.Version = *decodeNavDatasetVersion(v.Version)
	r.Airport = navdata.AirportID(v.Airport)
	r.STARFamily = navdata.STARFamilyID(v.StarFamily)
	r.FeederFix = navdata.FixID(v.FeederFix)
	r.HoldingToFeederDuration = optionalDomainDuration(v.HoldingToFeederDuration)
	r.RunwayGroup = aman.RunwayGroupID(v.RunwayGroup)
	if v.Legs != nil {
		r.Legs = make([]navdata.ProcedureLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = *decodeNavLeg(v.Legs[i])
		}
	}
	if v.HoldingIds != nil {
		r.HoldingIDs = make([]navdata.HoldingID, len(v.HoldingIds))
		for i := range v.HoldingIds {
			r.HoldingIDs[i] = navdata.HoldingID(v.HoldingIds[i])
		}
	}
	r.PublishedHeadingMagneticDeg = optionalNumber[int](v.PublishedHeadingMagneticDegrees)
	r.Coverage = navdata.Coverage(v.Coverage)
	if v.Unresolved != nil {
		r.Unresolved = make([]string, len(v.Unresolved))
		for i := range v.Unresolved {
			r.Unresolved[i] = string(v.Unresolved[i])
		}
	}
	r.Provenance = *decodeNavProvenance(v.Provenance)
	r.Digest = string(v.Digest)
	r.Feeder = navdata.FeederID(r.STARFamily)
	return r
}
func encodeNavRouteQuery(v *navdata.RouteQuery) *pb.NavRouteQuery {
	if v == nil {
		return nil
	}
	r := &pb.NavRouteQuery{}
	r.Version = encodeNavDatasetVersion(&v.Version)
	r.Origin = string(v.Origin)
	r.Destination = string(v.Destination)
	r.FiledRoute = string(v.FiledRoute)
	r.ArrivalProcedure = optionalString[string](v.ArrivalProcedure)
	r.Runway = optionalString[string](v.Runway)
	r.RunwayGroup = optionalString[string](v.RunwayGroup)
	return r
}
func decodeNavRouteQuery(v *pb.NavRouteQuery) *navdata.RouteQuery {
	if v == nil {
		return nil
	}
	r := &navdata.RouteQuery{}
	r.Version = *decodeNavDatasetVersion(v.Version)
	r.Origin = navdata.AirportID(v.Origin)
	r.Destination = navdata.AirportID(v.Destination)
	r.FiledRoute = string(v.FiledRoute)
	r.ArrivalProcedure = optionalString[navdata.ProcedureID](v.ArrivalProcedure)
	r.Runway = optionalString[navdata.RunwayID](v.Runway)
	r.RunwayGroup = optionalString[aman.RunwayGroupID](v.RunwayGroup)
	return r
}
func encodeNavRouteGeometry(v *navdata.RouteGeometry) *pb.NavRouteGeometry {
	if v == nil {
		return nil
	}
	r := &pb.NavRouteGeometry{}
	r.Version = encodeNavDatasetVersion(&v.Version)
	if v.Legs != nil {
		r.Legs = make([]*pb.NavLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = encodeNavLeg(&v.Legs[i])
		}
	}
	if v.HoldingIDs != nil {
		r.HoldingIds = make([]string, len(v.HoldingIDs))
		for i := range v.HoldingIDs {
			r.HoldingIds[i] = string(v.HoldingIDs[i])
		}
	}
	r.TotalDistanceNm = float64(v.TotalDistanceNM)
	r.Coverage = string(v.Coverage)
	if v.Unresolved != nil {
		r.Unresolved = make([]string, len(v.Unresolved))
		for i := range v.Unresolved {
			r.Unresolved[i] = string(v.Unresolved[i])
		}
	}
	r.Provenance = encodeNavProvenance(&v.Provenance)
	r.Digest = string(v.Digest)
	return r
}
func decodeNavRouteGeometry(v *pb.NavRouteGeometry) *navdata.RouteGeometry {
	if v == nil {
		return nil
	}
	r := &navdata.RouteGeometry{}
	r.Version = *decodeNavDatasetVersion(v.Version)
	if v.Legs != nil {
		r.Legs = make([]navdata.ProcedureLeg, len(v.Legs))
		for i := range v.Legs {
			r.Legs[i] = *decodeNavLeg(v.Legs[i])
		}
	}
	if v.HoldingIds != nil {
		r.HoldingIDs = make([]navdata.HoldingID, len(v.HoldingIds))
		for i := range v.HoldingIds {
			r.HoldingIDs[i] = navdata.HoldingID(v.HoldingIds[i])
		}
	}
	r.TotalDistanceNM = float64(v.TotalDistanceNm)
	r.Coverage = navdata.Coverage(v.Coverage)
	if v.Unresolved != nil {
		r.Unresolved = make([]string, len(v.Unresolved))
		for i := range v.Unresolved {
			r.Unresolved[i] = string(v.Unresolved[i])
		}
	}
	r.Provenance = *decodeNavProvenance(v.Provenance)
	r.Digest = string(v.Digest)
	return r
}
func encodeAmanTimelineMapping(v *navdata.TimelineMapping) *pb.AmanTimelineMapping {
	if v == nil {
		return nil
	}
	r := &pb.AmanTimelineMapping{}
	r.Id = uint32(v.ID)
	r.Left = optionalString[string](v.Left)
	r.Right = optionalString[string](v.Right)
	return r
}
func decodeAmanTimelineMapping(v *pb.AmanTimelineMapping) *navdata.TimelineMapping {
	if v == nil {
		return nil
	}
	r := &navdata.TimelineMapping{}
	r.ID = navdata.TimelineMappingID(v.Id)
	r.Left = optionalString[navdata.STARFamilyID](v.Left)
	r.Right = optionalString[navdata.STARFamilyID](v.Right)
	return r
}
