package models

import "time"

type Strip struct {
	ID                 int32
	Version            int32
	Callsign           string
	Session            int32
	Origin             string
	Destination        string
	Alternative        *string
	Route              *string
	Remarks            *string
	AssignedSquawk     *string
	Squawk             *string
	Sid                *string
	ClearedAltitude    *int32
	Heading            *int32
	AircraftType       *string
	Runway             *string
	RequestedAltitude  *int32
	Capabilities       *string
	CommunicationType  *string
	AircraftCategory   *string
	Stand              *string
	Sequence           *int32
	State              *string
	Cleared            bool
	Owner              *string
	Bay                string
	PositionLatitude   *float64
	PositionLongitude  *float64
	PositionAltitude   *int32
	Tobt               *string
	Tsat               *string
	Ttot               *string
	Ctot               *string
	Aobt               *string
	Asat               *string
	Eobt               *string
	NextOwners         []string
	PreviousOwners     []string
	CdmStatus          *string
	ReleasePoint       *string
	PdcState           string
	PdcRequestedAt     *time.Time
	PdcMessageSequence *int32
	PdcMessageSent     *time.Time
	Marked             bool
}
