export const VACS_SUBSCRIPTIONS = [
  "auth:authenticated",
  "auth:unauthenticated",
  "signaling:connected",
  "signaling:disconnected",
  "signaling:client-list",
  "signaling:client-connected",
  "signaling:client-disconnected",
  "signaling:call-invite",
  "signaling:call-end",
  "signaling:call-reject",
  "signaling:force-call-end",
  "signaling:outgoing-call-accepted",
  "signaling:ambiguous-position",
  "signaling:add-incoming-to-call-list",
  "signaling:update-call-list",
  "webrtc:call-connected",
  "webrtc:call-disconnected",
  "webrtc:call-error",
  "error",
] as const;
