name: Build frontend

on:
  push:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      - '.github/workflows/build-frontend.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'frontend/**'
      - '.github/workflows/build-frontend.yml'

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@master
      with:
        node-version: 22.16
    - name: install dependencies
      run: npm ci
    - name: build
      run: npm run build
    - name: install Playwright browsers
      run: npx playwright install --with-deps chromium firefox
    - name: run browser visual tests
      run: npm run test:visual

  docker:
    name: Docker build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build Docker image
      uses: docker/build-push-action@v7
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        cache-from: type=gha,scope=frontend
        cache-to: ${{ github.event_name == 'push' && 'type=gha,mode=max,scope=frontend' || '' }}
